#!/usr/bin/env python3
"""Cross-provider audit of sampled Hyperlane Explorer messages."""

from __future__ import annotations

# --- github publish layout (auto-generated by sync_github_publish.py) ---
import sys
from pathlib import Path as _Path
_GITHUB_ROOT = _Path(__file__).resolve().parents[1]
_BG = _GITHUB_ROOT / "BoundaryGuard"
_EXP = _GITHUB_ROOT / "exp"
for _p in (_BG, _EXP):
    _s = str(_p)
    if _s not in sys.path:
        sys.path.insert(0, _s)
DATA = _GITHUB_ROOT.joinpath("data")
EXP = _EXP
ROOT = _GITHUB_ROOT
# --- end header ---

import argparse
import json
import time
import urllib.error
import urllib.request
from collections import defaultdict
from pathlib import Path


URLS = {
    "ethereum": {
        "1rpc": "https://public.1rpc.io/eth",
        "publicnode": "https://ethereum-rpc.publicnode.com",
        "drpc": "https://eth.drpc.org",
    },
    "polygon": {
        "1rpc": "https://public.1rpc.io/matic",
        "publicnode": "https://polygon-bor-rpc.publicnode.com",
        "drpc": "https://polygon.drpc.org",
    },
    "arbitrum": {
        "1rpc": "https://public.1rpc.io/arb",
        "publicnode": "https://arbitrum-one-rpc.publicnode.com",
        "drpc": "https://arbitrum.drpc.org",
    },
    "optimism": {
        "1rpc": "https://public.1rpc.io/op",
        "publicnode": "https://optimism-rpc.publicnode.com",
        "drpc": "https://optimism.drpc.org",
    },
}


def normalize(value: str | None) -> str | None:
    if value is None:
        return None
    return "0x" + value[2:] if value.startswith("\\x") else value


def rpc(url: str, method: str, params: list, timeout: float) -> dict:
    body = json.dumps({"jsonrpc": "2.0", "id": 1, "method": method, "params": params}).encode()
    req = urllib.request.Request(
        url,
        data=body,
        headers={"content-type": "application/json", "user-agent": "BoundaryGuard-audit/0.1"},
        method="POST",
    )
    started = time.perf_counter()
    try:
        with urllib.request.urlopen(req, timeout=timeout) as response:
            raw = response.read()
        payload = json.loads(raw)
        outcome = "rpc_error" if payload.get("error") else "null" if payload.get("result") is None else "ok"
        return {
            "outcome": outcome,
            "latency_ms": round((time.perf_counter() - started) * 1000, 3),
            "result": payload.get("result"),
            "error": payload.get("error"),
        }
    except urllib.error.HTTPError as exc:
        raw = exc.read()
        try:
            error = json.loads(raw)
        except Exception:
            error = raw.decode(errors="replace")[:500]
        return {
            "outcome": "http_error",
            "latency_ms": round((time.perf_counter() - started) * 1000, 3),
            "result": None,
            "error": error,
        }
    except Exception as exc:
        return {
            "outcome": "transport_error",
            "latency_ms": round((time.perf_counter() - started) * 1000, 3),
            "result": None,
            "error": f"{type(exc).__name__}: {exc}",
        }


def load_samples(path: Path, per_chain: int) -> list[dict]:
    grouped: dict[str, list[dict]] = defaultdict(list)
    with path.open(encoding="utf-8") as handle:
        for line in handle:
            row = json.loads(line)
            grouped[row["chain"]].append(row)
    samples: list[dict] = []
    for chain, rows in grouped.items():
        rows.sort(key=lambda row: row["nonce"])
        for k in range(per_chain):
            index = round((k + 1) * (len(rows) - 1) / (per_chain + 1))
            samples.append(rows[index])
    return samples


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--input", type=Path, default=Path("data/hyperlane_messages.jsonl"))
    parser.add_argument("--output", type=Path, default=Path("data/hyperlane_ground_truth_audit.jsonl"))
    parser.add_argument("--per-chain", type=int, default=5)
    parser.add_argument("--timeout", type=float, default=12.0)
    parser.add_argument("--delay", type=float, default=0.12)
    args = parser.parse_args()
    records: list[dict] = []
    for message in load_samples(args.input, args.per_chain):
        chain = message["chain"]
        tx_hash = normalize(message["origin_tx_hash"])
        block_hash = normalize(message["origin_block_hash"])
        mailbox = normalize(message["origin_mailbox"])
        for provider, url in URLS[chain].items():
            receipt = rpc(url, "eth_getTransactionReceipt", [tx_hash], args.timeout)
            receipt_obj = receipt.pop("result", None)
            receipt_match = bool(
                isinstance(receipt_obj, dict)
                and receipt_obj.get("transactionHash", "").lower() == tx_hash.lower()
                and receipt_obj.get("blockHash", "").lower() == block_hash.lower()
            )
            rec = {
                "chain": chain, "nonce": message["nonce"], "provider": provider,
                "method": "eth_getTransactionReceipt", "tx_hash": tx_hash,
                "block_hash": block_hash, "semantic_match": receipt_match, **receipt,
            }
            records.append(rec)
            print(chain, message["nonce"], provider, "receipt", rec["outcome"], receipt_match, flush=True)
            time.sleep(args.delay)

            logs = rpc(
                url,
                "eth_getLogs",
                [{"blockHash": block_hash, "address": mailbox}],
                args.timeout,
            )
            log_list = logs.pop("result", None)
            matching = [
                log for log in log_list or []
                if isinstance(log, dict)
                and log.get("transactionHash", "").lower() == tx_hash.lower()
                and log.get("blockHash", "").lower() == block_hash.lower()
            ]
            rec = {
                "chain": chain, "nonce": message["nonce"], "provider": provider,
                "method": "eth_getLogs:blockHash", "tx_hash": tx_hash,
                "block_hash": block_hash, "semantic_match": bool(matching),
                "result_count": len(log_list) if isinstance(log_list, list) else None,
                "matching_logs": len(matching), **logs,
            }
            records.append(rec)
            print(chain, message["nonce"], provider, "logs", rec["outcome"], bool(matching), flush=True)
            time.sleep(args.delay)

    args.output.parent.mkdir(parents=True, exist_ok=True)
    with args.output.open("w", encoding="utf-8") as handle:
        for rec in records:
            handle.write(json.dumps(rec, sort_keys=True) + "\n")
    print(f"Wrote {len(records)} audit records to {args.output}")


if __name__ == "__main__":
    main()
