#!/usr/bin/env python3
"""Collect one additional valid Polygon batch for a 300-valid-batch bound."""

from __future__ import annotations

# --- github publish layout (auto-generated by sync_github_publish.py) ---
import sys
from pathlib import Path as _Path
_GITHUB_ROOT = _Path(__file__).resolve().parents[1]
_BG = _GITHUB_ROOT / "BoundaryGuard"
_EXP = _GITHUB_ROOT / "exp"
for _p in (_BG, _EXP):
    _s = str(_p)
    if _s not in sys.path:
        sys.path.insert(0, _s)
DATA = _GITHUB_ROOT.joinpath("data")
EXP = _EXP
ROOT = _GITHUB_ROOT
# --- end header ---

import json
import math
import time

import boundaryguard_scale_gate as base


COMBINED = base.DATA / "boundaryguard_scale_normal_combined.jsonl"
SUMMARY = base.DATA / "boundaryguard_scale_normal_combined_summary.json"


def main() -> None:
    rows = base.load_chains()["polygon"]
    cfg = base.CONFIG["polygon"]
    mailbox = base.normalize(rows[0]["origin_mailbox"])
    existing = [json.loads(line) for line in COMBINED.open()]
    used = {row["start"] for row in existing if row["chain"] == "polygon"}
    lo = rows[0]["origin_block_height"] + 1
    hi = rows[-1]["origin_block_height"] - base.BATCH_WIDTH - 1
    start = next(value for value in range(lo + 137, hi, 997) if value not in used)
    end = start + base.BATCH_WIDTH - 1
    before = base.read_nonce(cfg["boundary_url"], mailbox, start - 1)
    after = base.read_nonce(cfg["boundary_url"], mailbox, end)
    primary = base.rpc_retry(
        cfg["primary_url"], "eth_getLogs",
        [{"fromBlock": hex(start), "toBlock": hex(end), "address": mailbox,
          "topics": [base.DISPATCH_TOPIC]}],
    )
    logs = primary.pop("result", None)
    returned = len(logs) if isinstance(logs, list) else None
    expected = None if before["value"] is None or after["value"] is None else after["value"] - before["value"]
    valid = expected is not None and returned is not None
    row = {
        "ts": time.time(), "chain": "polygon", "batch_index": 150,
        "start": start, "end": end, "width": base.BATCH_WIDTH, "mailbox": mailbox,
        "primary": cfg["primary_name"], "boundary": cfg["boundary_name"], "repair": cfg["repair_name"],
        "nonce_before": before["value"], "nonce_after": after["value"],
        "expected_dispatches": expected, "returned_dispatches": returned,
        "valid": valid, "alarm": valid and expected != returned,
        "primary_outcome": primary["outcome"], "primary_latency_ms": primary["latency_ms"],
        "primary_attempts": primary["attempts"], "primary_history": primary["attempt_history"],
        "boundary_before_outcome": before["outcome"], "boundary_before_attempts": before["attempts"],
        "boundary_before_latency_ms": before["latency_ms"],
        "boundary_after_outcome": after["outcome"], "boundary_after_attempts": after["attempts"],
        "boundary_after_latency_ms": after["latency_ms"],
    }
    if not valid:
        raise RuntimeError(f"top-up batch invalid: {row}")
    existing.append(row)
    existing.sort(key=lambda item: (item["chain"], item["batch_index"]))
    with COMBINED.open("w") as handle:
        for item in existing:
            handle.write(json.dumps(item, sort_keys=True) + "\n")
    summary = base.summarize(existing)
    valid_total = summary["overall"]["valid_batches"]
    summary["overall"]["zero_event_95pct_exact_upper_bound"] = 1 - math.pow(0.05, 1 / valid_total)
    SUMMARY.write_text(json.dumps(summary, indent=2, sort_keys=True) + "\n")
    print(json.dumps({"expected": expected, "returned": returned, "valid_total": valid_total,
                      "upper_bound": summary["overall"]["zero_event_95pct_exact_upper_bound"]}, indent=2))


if __name__ == "__main__":
    main()
