#!/usr/bin/env python3
"""Four-chain Mailbox.nonce() cross-check (≥100 heights/chain).

Extends the Optimism-only 47/47 check. Agreement requires ≥2 independent
readable eth_call boundaries returning the same nonce.
"""

from __future__ import annotations

# --- github publish layout (auto-generated by sync_github_publish.py) ---
import sys
from pathlib import Path as _Path
_GITHUB_ROOT = _Path(__file__).resolve().parents[1]
_BG = _GITHUB_ROOT / "BoundaryGuard"
_EXP = _GITHUB_ROOT / "exp"
for _p in (_BG, _EXP):
    _s = str(_p)
    if _s not in sys.path:
        sys.path.insert(0, _s)
DATA = _GITHUB_ROOT.joinpath("data")
EXP = _EXP
ROOT = _GITHUB_ROOT
# --- end header ---

import argparse
import json
import time
from collections import Counter
from concurrent.futures import ThreadPoolExecutor, as_completed
from datetime import datetime, timezone
from pathlib import Path

from hyperlane_identity import normalize
from rpc_probe import rpc
from scale_four_chain_1000 import CONFIG as SCALE_CFG


ROOT = _GITHUB_ROOT
MESSAGES = DATA / "hyperlane_messages.jsonl"
OUT = DATA / "boundary_nonce_crosscheck_4chain.json"
NONCE_SELECTOR = "0xaffed0e0"

# Multiple archive-capable boundaries per chain (independent orgs/URLs).
BOUNDARIES = {
    "optimism": [
        "https://optimism.drpc.org",
        "https://optimism.gateway.tenderly.co",
        "https://op-pokt.nodies.app",
        "https://optimism-mainnet.public.blastapi.io",
    ],
    "polygon": [
        "https://polygon.drpc.org",
        "https://polygon.llamarpc.com",
        "https://polygon-bor-rpc.publicnode.com",
        "https://rpc-mainnet.matic.quiknode.pro",
    ],
    "ethereum": [
        # Free public endpoints that retain historical eth_call state.
        "https://eth-mainnet.public.blastapi.io",
        "https://eth-pokt.nodies.app",
        "https://eth.merkle.io",
        "https://ethereum.rpc.thirdweb.com",
        "https://rpc.mevblocker.io",
    ],
    "arbitrum": [
        "https://arbitrum-one.public.blastapi.io",
        "https://arbitrum.gateway.tenderly.co",
        "https://arb-pokt.nodies.app",
        "https://arbitrum.drpc.org",
    ],
}


def read_nonce_fast(url: str, mailbox: str, block: int, timeout: float = 8.0) -> dict:
    """Single-shot eth_call (no multi-minute retry cascade)."""
    response = rpc(url, "eth_call", [{"to": mailbox, "data": NONCE_SELECTOR}, hex(block)], timeout)
    raw = response.get("result")
    value = None
    if response.get("outcome") == "ok" and isinstance(raw, str) and len(raw) > 2:
        try:
            value = int(raw, 16)
        except ValueError:
            value = None
            response = {**response, "outcome": "rpc_error", "error": f"unparseable: {raw!r}"}
    return {"value": value, "url": url, **{k: v for k, v in response.items() if k != "result"}}


def load_heights(chain: str, n: int) -> tuple[str, list[int]]:
    rows = []
    with MESSAGES.open() as handle:
        for line in handle:
            row = json.loads(line)
            if row.get("chain") != chain or not row.get("is_delivered"):
                continue
            if not row.get("origin_block_height"):
                continue
            rows.append(row)
    rows.sort(key=lambda r: int(r["origin_block_height"]))
    if not rows:
        raise SystemExit(f"no delivered messages for {chain}")
    mailbox = normalize(rows[0].get("origin_mailbox") or rows[0].get("mailbox"))
    if len(rows) <= n:
        blocks_set = {int(r["origin_block_height"]) for r in rows}
    else:
        picks = [rows[round(i * (len(rows) - 1) / (n - 1))] for i in range(n)]
        blocks_set = {int(r["origin_block_height"]) for r in picks}
        i = 0
        while len(blocks_set) < n and i < len(rows):
            blocks_set.add(int(rows[i]["origin_block_height"]))
            i += 1
    blocks = sorted(blocks_set)[:n]
    return mailbox, blocks


def check_block(mailbox: str, urls: list[str], block: int, timeout: float, workers: int) -> dict:
    values: dict[str, int] = {}
    with ThreadPoolExecutor(max_workers=workers) as pool:
        futs = {
            pool.submit(read_nonce_fast, url, mailbox, block, timeout): url for url in urls
        }
        for fut in as_completed(futs):
            got = fut.result()
            if got.get("value") is not None:
                values[got["url"]] = int(got["value"])
    uniq = set(values.values())
    status = "no_read"
    if len(values) >= 2:
        status = "agree" if len(uniq) == 1 else "disagree"
    elif len(values) == 1:
        status = "single_read"
    return {
        "block": block,
        "status": status,
        "n_reads": len(values),
        "unique_values": sorted(uniq),
    }


def check_chain(chain: str, per_chain: int, timeout: float, workers: int) -> dict:
    mailbox, blocks = load_heights(chain, per_chain)
    urls = BOUNDARIES[chain]
    rows = []
    agree = disagree = readable = 0
    print(f"  heights={len(blocks)} mailbox={mailbox}", flush=True)
    for i, block in enumerate(blocks, 1):
        row = check_block(mailbox, urls, block, timeout, workers)
        rows.append(row)
        if row["status"] == "agree":
            agree += 1
            readable += 1
        elif row["status"] == "disagree":
            disagree += 1
            readable += 1
        if i % 10 == 0 or i == len(blocks):
            print(
                f"  {chain} {i}/{len(blocks)} agree={agree} disagree={disagree} "
                f"readable={readable} last={row['status']}",
                flush=True,
            )
    return {
        "chain": chain,
        "mailbox": mailbox,
        "boundary_urls": urls,
        "blocks": len(blocks),
        "readable_ge2": readable,
        "agree": agree,
        "disagree": disagree,
        "agreement_rate": None if readable == 0 else agree / readable,
        "status_counts": dict(Counter(r["status"] for r in rows)),
        "rows": rows,
        "scale_primary": SCALE_CFG.get(chain, {}).get("primary_url"),
    }


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--per-chain", type=int, default=100)
    parser.add_argument("--timeout", type=float, default=8.0)
    parser.add_argument("--workers", type=int, default=4)
    parser.add_argument(
        "--chains",
        default="optimism,polygon,ethereum,arbitrum",
    )
    args = parser.parse_args()
    chains = [c.strip() for c in args.chains.split(",") if c.strip()]
    started = time.time()
    by_chain = {}
    total_agree = total_readable = total_disagree = 0
    for chain in chains:
        print(f"==== {chain} ====", flush=True)
        result = check_chain(chain, args.per_chain, args.timeout, args.workers)
        by_chain[chain] = result
        total_agree += result["agree"]
        total_readable += result["readable_ge2"]
        total_disagree += result["disagree"]
        print(
            json.dumps({k: result[k] for k in result if k != "rows"}, indent=2, sort_keys=True),
            flush=True,
        )
    summary = {
        "provenance": "live_natural_observation",
        "gate": "boundary_crosscheck_4chain",
        "observed_at": datetime.now(timezone.utc).isoformat(),
        "per_chain_target": args.per_chain,
        "timeout_s": args.timeout,
        "chains": chains,
        "by_chain": {
            c: {k: v for k, v in row.items() if k != "rows"} for c, row in by_chain.items()
        },
        "detail_rows": {c: row["rows"] for c, row in by_chain.items()},
        "overall": {
            "agree": total_agree,
            "disagree": total_disagree,
            "readable_ge2": total_readable,
            "agreement_rate": None if total_readable == 0 else total_agree / total_readable,
            "meets_4_chains": len(by_chain) >= 4,
            "meets_100_per_chain": all(
                by_chain[c]["blocks"] >= args.per_chain for c in by_chain
            ),
            "zero_disagree": total_disagree == 0,
            "pass": (
                len(by_chain) >= 4
                and all(by_chain[c]["blocks"] >= args.per_chain for c in by_chain)
                and total_disagree == 0
                and total_readable >= args.per_chain * len(by_chain) * 0.8
            ),
        },
        "elapsed_s": time.time() - started,
    }
    OUT.write_text(json.dumps(summary, indent=2, sort_keys=True) + "\n")
    print(json.dumps(summary["overall"], indent=2, sort_keys=True), flush=True)
    raise SystemExit(0 if summary["overall"]["pass"] else 2)


if __name__ == "__main__":
    main()
