#!/usr/bin/env python3
"""Validate independent boundary and repair roles on Optimism and Polygon."""

from __future__ import annotations

# --- github publish layout (auto-generated by sync_github_publish.py) ---
import sys
from pathlib import Path as _Path
_GITHUB_ROOT = _Path(__file__).resolve().parents[1]
_BG = _GITHUB_ROOT / "BoundaryGuard"
_EXP = _GITHUB_ROOT / "exp"
for _p in (_BG, _EXP):
    _s = str(_p)
    if _s not in sys.path:
        sys.path.insert(0, _s)
DATA = _GITHUB_ROOT.joinpath("data")
EXP = _EXP
ROOT = _GITHUB_ROOT
# --- end header ---

import json
import statistics
import time
from pathlib import Path

from rpc_probe import rpc


ROOT = _GITHUB_ROOT
MESSAGES = DATA / "hyperlane_messages.jsonl"
AUDIT = DATA / "hyperlane_ground_truth_audit_10.jsonl"
OUTPUT = DATA / "boundaryguard_role_gate.jsonl"
SUMMARY = DATA / "boundaryguard_role_gate_summary.json"
NONCE_SELECTOR = "0xaffed0e0"
DISPATCH_TOPIC = "0x769f711d20c679153d382254f59892613b58a97cc876b249134ac25c80f9c814"

CONFIG = {
    "optimism": {
        "primary": "official", "boundary": "drpc", "repair": "nodies",
        "boundary_url": "https://optimism.drpc.org",
        "repair_url": "https://op-pokt.nodies.app",
    },
    "polygon": {
        "primary": "tenderly", "boundary": "drpc", "repair": "quicknode",
        "boundary_url": "https://polygon.drpc.org",
        "repair_url": "https://rpc-mainnet.matic.quiknode.pro",
    },
}


def normalize(value: str) -> str:
    return "0x" + value.removeprefix("\\x").removeprefix("0x")


def retry(url: str, method: str, params: list, attempts: int = 5) -> dict:
    history = []
    for index in range(attempts):
        response = rpc(url, method, params, 20.0)
        history.append({"outcome": response["outcome"], "latency_ms": response["latency_ms"], "error": response.get("error")})
        if response["outcome"] == "ok" and response.get("result") is not None:
            return {**response, "attempts": index + 1, "history": history}
        time.sleep(index + 1)
    return {**response, "attempts": attempts, "history": history}


def nonce(url: str, mailbox: str, block: int) -> dict:
    response = retry(url, "eth_call", [{"to": mailbox, "data": NONCE_SELECTOR}, hex(block)])
    raw = response.pop("result", None)
    value = int(raw, 16) if response["outcome"] == "ok" and isinstance(raw, str) else None
    return {"value": value, **response}


def samples() -> dict[str, list[dict]]:
    grouped = {"optimism": [], "polygon": []}
    all_messages = {}
    with MESSAGES.open() as handle:
        for line in handle:
            row = json.loads(line)
            all_messages[(row["chain"], row["nonce"])] = row
            if row["chain"] == "polygon":
                grouped["polygon"].append(row)
    miss_nonces = []
    with AUDIT.open() as handle:
        for line in handle:
            row = json.loads(line)
            if (row["chain"] == "optimism" and row["provider"] == "1rpc"
                    and row["method"] == "eth_getLogs:blockHash"
                    and row["outcome"] == "ok" and row.get("result_count") == 0
                    and not row["semantic_match"]):
                miss_nonces.append(row["nonce"])
    grouped["optimism"] = [all_messages[("optimism", value)] for value in miss_nonces]
    grouped["polygon"].sort(key=lambda row: row["nonce"])
    polygon = grouped["polygon"]
    grouped["polygon"] = [polygon[round((i + 1) * (len(polygon) - 1) / 9)] for i in range(8)]
    return grouped


def main() -> None:
    records = []
    for chain, rows in samples().items():
        cfg = CONFIG[chain]
        for row in rows:
            block = row["origin_block_height"]
            mailbox = normalize(row["origin_mailbox"])
            before = nonce(cfg["boundary_url"], mailbox, block - 1)
            after = nonce(cfg["boundary_url"], mailbox, block)
            repair = retry(
                cfg["repair_url"], "eth_getLogs",
                [{"fromBlock": hex(block), "toBlock": hex(block),
                  "address": mailbox, "topics": [DISPATCH_TOPIC]}],
            )
            logs = repair.pop("result", None)
            returned = len(logs) if isinstance(logs, list) else None
            expected = None if before["value"] is None or after["value"] is None else after["value"] - before["value"]
            success = expected is not None and returned == expected
            record = {
                "chain": chain, "nonce": row["nonce"], "block": block,
                "primary_role": cfg["primary"], "boundary_role": cfg["boundary"],
                "repair_role": cfg["repair"], "expected": expected, "returned": returned,
                "success": success, "boundary_before_attempts": before["attempts"],
                "boundary_after_attempts": after["attempts"], "repair_attempts": repair["attempts"],
                "boundary_before_latency_ms": before["latency_ms"],
                "boundary_after_latency_ms": after["latency_ms"],
                "repair_latency_ms": repair["latency_ms"], "repair_history": repair["history"],
            }
            records.append(record)
            print(chain, row["nonce"], "expected", expected, "repair", returned,
                  "success", success, "attempts", (before["attempts"], after["attempts"], repair["attempts"]), flush=True)
            time.sleep(0.3)
    with OUTPUT.open("w") as handle:
        for row in records:
            handle.write(json.dumps(row, sort_keys=True) + "\n")
    summary = {}
    for chain in CONFIG:
        rows = [row for row in records if row["chain"] == chain]
        summary[chain] = {
            "cases": len(rows), "successes": sum(row["success"] for row in rows),
            "median_repair_latency_ms": statistics.median(row["repair_latency_ms"] for row in rows),
            "repair_operations_retried": sum(row["repair_attempts"] > 1 for row in rows),
            "boundary_operations_retried": sum(
                row["boundary_before_attempts"] > 1 for row in rows
            ) + sum(row["boundary_after_attempts"] > 1 for row in rows),
        }
    SUMMARY.write_text(json.dumps(summary, indent=2, sort_keys=True) + "\n")
    print(json.dumps(summary, indent=2, sort_keys=True))


if __name__ == "__main__":
    main()
