#!/usr/bin/env python3
"""Batch boundary audit, binary localization, and repair feasibility gate.

The primary trace replays saved, real 1RPC silent-empty observations at their
actual Optimism blocks. All other primary results come from the canonical
Hyperlane trace. Boundary reads and repairs are executed live through dRPC.
"""

from __future__ import annotations

# --- github publish layout (auto-generated by sync_github_publish.py) ---
import sys
from pathlib import Path as _Path
_GITHUB_ROOT = _Path(__file__).resolve().parents[1]
_BG = _GITHUB_ROOT / "BoundaryGuard"
_EXP = _GITHUB_ROOT / "exp"
for _p in (_BG, _EXP):
    _s = str(_p)
    if _s not in sys.path:
        sys.path.insert(0, _s)
DATA = _GITHUB_ROOT.joinpath("data")
EXP = _EXP
ROOT = _GITHUB_ROOT
# --- end header ---

import json
import statistics
import time
from dataclasses import dataclass
from pathlib import Path

from rpc_probe import CHAINS, rpc


ROOT = _GITHUB_ROOT
MESSAGES = DATA / "hyperlane_messages.jsonl"
AUDIT = DATA / "hyperlane_ground_truth_audit_10.jsonl"
OUTPUT = DATA / "boundaryguard_batch_gate.json"
NONCE_SELECTOR = "0xaffed0e0"
DISPATCH_TOPIC = "0x769f711d20c679153d382254f59892613b58a97cc876b249134ac25c80f9c814"
CHAIN = "optimism"
CHUNK_WIDTH = 10_000
CHUNKS_PER_BATCH = 8
LOG_CU = 60
CALL_CU = 26


def normalize(value: str) -> str:
    return "0x" + value.removeprefix("\\x").removeprefix("0x")


@dataclass(frozen=True)
class Chunk:
    start: int
    end: int


class LiveBoundary:
    def __init__(self, url: str, mailbox: str):
        self.url = url
        self.mailbox = mailbox
        self.cache: dict[int, int] = {}
        self.calls = 0
        self.records = []

    def nonce(self, block: int) -> int:
        if block in self.cache:
            return self.cache[block]
        response = None
        result = None
        for attempt in range(5):
            response = rpc(
                self.url, "eth_call",
                [{"to": self.mailbox, "data": NONCE_SELECTOR}, hex(block)], 20.0,
            )
            result = response.pop("result", None)
            if response["outcome"] == "ok" and isinstance(result, str):
                break
            time.sleep(2.0 * (attempt + 1))
        if response is None or response["outcome"] != "ok" or not isinstance(result, str):
            raise RuntimeError(f"historical nonce unavailable at {block}: {response}")
        value = int(result, 16)
        self.cache[block] = value
        self.calls += 1
        self.records.append({"block": block, "nonce": value, **response})
        time.sleep(0.2)
        return value


def load_trace() -> tuple[list[dict], list[dict]]:
    messages = []
    with MESSAGES.open() as handle:
        for line in handle:
            row = json.loads(line)
            if row["chain"] == CHAIN:
                messages.append(row)
    messages.sort(key=lambda row: row["origin_block_height"])
    misses = []
    with AUDIT.open() as handle:
        for line in handle:
            row = json.loads(line)
            if (
                row["chain"] == CHAIN and row["provider"] == "1rpc"
                and row["method"] == "eth_getLogs:blockHash"
                and row["outcome"] == "ok" and row.get("result_count") == 0
                and not row["semantic_match"]
            ):
                misses.append(row)
    return messages, misses


def make_chunks(bad_block: int, trace_lo: int, trace_hi: int) -> list[Chunk]:
    bad_chunk_start = (bad_block // CHUNK_WIDTH) * CHUNK_WIDTH
    start = bad_chunk_start - (CHUNKS_PER_BATCH // 2) * CHUNK_WIDTH
    min_start = trace_lo
    max_start = trace_hi - CHUNKS_PER_BATCH * CHUNK_WIDTH + 1
    start = min(max(start, min_start), max_start)
    return [
        Chunk(start + index * CHUNK_WIDTH, start + (index + 1) * CHUNK_WIDTH - 1)
        for index in range(CHUNKS_PER_BATCH)
    ]


def canonical_counts(chunks: list[Chunk], messages: list[dict]) -> list[int]:
    return [
        sum(chunk.start <= row["origin_block_height"] <= chunk.end for row in messages)
        for chunk in chunks
    ]


def locate_bad_chunks(
    chunks: list[Chunk], observed: list[int], boundary: LiveBoundary,
    left: int = 0, right: int | None = None,
    start_nonce: int | None = None, end_nonce: int | None = None,
    decisions: list[dict] | None = None,
) -> list[int]:
    if right is None:
        right = len(chunks)
    if decisions is None:
        decisions = []
    if start_nonce is None:
        start_nonce = boundary.nonce(chunks[left].start - 1)
    if end_nonce is None:
        end_nonce = boundary.nonce(chunks[right - 1].end)
    expected = end_nonce - start_nonce
    actual = sum(observed[left:right])
    decisions.append({
        "left_chunk": left, "right_chunk_exclusive": right,
        "start_block": chunks[left].start, "end_block": chunks[right - 1].end,
        "expected": expected, "observed": actual, "mismatch": expected != actual,
    })
    if expected == actual:
        return []
    if right - left == 1:
        return [left]
    middle = (left + right) // 2
    middle_nonce = boundary.nonce(chunks[middle - 1].end)
    return (
        locate_bad_chunks(chunks, observed, boundary, left, middle,
                          start_nonce, middle_nonce, decisions)
        + locate_bad_chunks(chunks, observed, boundary, middle, right,
                            middle_nonce, end_nonce, decisions)
    )


def repair_chunk(url: str, mailbox: str, chunk: Chunk) -> dict:
    response = None
    logs = None
    for attempt in range(5):
        response = rpc(
            url, "eth_getLogs",
            [{"fromBlock": hex(chunk.start), "toBlock": hex(chunk.end),
              "address": mailbox, "topics": [DISPATCH_TOPIC]}], 20.0,
        )
        logs = response.pop("result", None)
        if response["outcome"] == "ok" and isinstance(logs, list):
            break
        time.sleep(2.0 * (attempt + 1))
    assert response is not None
    count = len(logs) if isinstance(logs, list) else None
    time.sleep(0.25)
    return {"count": count, **response}


def run_scenario(messages: list[dict], mailbox: str, bad_block: int | None) -> dict:
    trace_lo = messages[0]["origin_block_height"] + 1
    trace_hi = messages[-1]["origin_block_height"] - 1
    anchor = bad_block if bad_block is not None else messages[len(messages) // 2]["origin_block_height"]
    chunks = make_chunks(anchor, trace_lo, trace_hi)
    canonical = canonical_counts(chunks, messages)
    observed = list(canonical)
    omitted = 0
    actual_bad_index = None
    if bad_block is not None:
        actual_bad_index = next(index for index, chunk in enumerate(chunks) if chunk.start <= bad_block <= chunk.end)
        omitted = sum(row["origin_block_height"] == bad_block for row in messages)
        observed[actual_bad_index] -= omitted

    url = CHAINS[CHAIN]["urls"]["drpc"]
    boundary = LiveBoundary(url, mailbox)
    decisions: list[dict] = []
    located = locate_bad_chunks(chunks, observed, boundary, decisions=decisions)
    repairs = []
    for index in located:
        repair = repair_chunk(url, mailbox, chunks[index])
        expected = boundary.nonce(chunks[index].end) - boundary.nonce(chunks[index].start - 1)
        repairs.append({
            "chunk_index": index, "start": chunks[index].start, "end": chunks[index].end,
            "expected": expected, "success": repair["count"] == expected, **repair,
        })

    primary_log_calls = len(chunks)
    repair_log_calls = len(repairs)
    bg_cu = (primary_log_calls + repair_log_calls) * LOG_CU + boundary.calls * CALL_CU
    dual_cu = primary_log_calls * 2 * LOG_CU
    return {
        "bad_block": bad_block, "actual_bad_chunk": actual_bad_index,
        "omitted_dispatches": omitted, "chunks": [chunk.__dict__ for chunk in chunks],
        "canonical_counts": canonical, "primary_observed_counts": observed,
        "located_chunks": located, "correctly_localized": (
            located == [] if bad_block is None else located == [actual_bad_index]
        ),
        "all_repairs_succeeded": all(repair["success"] for repair in repairs),
        "boundary_calls": boundary.calls, "primary_log_calls": primary_log_calls,
        "repair_log_calls": repair_log_calls, "boundary_records": boundary.records,
        "decisions": decisions, "repairs": repairs,
        "boundaryguard_cu": bg_cu, "always_dual_cu": dual_cu,
        "cu_saving_pct": (dual_cu - bg_cu) / dual_cu * 100,
    }


def main() -> None:
    messages, misses = load_trace()
    mailbox = normalize(messages[0]["origin_mailbox"])
    scenarios = []
    # One no-fault scenario plus eight replays, each preserving one saved real
    # silent-empty failure at its original block.
    scenarios.append(run_scenario(messages, mailbox, None))
    for miss in misses:
        block = next(
            row["origin_block_height"] for row in messages if row["nonce"] == miss["nonce"]
        )
        scenario = run_scenario(messages, mailbox, block)
        scenario["source_nonce"] = miss["nonce"]
        scenario["source_primary_outcome"] = miss["outcome"]
        scenario["source_primary_result_count"] = miss["result_count"]
        scenarios.append(scenario)
        print(
            miss["nonce"], block, "located", scenario["located_chunks"],
            "boundary_calls", scenario["boundary_calls"],
            "repair", scenario["all_repairs_succeeded"],
            f"saving={scenario['cu_saving_pct']:.1f}%", flush=True,
        )

    result = {
        "configuration": {
            "chain": CHAIN, "chunk_width": CHUNK_WIDTH,
            "chunks_per_batch": CHUNKS_PER_BATCH,
            "primary": "1RPC saved-real-failure trace replay",
            "boundary_and_repair": "dRPC live historical RPC",
            "log_cu": LOG_CU, "eth_call_cu": CALL_CU,
        },
        "summary": {
            "fault_scenarios": len(scenarios) - 1,
            "correctly_localized": sum(s["correctly_localized"] for s in scenarios[1:]),
            "successfully_repaired": sum(s["all_repairs_succeeded"] for s in scenarios[1:]),
            "normal_false_alarm": not scenarios[0]["correctly_localized"],
            "normal_cu_saving_pct": scenarios[0]["cu_saving_pct"],
            "median_fault_cu_saving_pct": statistics.median(
                s["cu_saving_pct"] for s in scenarios[1:]
            ),
        },
        "scenarios": scenarios,
    }
    OUTPUT.write_text(json.dumps(result, indent=2, sort_keys=True) + "\n")
    print(json.dumps(result["summary"], indent=2, sort_keys=True))
    print(f"Wrote {OUTPUT}")


if __name__ == "__main__":
    main()
