#!/usr/bin/env python3
"""P3: re-probe paper unavailable batches with archive-capable boundary fallbacks.

Compares original Gate-1 valid=false rows against a multi-URL boundary path.
Writes data/boundary_fallback_reprobe.jsonl + summary JSON.
"""

from __future__ import annotations

# --- github publish layout (auto-generated by sync_github_publish.py) ---
import sys
from pathlib import Path as _Path
_GITHUB_ROOT = _Path(__file__).resolve().parents[1]
_BG = _GITHUB_ROOT / "BoundaryGuard"
_EXP = _GITHUB_ROOT / "exp"
for _p in (_BG, _EXP):
    _s = str(_p)
    if _s not in sys.path:
        sys.path.insert(0, _s)
DATA = _GITHUB_ROOT.joinpath("data")
EXP = _EXP
ROOT = _GITHUB_ROOT
# --- end header ---

import json
import time
from collections import Counter
from concurrent.futures import ThreadPoolExecutor, as_completed
from pathlib import Path

import boundaryguard_scale_gate as base


ROOT = _GITHUB_ROOT
SRC = DATA / "boundaryguard_scale_four_chain.jsonl"
OUT = DATA / "boundary_fallback_reprobe.jsonl"
SUMMARY = DATA / "boundary_fallback_reprobe_summary.json"

# Original primary URLs (best-effort) + expanded archive-oriented boundaries.
BOUNDARY_FALLBACKS = {
    "ethereum": [
        "https://eth.drpc.org",
        "https://ethereum.gateway.tenderly.co",
        "https://eth.llamarpc.com",
        "https://ethereum-rpc.publicnode.com",
        "https://rpc.ankr.com/eth",
    ],
    "arbitrum": [
        "https://arbitrum-one.public.blastapi.io",
        "https://arbitrum.gateway.tenderly.co",
        "https://arb-pokt.nodies.app",
        "https://arbitrum.drpc.org",
        "https://arb1.arbitrum.io/rpc",
    ],
    "optimism": [
        "https://optimism.drpc.org",
        "https://optimism.gateway.tenderly.co",
        "https://op-pokt.nodies.app",
        "https://mainnet.optimism.io",
        "https://optimism.llamarpc.com",
    ],
    "polygon": [
        "https://polygon.drpc.org",
        "https://tenderly.rpc.polygon.community",
        "https://polygon.llamarpc.com",
    ],
}

PRIMARY = {
    "ethereum": ["https://0xrpc.io/eth", "https://eth.llamarpc.com", "https://ethereum-rpc.publicnode.com"],
    "arbitrum": ["https://arb1.arbitrum.io/rpc", "https://arbitrum-one.public.blastapi.io", "https://arbitrum.drpc.org"],
    "optimism": ["https://mainnet.optimism.io", "https://optimism.drpc.org", "https://op-pokt.nodies.app"],
    "polygon": ["https://tenderly.rpc.polygon.community", "https://polygon.drpc.org"],
}


def read_nonce_any(urls: list[str], mailbox: str, block: int) -> dict:
    last = {"value": None, "outcome": "no_url", "url": None, "attempts": 0}
    for url in urls:
        got = base.read_nonce(url, mailbox, block)
        last = {**got, "url": url}
        if got.get("value") is not None:
            return last
    return last


def read_logs_any(urls: list[str], mailbox: str, start: int, end: int) -> dict:
    params = [{
        "fromBlock": hex(start),
        "toBlock": hex(end),
        "address": mailbox,
        "topics": [base.DISPATCH_TOPIC],
    }]
    last = {"result": None, "outcome": "no_url", "url": None, "count": None}
    for url in urls:
        resp = base.rpc_retry(url, "eth_getLogs", params, attempts=2)
        last = {
            "outcome": resp["outcome"],
            "url": url,
            "count": len(resp["result"]) if resp["outcome"] == "ok" and isinstance(resp.get("result"), list) else None,
            "error": resp.get("error"),
        }
        if last["count"] is not None:
            return last
    return last


def reprobe_one(row: dict) -> dict:
    chain = row["chain"]
    mailbox = row["mailbox"]
    start, end = int(row["start"]), int(row["end"])
    b_urls = BOUNDARY_FALLBACKS[chain]
    p_urls = PRIMARY[chain]
    before = read_nonce_any(b_urls, mailbox, start - 1)
    after = read_nonce_any(b_urls, mailbox, end)
    logs = read_logs_any(p_urls, mailbox, start, end)
    expected = None
    if before.get("value") is not None and after.get("value") is not None:
        expected = after["value"] - before["value"]
    returned = logs.get("count")
    valid = expected is not None and returned is not None
    alarm = valid and expected != returned
    return {
        "provenance": "live_natural_observation",
        "kind": "boundary_fallback_reprobe",
        "chain": chain,
        "start": start,
        "end": end,
        "mailbox": mailbox,
        "original_valid": bool(row.get("valid")),
        "original_boundary": row.get("boundary"),
        "original_boundary_before_outcome": row.get("boundary_before_outcome"),
        "original_boundary_after_outcome": row.get("boundary_after_outcome"),
        "original_primary_outcome": row.get("primary_outcome"),
        "nonce_before": before.get("value"),
        "nonce_after": after.get("value"),
        "boundary_before_url": before.get("url"),
        "boundary_after_url": after.get("url"),
        "boundary_before_outcome": before.get("outcome"),
        "boundary_after_outcome": after.get("outcome"),
        "returned_dispatches": returned,
        "primary_url": logs.get("url"),
        "primary_outcome": logs.get("outcome"),
        "expected_dispatches": expected,
        "valid": valid,
        "alarm": alarm,
        "recovered": (not row.get("valid")) and valid,
        "observed_at": time.time(),
    }


def main() -> None:
    rows = [json.loads(l) for l in SRC.read_text().splitlines() if l.strip()]
    unavailable = [r for r in rows if not r.get("valid")]
    print(f"unavailable_to_reprobe={len(unavailable)}", flush=True)
    results = []
    # Cap workers to reduce public-RPC ban risk.
    with ThreadPoolExecutor(max_workers=4) as pool:
        futs = {pool.submit(reprobe_one, row): row for row in unavailable}
        for i, fut in enumerate(as_completed(futs), 1):
            rec = fut.result()
            results.append(rec)
            print(
                i, rec["chain"], "recovered" if rec["recovered"] else "still_unavail",
                rec["boundary_before_outcome"], rec["boundary_after_outcome"],
                rec["primary_outcome"], flush=True,
            )

    OUT.write_text("".join(json.dumps(r, sort_keys=True) + "\n" for r in results))
    recovered = sum(1 for r in results if r["recovered"])
    still = len(results) - recovered
    alarms = sum(1 for r in results if r["alarm"])
    by_chain = Counter(r["chain"] for r in results if r["recovered"])
    still_chain = Counter(r["chain"] for r in results if not r["recovered"])
    summary = {
        "original_unavailable": len(unavailable),
        "reprobed": len(results),
        "recovered_with_boundary_fallback": recovered,
        "still_unavailable": still,
        "recovery_rate": recovered / len(results) if results else 0.0,
        "alarms_among_recovered": alarms,
        "recovered_by_chain": dict(by_chain),
        "still_by_chain": dict(still_chain),
        "implied_paper_unavailable_if_fallback": 140 - recovered,
        "implied_unavailable_rate_if_fallback": (140 - recovered) / 1281,
        "design_note": (
            "Archive-capable multi-URL boundary fallback recovers a subset of "
            "Gate-1 unavailable batches; remaining unavailability is still "
            "preferable to silent incompleteness for correctness-critical clients."
        ),
    }
    SUMMARY.write_text(json.dumps(summary, indent=2, sort_keys=True) + "\n")
    print(json.dumps(summary, indent=2), flush=True)


if __name__ == "__main__":
    main()
