#!/usr/bin/env python3
"""Cross-check Mailbox.nonce() across independent boundary providers.

Samples finalized Optimism blocks from the Table VII production workload and
reports agreement among archive-capable eth_call endpoints.
"""

from __future__ import annotations

# --- github publish layout (auto-generated by sync_github_publish.py) ---
import sys
from pathlib import Path as _Path
_GITHUB_ROOT = _Path(__file__).resolve().parents[1]
_BG = _GITHUB_ROOT / "BoundaryGuard"
_EXP = _GITHUB_ROOT / "exp"
for _p in (_BG, _EXP):
    _s = str(_p)
    if _s not in sys.path:
        sys.path.insert(0, _s)
DATA = _GITHUB_ROOT.joinpath("data")
EXP = _EXP
ROOT = _GITHUB_ROOT
# --- end header ---

import json
import time
from collections import Counter
from pathlib import Path

from boundaryguard_scale_gate import read_nonce
from hyperlane_identity import normalize


ROOT = _GITHUB_ROOT
OUT = DATA / "boundary_nonce_crosscheck.json"

OP_URLS = [
    "https://optimism.drpc.org",
    "https://optimism.gateway.tenderly.co",
    "https://optimism.llamarpc.com",
    "https://optimism-rpc.publicnode.com",
    "https://rpc.ankr.com/optimism",
]


def main() -> None:
    messages = []
    src = DATA / "relayer_proxy_live_production200.jsonl"
    if not src.exists():
        src = DATA / "hyperlane_messages.jsonl"
        for line in src.open():
            row = json.loads(line)
            if row.get("chain") == "optimism" and row.get("origin_block_height"):
                messages.append(row)
        # evenly spaced 80
        step = max(1, len(messages) // 80)
        messages = messages[::step][:80]
    else:
        for line in src.open():
            row = json.loads(line)
            messages.append(row)
        # every 4th → 50 points
        messages = messages[::4][:50]

    mailbox = normalize(messages[0].get("origin_mailbox") or messages[0].get("mailbox"))
    blocks = sorted({int(m.get("block") or m["origin_block_height"]) for m in messages})

    rows = []
    agree = 0
    disagree = 0
    readable = 0
    started = time.time()
    for block in blocks:
        values = {}
        for url in OP_URLS:
            got = read_nonce(url, mailbox, block)
            if got.get("value") is not None:
                values[url] = int(got["value"])
        uniq = set(values.values())
        status = "no_read"
        if len(values) >= 2:
            readable += 1
            if len(uniq) == 1:
                agree += 1
                status = "agree"
            else:
                disagree += 1
                status = "disagree"
        elif len(values) == 1:
            status = "single_read"
        rows.append(
            {
                "block": block,
                "status": status,
                "n_reads": len(values),
                "values": values,
                "unique_values": sorted(uniq),
            }
        )

    summary = {
        "provenance": "live_natural_observation",
        "chain": "optimism",
        "mailbox": mailbox,
        "boundary_urls": OP_URLS,
        "blocks": len(blocks),
        "readable_ge2": readable,
        "agree": agree,
        "disagree": disagree,
        "agreement_rate": None if readable == 0 else agree / readable,
        "elapsed_s": time.time() - started,
        "status_counts": dict(Counter(r["status"] for r in rows)),
        "rows": rows,
    }
    OUT.write_text(json.dumps(summary, indent=2, sort_keys=True) + "\n")
    print(json.dumps({k: summary[k] for k in summary if k != "rows"}, indent=2, sort_keys=True))


if __name__ == "__main__":
    main()
