#!/usr/bin/env python3
"""Paper-scale normal-batch gate for BoundaryGuard on two EVM chains."""

from __future__ import annotations

# --- github publish layout (auto-generated by sync_github_publish.py) ---
import sys
from pathlib import Path as _Path
_GITHUB_ROOT = _Path(__file__).resolve().parents[1]
_BG = _GITHUB_ROOT / "BoundaryGuard"
_EXP = _GITHUB_ROOT / "exp"
for _p in (_BG, _EXP):
    _s = str(_p)
    if _s not in sys.path:
        sys.path.insert(0, _s)
DATA = _GITHUB_ROOT.joinpath("data")
EXP = _EXP
ROOT = _GITHUB_ROOT
# --- end header ---

import json
import statistics
import threading
import time
from concurrent.futures import ThreadPoolExecutor
from pathlib import Path

from rpc_probe import rpc


ROOT = _GITHUB_ROOT
MESSAGES = DATA / "hyperlane_messages.jsonl"
OUTPUT = DATA / "boundaryguard_scale_normal.jsonl"
SUMMARY = DATA / "boundaryguard_scale_normal_summary.json"
NONCE_SELECTOR = "0xaffed0e0"
DISPATCH_TOPIC = "0x769f711d20c679153d382254f59892613b58a97cc876b249134ac25c80f9c814"
BATCH_WIDTH = 200
BATCHES_PER_CHAIN = 100

CONFIG = {
    "optimism": {
        "primary_name": "official",
        "primary_url": "https://mainnet.optimism.io",
        "boundary_name": "drpc",
        "boundary_url": "https://optimism.drpc.org",
        "repair_name": "nodies",
        "repair_url": "https://op-pokt.nodies.app",
    },
    "polygon": {
        "primary_name": "tenderly",
        "primary_url": "https://tenderly.rpc.polygon.community",
        "boundary_name": "drpc",
        "boundary_url": "https://polygon.drpc.org",
        "repair_name": "quicknode",
        "repair_url": "https://rpc-mainnet.matic.quiknode.pro",
    },
}


def normalize(value: str) -> str:
    return "0x" + value.removeprefix("\\x").removeprefix("0x")


def rpc_retry(url: str, method: str, params: list, attempts: int = 4) -> dict:
    history = []
    for attempt in range(attempts):
        response = rpc(url, method, params, 15.0)
        history.append({
            "attempt": attempt, "outcome": response["outcome"],
            "latency_ms": response["latency_ms"], "error": response.get("error"),
        })
        if response["outcome"] == "ok" and response.get("result") is not None:
            return {**response, "attempts": attempt + 1, "attempt_history": history}
        time.sleep(1.0 * (attempt + 1))
    return {**response, "attempts": attempts, "attempt_history": history}


def read_nonce(url: str, mailbox: str, block: int) -> dict:
    response = rpc_retry(url, "eth_call", [{"to": mailbox, "data": NONCE_SELECTOR}, hex(block)])
    raw = response.pop("result", None)
    value = None
    if response["outcome"] == "ok" and isinstance(raw, str) and len(raw) > 2:
        try:
            value = int(raw, 16)
        except ValueError:
            value = None
            response["outcome"] = "rpc_error"
            response["error"] = f"unparseable eth_call result: {raw!r}"
    return {"value": value, **response}


def load_chains() -> dict[str, list[dict]]:
    grouped = {chain: [] for chain in CONFIG}
    with MESSAGES.open() as handle:
        for line in handle:
            row = json.loads(line)
            if row["chain"] in grouped:
                grouped[row["chain"]].append(row)
    for rows in grouped.values():
        rows.sort(key=lambda row: row["origin_block_height"])
    return grouped


def intervals(rows: list[dict]) -> list[tuple[int, int]]:
    lo = rows[0]["origin_block_height"] + 1
    hi = rows[-1]["origin_block_height"] - BATCH_WIDTH - 1
    return [
        (round(lo + index * (hi - lo) / (BATCHES_PER_CHAIN - 1)),
         round(lo + index * (hi - lo) / (BATCHES_PER_CHAIN - 1)) + BATCH_WIDTH - 1)
        for index in range(BATCHES_PER_CHAIN)
    ]


def run_chain(chain: str, rows: list[dict], sink: list[dict], lock: threading.Lock) -> None:
    cfg = CONFIG[chain]
    mailbox = normalize(rows[0]["origin_mailbox"])
    for index, (start, end) in enumerate(intervals(rows)):
        before = read_nonce(cfg["boundary_url"], mailbox, start - 1)
        after = read_nonce(cfg["boundary_url"], mailbox, end)
        query = {
            "fromBlock": hex(start), "toBlock": hex(end),
            "address": mailbox, "topics": [DISPATCH_TOPIC],
        }
        primary = rpc_retry(cfg["primary_url"], "eth_getLogs", [query])
        logs = primary.pop("result", None)
        returned = len(logs) if isinstance(logs, list) else None
        expected = None if before["value"] is None or after["value"] is None else after["value"] - before["value"]
        valid = expected is not None and returned is not None
        record = {
            "ts": time.time(), "chain": chain, "batch_index": index,
            "start": start, "end": end, "width": BATCH_WIDTH,
            "mailbox": mailbox, "primary": cfg["primary_name"],
            "boundary": cfg["boundary_name"], "repair": cfg["repair_name"],
            "nonce_before": before["value"], "nonce_after": after["value"],
            "expected_dispatches": expected, "returned_dispatches": returned,
            "valid": valid, "alarm": valid and expected != returned,
            "primary_outcome": primary["outcome"], "primary_latency_ms": primary["latency_ms"],
            "primary_attempts": primary["attempts"], "primary_history": primary["attempt_history"],
            "boundary_before_outcome": before["outcome"], "boundary_before_attempts": before["attempts"],
            "boundary_before_latency_ms": before["latency_ms"],
            "boundary_after_outcome": after["outcome"], "boundary_after_attempts": after["attempts"],
            "boundary_after_latency_ms": after["latency_ms"],
        }
        with lock:
            sink.append(record)
        print(chain, index, "expected", expected, "returned", returned,
              "alarm", record["alarm"], "attempts",
              (before["attempts"], after["attempts"], primary["attempts"]), flush=True)
        time.sleep(0.25)


def summarize(records: list[dict]) -> dict:
    result = {"configuration": {"batch_width": BATCH_WIDTH, "batches_per_chain": BATCHES_PER_CHAIN}, "chains": {}}
    for chain in CONFIG:
        rows = [row for row in records if row["chain"] == chain]
        valid = [row for row in rows if row["valid"]]
        attempts = [
            attempt
            for row in rows
            for attempt in (row["primary_attempts"], row["boundary_before_attempts"], row["boundary_after_attempts"])
        ]
        latencies = [
            latency
            for row in rows
            for latency in (row["primary_latency_ms"], row["boundary_before_latency_ms"], row["boundary_after_latency_ms"])
        ]
        result["chains"][chain] = {
            "batches": len(rows), "valid_batches": len(valid),
            "alarms": sum(row["alarm"] for row in valid),
            "false_alarm_rate": sum(row["alarm"] for row in valid) / len(valid) if valid else None,
            "rpc_operations": len(rows) * 3,
            "operations_retried": sum(attempt > 1 for attempt in attempts),
            "total_extra_attempts": sum(attempt - 1 for attempt in attempts),
            "median_final_latency_ms": statistics.median(latencies) if latencies else None,
            "p95_final_latency_ms": sorted(latencies)[max(0, round(0.95 * len(latencies)) - 1)] if latencies else None,
        }
    result["overall"] = {
        "batches": len(records), "valid_batches": sum(row["valid"] for row in records),
        "alarms": sum(row["alarm"] for row in records if row["valid"]),
    }
    valid_total = result["overall"]["valid_batches"]
    result["overall"]["false_alarm_rate"] = result["overall"]["alarms"] / valid_total if valid_total else None
    return result


def main() -> None:
    grouped = load_chains()
    records: list[dict] = []
    lock = threading.Lock()
    with ThreadPoolExecutor(max_workers=2) as pool:
        futures = [pool.submit(run_chain, chain, rows, records, lock) for chain, rows in grouped.items()]
        for future in futures:
            future.result()
    records.sort(key=lambda row: (row["chain"], row["batch_index"]))
    with OUTPUT.open("w") as handle:
        for row in records:
            handle.write(json.dumps(row, sort_keys=True) + "\n")
    summary = summarize(records)
    SUMMARY.write_text(json.dumps(summary, indent=2, sort_keys=True) + "\n")
    print(json.dumps(summary, indent=2, sort_keys=True))


if __name__ == "__main__":
    main()
