#!/usr/bin/env python3
"""Replay real silent omissions against Hyperlane nonce boundaries and repair them."""

from __future__ import annotations

# --- github publish layout (auto-generated by sync_github_publish.py) ---
import sys
from pathlib import Path as _Path
_GITHUB_ROOT = _Path(__file__).resolve().parents[1]
_BG = _GITHUB_ROOT / "BoundaryGuard"
_EXP = _GITHUB_ROOT / "exp"
for _p in (_BG, _EXP):
    _s = str(_p)
    if _s not in sys.path:
        sys.path.insert(0, _s)
DATA = _GITHUB_ROOT.joinpath("data")
EXP = _EXP
ROOT = _GITHUB_ROOT
# --- end header ---

import json
import time
from pathlib import Path

from rpc_probe import CHAINS, rpc


ROOT = _GITHUB_ROOT
MESSAGES = DATA / "hyperlane_messages.jsonl"
AUDIT = DATA / "hyperlane_ground_truth_audit_10.jsonl"
OUTPUT = DATA / "boundaryguard_gate.jsonl"
NORMAL_OUTPUT = DATA / "boundaryguard_normal_gate.jsonl"
NONCE_SELECTOR = "0xaffed0e0"
DISPATCH_TOPIC = "0x769f711d20c679153d382254f59892613b58a97cc876b249134ac25c80f9c814"


def normalize(value: str) -> str:
    return "0x" + value.removeprefix("\\x").removeprefix("0x")


def call_nonce(url: str, mailbox: str, block: int) -> dict:
    response = rpc(url, "eth_call", [{"to": mailbox, "data": NONCE_SELECTOR}, hex(block)], 20.0)
    result = response.pop("result", None)
    value = int(result, 16) if response["outcome"] == "ok" and isinstance(result, str) else None
    return {"value": value, **response}


def main() -> None:
    messages = {}
    with MESSAGES.open() as handle:
        for line in handle:
            row = json.loads(line)
            messages[(row["chain"], row["nonce"])] = row

    misses = []
    with AUDIT.open() as handle:
        for line in handle:
            row = json.loads(line)
            if (
                row["provider"] == "1rpc"
                and row["method"] == "eth_getLogs:blockHash"
                and row["outcome"] == "ok"
                and not row["semantic_match"]
                and row.get("result_count") == 0
            ):
                misses.append(row)

    records = []
    for miss in misses:
        message = messages[(miss["chain"], miss["nonce"])]
        chain = miss["chain"]
        block = message["origin_block_height"]
        mailbox = normalize(message["origin_mailbox"])
        url = CHAINS[chain]["urls"]["drpc"]
        before = call_nonce(url, mailbox, block - 1)
        time.sleep(0.2)
        after = call_nonce(url, mailbox, block)
        time.sleep(0.2)
        repair = rpc(
            url,
            "eth_getLogs",
            [{
                "fromBlock": hex(block), "toBlock": hex(block),
                "address": mailbox, "topics": [DISPATCH_TOPIC],
            }],
            20.0,
        )
        repair_logs = repair.pop("result", None)
        repair_count = len(repair_logs) if isinstance(repair_logs, list) else None
        expected = None if before["value"] is None or after["value"] is None else after["value"] - before["value"]
        detected = expected is not None and miss["result_count"] != expected
        repaired = expected is not None and repair_count == expected
        record = {
            "chain": chain, "nonce": miss["nonce"], "block": block,
            "primary_provider": "1rpc", "primary_transport_outcome": miss["outcome"],
            "primary_returned": miss["result_count"], "boundary_provider": "drpc",
            "nonce_before": before["value"], "nonce_after": after["value"],
            "expected_dispatches": expected, "detected": detected,
            "repair_provider": "drpc", "repair_returned": repair_count,
            "repaired": repaired, "before": before, "after": after,
            "repair_outcome": repair["outcome"], "repair_latency_ms": repair["latency_ms"],
            "repair_error": repair["error"],
        }
        records.append(record)
        print(chain, miss["nonce"], block, "expected", expected, "primary", 0,
              "detected", detected, "repair", repair_count, repaired, flush=True)
        time.sleep(0.3)

    with OUTPUT.open("w") as handle:
        for row in records:
            handle.write(json.dumps(row, sort_keys=True) + "\n")
    print(f"detected={sum(row['detected'] for row in records)}/{len(records)}")
    print(f"repaired={sum(row['repaired'] for row in records)}/{len(records)}")
    print(f"Wrote {OUTPUT}")


def normal_gate() -> None:
    grouped = {"optimism": [], "polygon": []}
    with MESSAGES.open() as handle:
        for line in handle:
            row = json.loads(line)
            if row["chain"] in grouped:
                grouped[row["chain"]].append(row)
    records = []
    for chain, rows in grouped.items():
        rows.sort(key=lambda row: row["nonce"])
        samples = [rows[round((index + 1) * (len(rows) - 1) / 11)] for index in range(10)]
        for message in samples:
            block = message["origin_block_height"]
            mailbox = normalize(message["origin_mailbox"])
            url = CHAINS[chain]["urls"]["drpc"]
            before = call_nonce(url, mailbox, block - 1)
            time.sleep(0.15)
            after = call_nonce(url, mailbox, block)
            time.sleep(0.15)
            primary = rpc(
                url, "eth_getLogs",
                [{"fromBlock": hex(block), "toBlock": hex(block),
                  "address": mailbox, "topics": [DISPATCH_TOPIC]}], 20.0,
            )
            logs = primary.pop("result", None)
            returned = len(logs) if isinstance(logs, list) else None
            expected = None if before["value"] is None or after["value"] is None else after["value"] - before["value"]
            alarm = expected is None or returned != expected
            records.append({
                "chain": chain, "nonce": message["nonce"], "block": block,
                "expected_dispatches": expected, "returned_dispatches": returned,
                "alarm": alarm, "nonce_before": before["value"], "nonce_after": after["value"],
                "primary_outcome": primary["outcome"], "primary_latency_ms": primary["latency_ms"],
                "primary_error": primary["error"],
            })
            print(chain, message["nonce"], "expected", expected, "returned", returned,
                  "alarm", alarm, flush=True)
            time.sleep(0.25)
    with NORMAL_OUTPUT.open("w") as handle:
        for row in records:
            handle.write(json.dumps(row, sort_keys=True) + "\n")
    print(f"false_alarms={sum(row['alarm'] for row in records)}/{len(records)}")
    print(f"Wrote {NORMAL_OUTPUT}")


if __name__ == "__main__":
    import sys
    normal_gate() if "--normal" in sys.argv else main()
