#!/usr/bin/env python3
"""Trace-exact multi-fault and batch-size matrix for BoundaryGuard."""

from __future__ import annotations

# --- github publish layout (auto-generated by sync_github_publish.py) ---
import sys
from pathlib import Path as _Path
_GITHUB_ROOT = _Path(__file__).resolve().parents[1]
_BG = _GITHUB_ROOT / "BoundaryGuard"
_EXP = _GITHUB_ROOT / "exp"
for _p in (_BG, _EXP):
    _s = str(_p)
    if _s not in sys.path:
        sys.path.insert(0, _s)
DATA = _GITHUB_ROOT.joinpath("data")
EXP = _EXP
ROOT = _GITHUB_ROOT
# --- end header ---

import json
import statistics
from dataclasses import dataclass
from pathlib import Path


ROOT = _GITHUB_ROOT
MESSAGES = DATA / "hyperlane_messages.jsonl"
AUDIT = DATA / "hyperlane_ground_truth_audit_10.jsonl"
OUTPUT = DATA / "boundaryguard_matrix_gate.json"
LOG_CU = 60
CALL_CU = 26
CHUNK_WIDTH = 10_000


@dataclass(frozen=True)
class Chunk:
    start: int
    end: int


class TraceBoundary:
    def __init__(self, heights: list[int]):
        self.heights = sorted(heights)
        self.cache: dict[int, int] = {}
        self.calls = 0

    def nonce(self, block: int) -> int:
        if block not in self.cache:
            # A local exact replay of the protocol's monotonic counter. Its
            # absolute offset is irrelevant; interval differences are exact.
            self.cache[block] = sum(height <= block for height in self.heights)
            self.calls += 1
        return self.cache[block]


def load() -> tuple[dict[str, list[dict]], list[int]]:
    grouped = {"optimism": [], "polygon": []}
    with MESSAGES.open() as handle:
        for line in handle:
            row = json.loads(line)
            if row["chain"] in grouped:
                grouped[row["chain"]].append(row)
    for rows in grouped.values():
        rows.sort(key=lambda row: row["origin_block_height"])
    natural = []
    with AUDIT.open() as handle:
        for line in handle:
            row = json.loads(line)
            if (row["chain"] == "optimism" and row["provider"] == "1rpc"
                    and row["method"] == "eth_getLogs:blockHash"
                    and row["outcome"] == "ok" and row.get("result_count") == 0
                    and not row["semantic_match"]):
                natural.append(row["nonce"])
    natural_blocks = [
        next(row["origin_block_height"] for row in grouped["optimism"] if row["nonce"] == nonce)
        for nonce in natural
    ]
    return grouped, natural_blocks


def chunks_around(rows: list[dict], count: int, anchors: list[int]) -> list[Chunk]:
    lo = rows[0]["origin_block_height"] + 1
    hi = rows[-1]["origin_block_height"] - 1
    center = round(statistics.fmean(anchors))
    start = (center // CHUNK_WIDTH) * CHUNK_WIDTH - count // 2 * CHUNK_WIDTH
    start = min(max(start, lo), hi - count * CHUNK_WIDTH + 1)
    return [Chunk(start + i * CHUNK_WIDTH, start + (i + 1) * CHUNK_WIDTH - 1) for i in range(count)]


def locate(chunks: list[Chunk], observed: list[int], boundary: TraceBoundary,
           left: int = 0, right: int | None = None,
           start_nonce: int | None = None, end_nonce: int | None = None) -> list[int]:
    right = len(chunks) if right is None else right
    start_nonce = boundary.nonce(chunks[left].start - 1) if start_nonce is None else start_nonce
    end_nonce = boundary.nonce(chunks[right - 1].end) if end_nonce is None else end_nonce
    if end_nonce - start_nonce == sum(observed[left:right]):
        return []
    if right - left == 1:
        return [left]
    mid = (left + right) // 2
    mid_nonce = boundary.nonce(chunks[mid - 1].end)
    return (locate(chunks, observed, boundary, left, mid, start_nonce, mid_nonce)
            + locate(chunks, observed, boundary, mid, right, mid_nonce, end_nonce))


def scenario(chain: str, rows: list[dict], chunk_count: int, fault_blocks: list[int], source: str) -> dict:
    chunks = chunks_around(rows, chunk_count, fault_blocks or [rows[len(rows)//2]["origin_block_height"]])
    heights = [row["origin_block_height"] for row in rows]
    canonical = [sum(chunk.start <= height <= chunk.end for height in heights) for chunk in chunks]
    observed = list(canonical)
    actual_bad = set()
    effective_faults = []
    for block in fault_blocks:
        for index, chunk in enumerate(chunks):
            if chunk.start <= block <= chunk.end:
                omitted = sum(height == block for height in heights)
                if omitted:
                    observed[index] -= omitted
                    actual_bad.add(index)
                    effective_faults.append({"block": block, "omitted": omitted, "chunk": index})
                break
    boundary = TraceBoundary(heights)
    located = locate(chunks, observed, boundary)
    repair_calls = len(located)
    bg_cu = chunk_count * LOG_CU + boundary.calls * CALL_CU + repair_calls * LOG_CU
    dual_cu = chunk_count * 2 * LOG_CU
    return {
        "chain": chain, "source": source, "chunk_count": chunk_count,
        "chunk_width": CHUNK_WIDTH, "requested_faults": len(fault_blocks),
        "effective_faults": effective_faults, "bad_chunks": sorted(actual_bad),
        "located_chunks": located, "correct": located == sorted(actual_bad),
        "boundary_calls": boundary.calls, "repair_calls": repair_calls,
        "boundaryguard_cu": bg_cu, "always_dual_cu": dual_cu,
        "cu_saving_pct": (dual_cu - bg_cu) / dual_cu * 100,
    }


def evenly_spaced_blocks(rows: list[dict], count: int, chunk_count: int) -> list[int]:
    # Choose real message-bearing blocks within a central batch, one per
    # distinct chunk where possible. These are controlled omissions on Polygon.
    anchor = rows[len(rows)//2]["origin_block_height"]
    chunks = chunks_around(rows, chunk_count, [anchor])
    candidates = []
    for chunk in chunks:
        blocks = sorted({row["origin_block_height"] for row in rows if chunk.start <= row["origin_block_height"] <= chunk.end})
        if blocks:
            candidates.append(blocks[len(blocks)//2])
    if count <= len(candidates):
        return [candidates[round(i * (len(candidates)-1) / max(1, count-1))] for i in range(count)]
    return candidates


def main() -> None:
    grouped, natural = load()
    scenarios = []
    # Natural Optimism multi-fault matrix in a 16-chunk batch.
    for count in (1, 2, 4, 8):
        scenarios.append(scenario("optimism", grouped["optimism"], 16, natural[:count], "saved-real-1rpc"))
    # One real failure with 4/8/16 batch sizes.
    for chunks in (4, 8, 16):
        scenarios.append(scenario("optimism", grouped["optimism"], chunks, [natural[len(natural)//2]], "saved-real-1rpc"))
    # Polygon completes the second-chain mechanism under controlled omissions.
    for count in (1, 2, 4, 8):
        blocks = evenly_spaced_blocks(grouped["polygon"], count, 16)
        scenarios.append(scenario("polygon", grouped["polygon"], 16, blocks, "controlled-real-message-positions"))
    for chunks in (4, 8, 16):
        block = evenly_spaced_blocks(grouped["polygon"], 1, chunks)
        scenarios.append(scenario("polygon", grouped["polygon"], chunks, block, "controlled-real-message-position"))

    result = {
        "configuration": {"log_cu": LOG_CU, "eth_call_cu": CALL_CU, "chunk_width": CHUNK_WIDTH},
        "summary": {
            "scenarios": len(scenarios), "correct": sum(item["correct"] for item in scenarios),
            "mean_cu_saving_pct": statistics.fmean(item["cu_saving_pct"] for item in scenarios),
            "scenarios_saving_at_least_20pct": sum(item["cu_saving_pct"] >= 20 for item in scenarios),
        },
        "scenarios": scenarios,
    }
    OUTPUT.write_text(json.dumps(result, indent=2, sort_keys=True) + "\n")
    for item in scenarios:
        print(item["chain"], item["source"], "chunks", item["chunk_count"],
              "faults", item["requested_faults"], "bad", item["bad_chunks"],
              "located", item["located_chunks"], f"saving={item['cu_saving_pct']:.1f}%")
    print(json.dumps(result["summary"], indent=2, sort_keys=True))


if __name__ == "__main__":
    main()
