#!/usr/bin/env python3
"""Add 100 non-overlapping-in-sample normal batches for a 300-batch total."""

from __future__ import annotations

# --- github publish layout (auto-generated by sync_github_publish.py) ---
import sys
from pathlib import Path as _Path
_GITHUB_ROOT = _Path(__file__).resolve().parents[1]
_BG = _GITHUB_ROOT / "BoundaryGuard"
_EXP = _GITHUB_ROOT / "exp"
for _p in (_BG, _EXP):
    _s = str(_p)
    if _s not in sys.path:
        sys.path.insert(0, _s)
DATA = _GITHUB_ROOT.joinpath("data")
EXP = _EXP
ROOT = _GITHUB_ROOT
# --- end header ---

import json
import threading
import time
from concurrent.futures import ThreadPoolExecutor

import boundaryguard_scale_gate as base


OUTPUT = base.DATA / "boundaryguard_scale_normal_extension.jsonl"
COMBINED = base.DATA / "boundaryguard_scale_normal_combined.jsonl"
SUMMARY = base.DATA / "boundaryguard_scale_normal_combined_summary.json"


def extension_intervals(rows: list[dict]) -> list[tuple[int, int]]:
    original = base.intervals(rows)
    starts = [round((original[index][0] + original[index + 1][0]) / 2) for index in range(0, 99, 2)]
    return [(start, start + base.BATCH_WIDTH - 1) for start in starts]


def run_chain(chain: str, rows: list[dict], sink: list[dict], lock: threading.Lock) -> None:
    cfg = base.CONFIG[chain]
    mailbox = base.normalize(rows[0]["origin_mailbox"])
    for index, (start, end) in enumerate(extension_intervals(rows)):
        before = base.read_nonce(cfg["boundary_url"], mailbox, start - 1)
        after = base.read_nonce(cfg["boundary_url"], mailbox, end)
        primary = base.rpc_retry(
            cfg["primary_url"], "eth_getLogs",
            [{"fromBlock": hex(start), "toBlock": hex(end), "address": mailbox,
              "topics": [base.DISPATCH_TOPIC]}],
        )
        logs = primary.pop("result", None)
        returned = len(logs) if isinstance(logs, list) else None
        expected = None if before["value"] is None or after["value"] is None else after["value"] - before["value"]
        valid = expected is not None and returned is not None
        row = {
            "ts": time.time(), "chain": chain, "batch_index": 100 + index,
            "start": start, "end": end, "width": base.BATCH_WIDTH,
            "mailbox": mailbox, "primary": cfg["primary_name"],
            "boundary": cfg["boundary_name"], "repair": cfg["repair_name"],
            "nonce_before": before["value"], "nonce_after": after["value"],
            "expected_dispatches": expected, "returned_dispatches": returned,
            "valid": valid, "alarm": valid and expected != returned,
            "primary_outcome": primary["outcome"], "primary_latency_ms": primary["latency_ms"],
            "primary_attempts": primary["attempts"], "primary_history": primary["attempt_history"],
            "boundary_before_outcome": before["outcome"], "boundary_before_attempts": before["attempts"],
            "boundary_before_latency_ms": before["latency_ms"],
            "boundary_after_outcome": after["outcome"], "boundary_after_attempts": after["attempts"],
            "boundary_after_latency_ms": after["latency_ms"],
        }
        with lock:
            sink.append(row)
        print(chain, 100 + index, "expected", expected, "returned", returned,
              "alarm", row["alarm"], "attempts",
              (before["attempts"], after["attempts"], primary["attempts"]), flush=True)
        time.sleep(0.25)


def main() -> None:
    grouped = base.load_chains()
    extension: list[dict] = []
    lock = threading.Lock()
    with ThreadPoolExecutor(max_workers=2) as pool:
        futures = [pool.submit(run_chain, chain, rows, extension, lock) for chain, rows in grouped.items()]
        for future in futures:
            future.result()
    extension.sort(key=lambda row: (row["chain"], row["batch_index"]))
    with OUTPUT.open("w") as handle:
        for row in extension:
            handle.write(json.dumps(row, sort_keys=True) + "\n")
    original = [json.loads(line) for line in base.OUTPUT.open()]
    combined = sorted(original + extension, key=lambda row: (row["chain"], row["batch_index"]))
    with COMBINED.open("w") as handle:
        for row in combined:
            handle.write(json.dumps(row, sort_keys=True) + "\n")
    summary = base.summarize(combined)
    summary["overall"]["rule_of_three_95pct_upper_bound"] = 3 / summary["overall"]["valid_batches"]
    SUMMARY.write_text(json.dumps(summary, indent=2, sort_keys=True) + "\n")
    print(json.dumps(summary, indent=2, sort_keys=True))


if __name__ == "__main__":
    main()
