#!/usr/bin/env python3
# --- github publish layout (auto-generated by sync_github_publish.py) ---
import sys
from pathlib import Path as _Path
_GITHUB_ROOT = _Path(__file__).resolve().parents[1]
_BG = _GITHUB_ROOT / "BoundaryGuard"
_EXP = _GITHUB_ROOT / "exp"
for _p in (_BG, _EXP):
    _s = str(_p)
    if _s not in sys.path:
        sys.path.insert(0, _s)
DATA = _GITHUB_ROOT.joinpath("data")
EXP = _EXP
ROOT = _GITHUB_ROOT
# --- end header ---

"""Compare blockHash and one-block range log semantics on Optimism."""

import json
import time
from pathlib import Path

from audit_hyperlane_ground_truth import URLS, load_samples, normalize, rpc


messages = [row for row in load_samples(Path("data/hyperlane_messages.jsonl"), 10) if row["chain"] == "optimism"]
records = []
for message in messages:
    tx_hash = normalize(message["origin_tx_hash"])
    block_hash = normalize(message["origin_block_hash"])
    mailbox = normalize(message["origin_mailbox"])
    block = hex(message["origin_block_height"])
    for provider in ("1rpc", "publicnode", "drpc"):
        response = rpc(
            URLS["optimism"][provider],
            "eth_getLogs",
            [{"fromBlock": block, "toBlock": block, "address": mailbox}],
            12.0,
        )
        logs = response.pop("result", None)
        matching = [
            log for log in logs or []
            if log.get("transactionHash", "").lower() == tx_hash.lower()
            and log.get("blockHash", "").lower() == block_hash.lower()
        ]
        rec = {
            "chain": "optimism", "nonce": message["nonce"], "provider": provider,
            "method": "eth_getLogs:range1", "outcome": response["outcome"],
            "semantic_match": bool(matching),
            "result_count": len(logs) if isinstance(logs, list) else None,
            "matching_logs": len(matching), "error": response.get("error"),
            "latency_ms": response["latency_ms"],
        }
        records.append(rec)
        print(message["nonce"], provider, rec["outcome"], rec["semantic_match"], flush=True)
        time.sleep(0.15)

output = Path("data/optimism_range_semantics.jsonl")
with output.open("w", encoding="utf-8") as handle:
    for rec in records:
        handle.write(json.dumps(rec, sort_keys=True) + "\n")
print(f"Wrote {len(records)} records to {output}")
