#!/usr/bin/env python3
"""Controlled demotion FSM micro-experiment.

Drives a synthetic provider through:
  healthy → omit → quarantine → probation → recovery(healthy)

This is controlled_fault_injection evidence for the demotion *policy*, not a
multi-day live ops study.
"""

from __future__ import annotations

# --- github publish layout (auto-generated by sync_github_publish.py) ---
import sys
from pathlib import Path as _Path
_GITHUB_ROOT = _Path(__file__).resolve().parents[1]
_BG = _GITHUB_ROOT / "BoundaryGuard"
_EXP = _GITHUB_ROOT / "exp"
for _p in (_BG, _EXP):
    _s = str(_p)
    if _s not in sys.path:
        sys.path.insert(0, _s)
DATA = _GITHUB_ROOT.joinpath("data")
EXP = _EXP
ROOT = _GITHUB_ROOT
# --- end header ---

import json
from dataclasses import dataclass, field
from datetime import datetime, timezone
from pathlib import Path


ROOT = _GITHUB_ROOT
OUT = DATA / "strong_e2e" / "demotion_fsm_controlled.json"


@dataclass
class DemotionFSM:
    """Small FSM with an explicit soft-omit state before quarantine."""

    status: str = "healthy"
    omit_left: int = 0
    cooldown_left: int = 0
    canary_ok: int = 0
    demotions: int = 0
    trace: list = field(default_factory=list)

    def _log(self, event: str) -> None:
        self.trace.append({"event": event, "status": self.status,
                           "omit_left": self.omit_left, "cooldown_left": self.cooldown_left,
                           "canary_ok": self.canary_ok, "demotions": self.demotions})

    def observe(self, outcome: str, semantic_match: bool | None = None) -> None:
        """outcome in {ok, error, omit_signal, semantic_miss}."""
        if outcome == "omit_signal" and self.status == "healthy":
            self.status = "omit"
            self.omit_left = 3
            self._log("enter_omit")
            return
        if self.status == "omit":
            self.omit_left -= 1
            if outcome == "semantic_miss" or (outcome == "ok" and semantic_match is False):
                self.status = "quarantined"
                self.cooldown_left = 5
                self.demotions += 1
                self._log("omit_to_quarantine")
                return
            if self.omit_left <= 0:
                self.status = "healthy"
                self._log("omit_expired_recover")
            else:
                self._log("omit_tick")
            return
        if outcome == "semantic_miss" or (outcome == "ok" and semantic_match is False):
            self.status = "quarantined"
            self.cooldown_left = 5
            self.demotions += 1
            self._log("quarantine")
            return
        if self.status == "probation":
            if outcome == "ok" and semantic_match:
                self.canary_ok += 1
                self._log("probation_canary_ok")
                if self.canary_ok >= 3:
                    self.status = "healthy"
                    self._log("recovered_healthy")
            else:
                self.status = "quarantined"
                self.cooldown_left = 5
                self.demotions += 1
                self._log("probation_fail_requarantine")
            return
        self._log(f"observe_{outcome}")

    def tick(self) -> None:
        if self.status == "quarantined":
            self.cooldown_left -= 1
            self._log("quarantine_tick")
            if self.cooldown_left <= 0:
                self.status = "probation"
                self.canary_ok = 0
                self._log("enter_probation")


def run_scripted() -> dict:
    fsm = DemotionFSM()
    # healthy
    fsm.observe("ok", True)
    # soft omit after sparse silent miss signal
    fsm.observe("omit_signal")
    fsm.observe("ok", True)  # still in omit
    fsm.observe("ok", True)
    # escalate: confirmed semantic miss while omitted
    fsm.observe("semantic_miss")
    # quarantine cooldown
    for _ in range(5):
        fsm.tick()
    # probation canaries
    fsm.observe("ok", True)
    fsm.observe("ok", True)
    fsm.observe("ok", True)
    statuses = [t["status"] for t in fsm.trace]
    required = ["omit", "quarantined", "probation", "healthy"]
    # Compact ordered unique path, retaining final healthy even if it appeared earlier.
    seen = []
    for s in statuses:
        if s in required and (not seen or seen[-1] != s):
            seen.append(s)
    # Drop leading healthy (pre-fault) for reporting the demotion path.
    while seen and seen[0] == "healthy":
        seen = seen[1:]
    path_ok = (
        "omit" in statuses
        and "quarantined" in statuses
        and "probation" in statuses
        and statuses[-1] == "healthy"
        and fsm.demotions >= 1
    )
    return {
        "gate": "demotion_fsm_controlled",
        "provenance": "controlled_fault_injection",
        "observed_at": datetime.now(timezone.utc).isoformat(),
        "final_status": fsm.status,
        "demotions": fsm.demotions,
        "transition_path_seen": seen,
        "required_path": required,
        "trace": fsm.trace,
        "pass": path_ok and fsm.status == "healthy",
        "note": (
            "Synthetic provider-state machine with soft-omit before quarantine. "
            "Not a live multi-day ops evaluation."
        ),
    }


def main() -> None:
    OUT.parent.mkdir(parents=True, exist_ok=True)
    out = run_scripted()
    OUT.write_text(json.dumps(out, indent=2, sort_keys=True) + "\n")
    print(json.dumps({k: out[k] for k in out if k != "trace"}, indent=2, sort_keys=True))
    raise SystemExit(0 if out["pass"] else 2)


if __name__ == "__main__":
    main()
