#!/usr/bin/env python3
"""Quick gate: does real Hyperlane event density change RPC action cost?"""

from __future__ import annotations

# --- github publish layout (auto-generated by sync_github_publish.py) ---
import sys
from pathlib import Path as _Path
_GITHUB_ROOT = _Path(__file__).resolve().parents[1]
_BG = _GITHUB_ROOT / "BoundaryGuard"
_EXP = _GITHUB_ROOT / "exp"
for _p in (_BG, _EXP):
    _s = str(_p)
    if _s not in sys.path:
        sys.path.insert(0, _s)
DATA = _GITHUB_ROOT.joinpath("data")
EXP = _EXP
ROOT = _GITHUB_ROOT
# --- end header ---

import json
import random
import statistics
import time
from collections import defaultdict
from pathlib import Path

from rpc_probe import CHAINS, rpc


ROOT = _GITHUB_ROOT
MESSAGES = DATA / "hyperlane_messages.jsonl"
OUTPUT = DATA / "density_action_gate.jsonl"
SUMMARY = DATA / "density_action_gate_summary.json"
DISPATCH_TOPIC = "0x769f711d20c679153d382254f59892613b58a97cc876b249134ac25c80f9c814"
WIDTHS = (50, 100, 1000, 10000)
CHAINS_TO_TEST = ("arbitrum", "optimism", "polygon")
PROVIDERS = ("1rpc", "drpc")


def normalize_address(value: str) -> str:
    return "0x" + value.removeprefix("\\x").removeprefix("0x")


def load_messages() -> dict[str, list[dict]]:
    grouped: dict[str, list[dict]] = defaultdict(list)
    with MESSAGES.open() as handle:
        for line in handle:
            row = json.loads(line)
            if row["chain"] in CHAINS_TO_TEST:
                grouped[row["chain"]].append(row)
    for rows in grouped.values():
        rows.sort(key=lambda row: row["origin_block_height"])
    return grouped


def select_windows(rows: list[dict], width: int) -> dict[str, dict]:
    lo = rows[0]["origin_block_height"] + 1
    hi = rows[-1]["origin_block_height"] - 1
    first_bin = (lo // width) + 1
    last_bin = (hi // width) - 1
    bins = []
    heights = [row["origin_block_height"] for row in rows]
    for index in range(first_bin, last_bin + 1):
        start = index * width
        end = start + width - 1
        count = sum(start <= block <= end for block in heights)
        bins.append((count, start, end))
    if not bins:
        start = lo
        end = min(hi, lo + width - 1)
        count = sum(start <= block <= end for block in heights)
        bins = [(count, start, end)]
    bins.sort()
    selected = {
        "low": bins[0],
        "mid": bins[len(bins) // 2],
        "high": bins[-1],
    }
    return {
        label: {"expected_events": item[0], "start": item[1], "end": item[2]}
        for label, item in selected.items()
    }


def run() -> list[dict]:
    grouped = load_messages()
    records = []
    for chain in CHAINS_TO_TEST:
        rows = grouped[chain]
        mailbox = normalize_address(rows[0]["origin_mailbox"])
        for width in WIDTHS:
            for density, window in select_windows(rows, width).items():
                query = {
                    "fromBlock": hex(window["start"]),
                    "toBlock": hex(window["end"]),
                    "address": mailbox,
                    "topics": [DISPATCH_TOPIC],
                }
                for provider in PROVIDERS:
                    for repeat in range(2):
                        response = rpc(
                            CHAINS[chain]["urls"][provider],
                            "eth_getLogs",
                            [query],
                            20.0,
                        )
                        result = response.get("result")
                        returned = len(result) if isinstance(result, list) else None
                        record = {
                            "ts": time.time(),
                            "chain": chain,
                            "provider": provider,
                            "width": width,
                            "density": density,
                            "repeat": repeat,
                            "start": window["start"],
                            "end": window["end"],
                            "expected_events": window["expected_events"],
                            "returned_events": returned,
                            "semantic_match": returned == window["expected_events"],
                            "outcome": response["outcome"],
                            "latency_ms": response["latency_ms"],
                            "response_bytes": response["response_bytes"],
                            "error": response["error"],
                        }
                        records.append(record)
                        print(
                            chain, provider, width, density,
                            record["outcome"], returned, window["expected_events"],
                            f'{record["latency_ms"]:.1f}ms', flush=True,
                        )
                        time.sleep(0.15)
    return records


def summarize(records: list[dict]) -> dict:
    grouped: dict[tuple, list[dict]] = defaultdict(list)
    for row in records:
        grouped[(row["chain"], row["provider"], row["width"], row["density"])].append(row)
    cells = []
    for key, rows in sorted(grouped.items()):
        correct = [row for row in rows if row["outcome"] == "ok" and row["semantic_match"]]
        cells.append({
            "chain": key[0], "provider": key[1], "width": key[2], "density": key[3],
            "expected_events": rows[0]["expected_events"],
            "correct_runs": len(correct), "runs": len(rows),
            "median_latency_ms": statistics.median(row["latency_ms"] for row in correct) if correct else None,
            "median_response_bytes": statistics.median(row["response_bytes"] for row in correct) if correct else None,
        })

    sensitivity = []
    by_action: dict[tuple, list[dict]] = defaultdict(list)
    for cell in cells:
        by_action[(cell["chain"], cell["provider"], cell["width"])].append(cell)
    for key, values in sorted(by_action.items()):
        lookup = {value["density"]: value for value in values}
        low = lookup.get("low", {}).get("median_latency_ms")
        high = lookup.get("high", {}).get("median_latency_ms")
        ratio = high / low if low and high else None
        sensitivity.append({
            "chain": key[0], "provider": key[1], "width": key[2],
            "low_latency_ms": low, "high_latency_ms": high,
            "high_low_latency_ratio": ratio,
            "density_sensitive_15pct": ratio is not None and (ratio >= 1.15 or ratio <= 1 / 1.15),
        })
    return {"cells": cells, "sensitivity": sensitivity}


def main() -> None:
    records = run()
    with OUTPUT.open("w") as handle:
        for row in records:
            handle.write(json.dumps(row, sort_keys=True) + "\n")
    summary = summarize(records)
    SUMMARY.write_text(json.dumps(summary, indent=2, sort_keys=True) + "\n")
    print(f"Wrote {len(records)} records to {OUTPUT}")


def confirm() -> None:
    """Randomized confirmation on actions that were usable in the first pass."""
    grouped = load_messages()
    action_widths = {"arbitrum": (10000,), "optimism": (100, 1000, 10000), "polygon": (50, 100)}
    tasks = []
    for chain, widths in action_widths.items():
        rows = grouped[chain]
        mailbox = normalize_address(rows[0]["origin_mailbox"])
        for width in widths:
            windows = select_windows(rows, width)
            for density in ("low", "high"):
                for repeat in range(5):
                    tasks.append((chain, mailbox, width, density, repeat, windows[density]))
    random.Random(20260803).shuffle(tasks)
    records = []
    for chain, mailbox, width, density, repeat, window in tasks:
        query = {
            "fromBlock": hex(window["start"]), "toBlock": hex(window["end"]),
            "address": mailbox, "topics": [DISPATCH_TOPIC],
        }
        response = rpc(CHAINS[chain]["urls"]["drpc"], "eth_getLogs", [query], 20.0)
        result = response.get("result")
        returned = len(result) if isinstance(result, list) else None
        row = {
            "ts": time.time(), "chain": chain, "provider": "drpc", "width": width,
            "density": density, "repeat": repeat, "start": window["start"], "end": window["end"],
            "expected_events": window["expected_events"], "returned_events": returned,
            "semantic_match": returned == window["expected_events"], "outcome": response["outcome"],
            "latency_ms": response["latency_ms"], "response_bytes": response["response_bytes"],
            "error": response["error"],
        }
        records.append(row)
        print(chain, width, density, row["outcome"], returned, window["expected_events"], f'{row["latency_ms"]:.1f}ms', flush=True)
        time.sleep(0.25)
    path = DATA / "density_action_gate_confirm.jsonl"
    with path.open("w") as handle:
        for row in records:
            handle.write(json.dumps(row, sort_keys=True) + "\n")
    summary = summarize(records)
    (DATA / "density_action_gate_confirm_summary.json").write_text(
        json.dumps(summary, indent=2, sort_keys=True) + "\n"
    )
    print(f"Wrote {len(records)} randomized confirmation records to {path}")


if __name__ == "__main__":
    import sys
    confirm() if "--confirm" in sys.argv else main()
