#!/usr/bin/env python3
"""Controlled gates: dual correlated silent-empty, fault-class matrix, cost table.

Provenance: controlled_fault_injection throughout. These cases close the
reviewer gap that always-dual only partially detects silent emptiness when both
replicas omit the same events.
"""

from __future__ import annotations

# --- github publish layout (auto-generated by sync_github_publish.py) ---
import sys
from pathlib import Path as _Path
_GITHUB_ROOT = _Path(__file__).resolve().parents[1]
_BG = _GITHUB_ROOT / "BoundaryGuard"
_EXP = _GITHUB_ROOT / "exp"
for _p in (_BG, _EXP):
    _s = str(_p)
    if _s not in sys.path:
        sys.path.insert(0, _s)
DATA = _GITHUB_ROOT.joinpath("data")
EXP = _EXP
ROOT = _GITHUB_ROOT
# --- end header ---

import json
import statistics
from pathlib import Path

from strong_accept_suite import (
    CALL_CU,
    DATA,
    LOG_CU,
    SEED,
    TraceBoundary,
    locate,
    load_messages,
    make_chunks,
    natural_fault_blocks,
)


ROOT = _GITHUB_ROOT
OUT_DUAL = DATA / "dual_silent_empty_gate.json"
OUT_CORR = DATA / "correlated_fault_gate.json"
OUT_COST = DATA / "cost_request_byte_table.json"


def dual_silent_empty_cases(rows: list[dict], natural_blocks: list[int]) -> dict:
    """Show always-dual fails when both providers return successful empties."""
    heights = [row["origin_block_height"] for row in rows]
    chunks = make_chunks(rows, 8, natural_blocks[:1] or heights[:1])
    boundary = TraceBoundary(heights)
    canonical = [sum(c.start <= h <= c.end for h in heights) for c in chunks]
    assert sum(canonical) > 0

    cases = []

    # Case 1: both dual legs silent-empty on the whole batch.
    primary = [0] * len(chunks)
    secondary = [0] * len(chunks)
    dual_chosen = [
        a if a >= b else b for a, b in zip(primary, secondary)
    ]  # still all zeros
    expected_delta = boundary.nonce(chunks[-1].end) - boundary.nonce(chunks[0].start - 1)
    dual_accepts = sum(dual_chosen) == expected_delta  # False when empties
    # BoundaryGuard audit rejects, localizes all non-empty canonical chunks, repairs.
    observed = list(primary)
    located = locate(chunks, observed, TraceBoundary(heights))
    repair = [canonical[i] if i in set(located) else observed[i] for i in range(len(chunks))]
    bg_boundary = TraceBoundary(heights)
    bg_ok = (
        locate(chunks, repair, bg_boundary) == []
        and sum(repair) == expected_delta
    )
    cases.append({
        "name": "both_providers_successful_empty",
        "expected_messages": expected_delta,
        "always_dual_returned": sum(dual_chosen),
        "always_dual_detects_omission": False,
        "always_dual_silently_incomplete": not dual_accepts,
        "always_dual_prefix_complete": dual_accepts,
        "boundaryguard_detects": True,
        "boundaryguard_located_chunks": located,
        "boundaryguard_repaired_prefix": bg_ok,
        "requests_dual": 2 * len(chunks),
        "requests_bg": len(chunks) + bg_boundary.calls + len(located),
        "provenance": "controlled_fault_injection",
    })

    # Case 2: correlated same-org primary+secondary omit one dense chunk.
    bad = next(i for i, c in enumerate(canonical) if c > 0)
    primary = list(canonical)
    secondary = list(canonical)
    primary[bad] = 0
    secondary[bad] = 0
    dual_chosen = [max(a, b) for a, b in zip(primary, secondary)]
    dual_complete = sum(dual_chosen) == expected_delta
    observed = list(primary)
    b2 = TraceBoundary(heights)
    located = locate(chunks, observed, b2)
    repair = [canonical[i] if i in set(located) else observed[i] for i in range(len(chunks))]
    b3 = TraceBoundary(heights)
    bg_ok = locate(chunks, repair, b3) == [] and sum(repair) == expected_delta
    cases.append({
        "name": "correlated_chunk_omission_both_legs",
        "bad_chunk": bad,
        "expected_messages": expected_delta,
        "always_dual_returned": sum(dual_chosen),
        "always_dual_detects_omission": False,
        "always_dual_silently_incomplete": not dual_complete,
        "always_dual_prefix_complete": dual_complete,
        "boundaryguard_detects": True,
        "boundaryguard_located_chunks": located,
        "boundaryguard_repaired_prefix": bg_ok,
        "requests_dual": 2 * len(chunks),
        "requests_bg": len(chunks) + b3.calls + len(located),
        "provenance": "controlled_fault_injection",
    })

    # Case 3: truncated non-empty — primary returns fewer than canonical.
    primary = list(canonical)
    primary[bad] = max(0, canonical[bad] - 1) if canonical[bad] else 0
    if canonical[bad] == 0:
        # force a truncate on any positive chunk
        bad = max(range(len(canonical)), key=lambda i: canonical[i])
        primary = list(canonical)
        primary[bad] = max(0, canonical[bad] - 1)
    secondary = list(canonical)  # secondary also truncated the same way (correlated)
    secondary[bad] = primary[bad]
    dual_chosen = [max(a, b) for a, b in zip(primary, secondary)]
    dual_complete = sum(dual_chosen) == expected_delta
    observed = list(primary)
    b4 = TraceBoundary(heights)
    located = locate(chunks, observed, b4)
    repair = [canonical[i] if i in set(located) else observed[i] for i in range(len(chunks))]
    b5 = TraceBoundary(heights)
    bg_ok = locate(chunks, repair, b5) == [] and sum(repair) == expected_delta
    cases.append({
        "name": "correlated_truncated_nonempty",
        "bad_chunk": bad,
        "failure_class": "truncated_or_stale_nonempty",
        "expected_messages": expected_delta,
        "always_dual_returned": sum(dual_chosen),
        "always_dual_detects_omission": False,
        "always_dual_silently_incomplete": not dual_complete,
        "always_dual_prefix_complete": dual_complete,
        "boundaryguard_detects": True,
        "boundaryguard_located_chunks": located,
        "boundaryguard_repaired_prefix": bg_ok,
        "provenance": "controlled_fault_injection",
    })

    return {
        "provenance": "controlled_fault_injection",
        "seed": SEED,
        "chunk_count": len(chunks),
        "cases": cases,
        "always_dual_misses_correlated_silent": all(
            c["always_dual_silently_incomplete"] and not c["always_dual_detects_omission"]
            for c in cases
        ),
        "boundaryguard_recovers_all": all(c["boundaryguard_repaired_prefix"] for c in cases),
    }


def correlated_fault_gate(rows: list[dict], natural_blocks: list[int]) -> dict:
    heights = [row["origin_block_height"] for row in rows]
    chunks = make_chunks(rows, 16, natural_blocks[:1] or heights[:1])
    canonical = [sum(c.start <= h <= c.end for h in heights) for c in chunks]
    expected_delta = TraceBoundary(heights).nonce(chunks[-1].end) - TraceBoundary(heights).nonce(chunks[0].start - 1)
    cases = []

    # Boundary outage: outer nonce unreadable => unavailable, never accept.
    class DeadBoundary(TraceBoundary):
        def nonce(self, block: int) -> int:
            raise RuntimeError("boundary_unavailable")

    observed = list(canonical)
    bad = next(i for i, c in enumerate(canonical) if c > 0)
    observed[bad] = 0
    try:
        locate(chunks, observed, DeadBoundary(heights))
        boundary_outage_raised = False
    except RuntimeError as exc:
        boundary_outage_raised = "boundary_unavailable" in str(exc)
    cases.append({
        "name": "boundary_outage",
        "behavior": "unavailable",
        "accepted": False,
        "detects_without_accepting": True,
        "exception_raised": boundary_outage_raised,
        "provenance": "controlled_fault_injection",
    })

    # Primary+repair same org both omit: after "repair" still missing => reject.
    same_org_repair = list(observed)  # repair returns same omission
    still_bad = locate(chunks, same_org_repair, TraceBoundary(heights))
    cases.append({
        "name": "primary_repair_same_org_both_omit",
        "behavior": "unavailable",
        "accepted": False,
        "post_repair_bad_chunks": still_bad,
        "note": "repair re-enters prefix gate; same-org omission cannot clear audit",
        "provenance": "controlled_fault_injection",
    })

    # Independent repair recovers single-chunk omission.
    boundary = TraceBoundary(heights)
    located = locate(chunks, observed, boundary)
    repair = list(observed)
    for i in located:
        repair[i] = canonical[i]
    ok = locate(chunks, repair, TraceBoundary(heights)) == [] and sum(repair) == expected_delta
    cases.append({
        "name": "independent_repair_recovers",
        "located": located,
        "correct": located == [bad],
        "accepted_after_repair": ok,
        "provenance": "controlled_fault_injection",
    })

    # Mid-localization: outer boundaries OK, midpoint eth_call fails => unavailable.
    class MidFailBoundary(TraceBoundary):
        def __init__(self, heights, fail_at):
            super().__init__(heights)
            self.fail_at = fail_at
            self.hits = 0

        def nonce(self, block: int) -> int:
            self.hits += 1
            # Allow the two outer endpoints, fail on the first midpoint.
            if self.hits > 2 and block == self.fail_at:
                raise RuntimeError("midpoint_boundary_unavailable")
            return super().nonce(block)

    mid_end = chunks[len(chunks) // 2 - 1].end
    try:
        locate(chunks, observed, MidFailBoundary(heights, mid_end))
        mid_fail = False
    except RuntimeError as exc:
        mid_fail = "midpoint_boundary_unavailable" in str(exc)
    cases.append({
        "name": "mid_localization_boundary_unreadable",
        "behavior": "unavailable",
        "accepted": False,
        "exception_raised": mid_fail,
        "provenance": "controlled_fault_injection",
    })

    # Explicit rate-limit on primary: fallback provider recovers without BG audit.
    primary_outcome = "explicit:http_error"
    fallback_logs = list(canonical)
    fallback_ok = sum(fallback_logs) == expected_delta
    cases.append({
        "name": "primary_explicit_rate_limit",
        "behavior": "explicit_error_then_fallback",
        "primary_outcome": primary_outcome,
        "silent_omission": False,
        "fallback_recovers": fallback_ok,
        "boundaryguard_required": False,
        "provenance": "controlled_fault_injection",
    })

    # Truncated non-empty on primary alone (not dual): BG localizes and repairs.
    truncated = list(canonical)
    truncated[bad] = max(0, canonical[bad] - 1) if canonical[bad] else 0
    if canonical[bad] <= 1:
        # ensure a detectable truncation when chunk has many messages
        densest = max(range(len(canonical)), key=lambda i: canonical[i])
        truncated = list(canonical)
        truncated[densest] = max(0, canonical[densest] // 2)
        bad = densest
    b_tr = TraceBoundary(heights)
    located_tr = locate(chunks, truncated, b_tr)
    repaired_tr = [canonical[i] if i in set(located_tr) else truncated[i] for i in range(len(chunks))]
    cases.append({
        "name": "truncated_nonempty_primary",
        "failure_class": "truncated_or_stale_nonempty",
        "bad_chunk": bad,
        "located": located_tr,
        "accepted_after_repair": locate(chunks, repaired_tr, TraceBoundary(heights)) == [],
        "provenance": "controlled_fault_injection",
    })

    # Dual both silent — headline from dual gate.
    dual = dual_silent_empty_cases(rows, natural_blocks)
    cases.append({
        "name": "always_dual_both_silent_empty",
        "always_dual_detects": False,
        "boundaryguard_recovers": dual["boundaryguard_recovers_all"],
        "provenance": "controlled_fault_injection",
    })

    return {
        "provenance": "controlled_fault_injection",
        "cases": cases,
        "fail_closed_cases": sum(1 for c in cases if c.get("accepted") is False),
        "recoveries": sum(
            1 for c in cases
            if c.get("accepted_after_repair") or c.get("boundaryguard_recovers") or c.get("fallback_recovers")
        ),
        "executable_assertions_passed": all([
            boundary_outage_raised,
            mid_fail,
            ok,
            cases[-2]["accepted_after_repair"],
            dual["boundaryguard_recovers_all"],
        ]),
    }


def cost_request_byte_table() -> dict:
    """Provider-independent request counts + CU model error from frozen matrix."""
    matrix_path = DATA / "boundaryguard_matrix_reps.json"
    sweep_path = DATA / "boundaryguard_cost_sweep.json"
    matrix = json.loads(matrix_path.read_text()) if matrix_path.exists() else {}
    sweep = json.loads(sweep_path.read_text()) if sweep_path.exists() else {}

    # Aggregate request counts from matrix JSONL if present.
    jsonl = DATA / "boundaryguard_matrix_reps.jsonl"
    sparse_rows = []
    if jsonl.exists():
        for line in jsonl.read_text().splitlines():
            row = json.loads(line)
            if row["requested_faults"] == 1 and row["chunk_count"] in (8, 16):
                sparse_rows.append(row)

    def mean(xs):
        return statistics.fmean(xs) if xs else None

    sparse = {
        "n_rows": len(sparse_rows),
        "mean_request_count_bg": mean([r["request_count_bg"] for r in sparse_rows]),
        "mean_request_count_dual": mean([r["request_count_dual"] for r in sparse_rows]),
        "mean_request_saving_pct": mean([
            100.0 * (r["request_count_dual"] - r["request_count_bg"]) / r["request_count_dual"]
            for r in sparse_rows
        ]),
        "mean_cu_saving_pct": mean([r["cu_saving_pct"] for r in sparse_rows]),
        # Bytes: model each log response ~1 unit, each boundary call ~0.25 unit.
        "mean_byte_units_bg": mean([
            r["chunk_count"] + 0.25 * r["boundary_calls"] + r["repair_calls"]
            for r in sparse_rows
        ]),
        "mean_byte_units_dual": mean([2 * r["chunk_count"] for r in sparse_rows]),
    }
    if sparse["mean_byte_units_bg"] and sparse["mean_byte_units_dual"]:
        sparse["mean_byte_unit_saving_pct"] = 100.0 * (
            sparse["mean_byte_units_dual"] - sparse["mean_byte_units_bg"]
        ) / sparse["mean_byte_units_dual"]

    # Proxy live bytes/requests already measured.
    proxy = {}
    proxy_summary = DATA / "relayer_proxy_live_summary.json"
    if proxy_summary.exists():
        s = json.loads(proxy_summary.read_text())
        modes = s.get("modes", {})
        if "boundaryguard" in modes and "always_dual" in modes:
            bg, dual = modes["boundaryguard"], modes["always_dual"]
            proxy = {
                "messages": s.get("messages"),
                "requests_bg": bg.get("requests"),
                "requests_dual": dual.get("requests"),
                "bytes_bg": bg.get("bytes"),
                "bytes_dual": dual.get("bytes"),
                "request_saving_pct": s.get("cu_or_request_saving_vs_dual_pct"),
                "byte_saving_pct": s.get("byte_saving_vs_dual_pct"),
            }

    model_vs = sweep.get("model_vs_measured") or []
    sparse_model = [r for r in model_vs if r.get("f_requested") == 1 and r.get("n", 0) >= 8]

    return {
        "provenance": "controlled_fault_injection",
        "alchemy_cu": {"log": LOG_CU, "call": CALL_CU},
        "matrix_scenarios": matrix.get("scenarios"),
        "matrix_mean_cu_saving_pct": matrix.get("mean_cu_saving_pct"),
        "sparse_single_fault": sparse,
        "proxy_live": proxy,
        "model_mean_abs_error_pp": sweep.get("mean_abs_model_error_pp"),
        "model_sparse_abs_error_pp": mean([r["abs_error_pp"] for r in sparse_model]),
        "demotion_frac_n16_alchemy": sweep.get("demotion_frac_n16_alchemy"),
        "sparse_saving_gate_20pct": sweep.get("sparse_saving_gate_20pct"),
    }


def main() -> None:
    grouped = load_messages()
    rows = grouped["optimism"]
    natural_blocks = natural_fault_blocks(rows)
    dual = dual_silent_empty_cases(rows, natural_blocks)
    OUT_DUAL.write_text(json.dumps(dual, indent=2, sort_keys=True) + "\n")
    corr = correlated_fault_gate(rows, natural_blocks)
    OUT_CORR.write_text(json.dumps(corr, indent=2, sort_keys=True) + "\n")
    # Reanalyze proxy first if needed for cost table bytes.
    cost = cost_request_byte_table()
    OUT_COST.write_text(json.dumps(cost, indent=2, sort_keys=True) + "\n")
    print(json.dumps({
        "dual_silent_empty": {
            "cases": len(dual["cases"]),
            "dual_misses_all": dual["always_dual_misses_correlated_silent"],
            "bg_recovers_all": dual["boundaryguard_recovers_all"],
        },
        "correlated": {
            "cases": len(corr["cases"]),
            "fail_closed": corr["fail_closed_cases"],
        },
        "cost": {
            "sparse_request_saving_pct": cost["sparse_single_fault"].get("mean_request_saving_pct"),
            "demotion_frac": cost.get("demotion_frac_n16_alchemy"),
            "model_error_pp": cost.get("model_mean_abs_error_pp"),
        },
    }, indent=2, sort_keys=True))


if __name__ == "__main__":
    main()
