#!/usr/bin/env python3
"""Fetch recent Hyperlane cross-chain messages from the public Explorer API."""

from __future__ import annotations

# --- github publish layout (auto-generated by sync_github_publish.py) ---
import sys
from pathlib import Path as _Path
_GITHUB_ROOT = _Path(__file__).resolve().parents[1]
_BG = _GITHUB_ROOT / "BoundaryGuard"
_EXP = _GITHUB_ROOT / "exp"
for _p in (_BG, _EXP):
    _s = str(_p)
    if _s not in sys.path:
        sys.path.insert(0, _s)
DATA = _GITHUB_ROOT.joinpath("data")
EXP = _EXP
ROOT = _GITHUB_ROOT
# --- end header ---

import argparse
import json
import time
import urllib.error
import urllib.request
from pathlib import Path


API = "https://explorer4.hasura.app/v1/graphql"
CHAINS = {1: "ethereum", 10: "optimism", 137: "polygon", 42161: "arbitrum"}
FIELDS = """
msg_id nonce origin_chain_id origin_domain_id origin_mailbox
origin_block_height origin_block_hash origin_tx_hash destination_chain_id
send_occurred_at is_delivered delivery_occurred_at delivery_latency
"""


def query(document: str, timeout: float = 20.0) -> list[dict]:
    body = json.dumps({"query": document}).encode()
    req = urllib.request.Request(
        API,
        data=body,
        headers={"content-type": "application/json", "user-agent": "BoundaryGuard/0.2"},
        method="POST",
    )
    with urllib.request.urlopen(req, timeout=timeout) as response:
        payload = json.load(response)
    if payload.get("errors"):
        raise RuntimeError(json.dumps(payload["errors"], sort_keys=True))
    return payload["data"]["message_view"]


def latest_message(chain_id: int) -> dict:
    return query(
        f"""
        query Latest {{
          message_view(limit: 1, order_by: {{nonce: desc}},
            where: {{origin_chain_id: {{_eq: {chain_id}}}}}) {{ {FIELDS} }}
        }}
        """
    )[0]


def fetch_chain(chain_id: int, count: int, page: int, delay: float) -> list[dict]:
    latest = latest_message(chain_id)
    mailbox = latest["origin_mailbox"]
    hi = int(latest["nonce"])
    lo = max(0, hi - count + 1)
    rows: list[dict] = []
    cursor = lo
    while cursor <= hi:
        page_hi = min(hi, cursor + page - 1)
        # The nonce range keeps each Hasura request below its five-second cap.
        document = f"""
        query Page {{
          message_view(limit: {page}, order_by: {{nonce: asc}}, where: {{_and: [
            {{origin_chain_id: {{_eq: {chain_id}}}}},
            {{nonce: {{_gte: {cursor}}}}},
            {{nonce: {{_lte: {page_hi}}}}}
          ]}}) {{ {FIELDS} }}
        }}
        """
        for attempt in range(4):
            try:
                batch = query(document)
                break
            except (urllib.error.URLError, TimeoutError, RuntimeError) as exc:
                if attempt == 3:
                    raise
                time.sleep(1.0 * (attempt + 1))
        # A chain can contain retired Mailbox deployments with overlapping
        # nonces.  Keep the deployment associated with the latest message.
        rows.extend(row for row in batch if row["origin_mailbox"] == mailbox)
        print(
            f"{CHAINS[chain_id]:9s} nonce {cursor}-{page_hi}: "
            f"{len(batch)} rows ({len(rows)} retained)",
            flush=True,
        )
        cursor = page_hi + 1
        time.sleep(delay)
    rows.sort(key=lambda row: row["nonce"])
    return rows


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--count", type=int, default=2000)
    parser.add_argument("--page", type=int, default=250)
    parser.add_argument("--delay", type=float, default=0.15)
    parser.add_argument("--output", type=Path, default=Path("data/hyperlane_messages.jsonl"))
    args = parser.parse_args()
    args.output.parent.mkdir(parents=True, exist_ok=True)
    all_rows: list[dict] = []
    for chain_id in CHAINS:
        rows = fetch_chain(chain_id, args.count, args.page, args.delay)
        for row in rows:
            row["chain"] = CHAINS[chain_id]
        all_rows.extend(rows)
    with args.output.open("w", encoding="utf-8") as handle:
        for row in sorted(all_rows, key=lambda item: (item["send_occurred_at"], item["chain"])):
            handle.write(json.dumps(row, sort_keys=True) + "\n")
    print(f"Wrote {len(all_rows)} messages to {args.output}")


if __name__ == "__main__":
    main()
