#!/usr/bin/env python3
"""Freeze independent protocol-state ground truth for every S4 query block.

The original paired-baseline run evaluated only the subset for which its
single evaluation endpoint happened to answer both historical nonce calls.
This script does not rewrite those raw samples.  It independently obtains
Mailbox.nonce() at h-1 and h from at least two archive-provider organizations,
requires agreement, and writes an immutable block->expected-count map plus a
reanalysis summary covering every saved S4 response.

The freeze is post-hoc with respect to the original S4 request execution and is
therefore labelled as such in both artifacts and the paper.
"""

from __future__ import annotations

# --- github publish layout (auto-generated by sync_github_publish.py) ---
import sys
from pathlib import Path as _Path
_GITHUB_ROOT = _Path(__file__).resolve().parents[1]
_BG = _GITHUB_ROOT / "BoundaryGuard"
_EXP = _GITHUB_ROOT / "exp"
for _p in (_BG, _EXP):
    _s = str(_p)
    if _s not in sys.path:
        sys.path.insert(0, _s)
DATA = _GITHUB_ROOT.joinpath("data")
EXP = _EXP
ROOT = _GITHUB_ROOT
# --- end header ---

import argparse
import json
import statistics
import threading
import time
from collections import defaultdict
from concurrent.futures import ThreadPoolExecutor, as_completed
from datetime import datetime, timezone
from pathlib import Path

from rpc_probe import rpc
from hyperlane_identity import normalize


ROOT = _GITHUB_ROOT
DATA = DATA / "strong_e2e"
SAMPLES = DATA / "s4_paired_samples.jsonl"
MESSAGES = DATA / "hyperlane_messages.jsonl"
OUT = DATA / "s4_ground_truth.jsonl"
SUMMARY = DATA / "s4_ground_truth_summary.json"
NONCE_SELECTOR = "0xaffed0e0"

# Different provider organizations.  The first three currently expose the
# required Optimism historical state; failures remain visible in evidence.
PROVIDERS = [
    ("drpc", "https://optimism.drpc.org"),
    ("tenderly", "https://optimism.gateway.tenderly.co"),
    ("publicnode", "https://optimism-rpc.publicnode.com"),
]


def load_jsonl(path: Path) -> list[dict]:
    return [json.loads(line) for line in path.read_text().splitlines() if line.strip()]


def mailbox_for_blocks(blocks: set[int]) -> str:
    mailboxes = {
        normalize(str(row["origin_mailbox"]))
        for row in load_jsonl(MESSAGES)
        if row.get("chain") == "optimism"
        and int(row["origin_block_height"]) in blocks
    }
    mailboxes.discard(None)
    if len(mailboxes) != 1:
        raise SystemExit(f"expected one Optimism Mailbox, found {sorted(mailboxes)}")
    return next(iter(mailboxes))


def nonce_pair(name: str, url: str, mailbox: str, block: int, timeout: float) -> dict:
    started = time.perf_counter()
    values = []
    for height in (block - 1, block):
        response = rpc(
            url,
            "eth_call",
            [{"to": mailbox, "data": NONCE_SELECTOR}, hex(height)],
            timeout,
        )
        if response.get("outcome") != "ok" or not isinstance(response.get("result"), str):
            return {
                "provider": name,
                "ok": False,
                "error": str(response.get("error") or response.get("outcome"))[:240],
                "latency_ms": (time.perf_counter() - started) * 1000,
            }
        values.append(int(response["result"], 16))
    return {
        "provider": name,
        "ok": True,
        "nonce_before": values[0],
        "nonce_after": values[1],
        "expected": values[1] - values[0],
        "latency_ms": (time.perf_counter() - started) * 1000,
    }


def freeze_one(mailbox: str, block: int, timeout: float, retries: int) -> dict:
    evidence: list[dict] = []
    for attempt in range(retries + 1):
        with ThreadPoolExecutor(max_workers=len(PROVIDERS)) as pool:
            futures = [
                pool.submit(nonce_pair, name, url, mailbox, block, timeout)
                for name, url in PROVIDERS
            ]
            evidence.extend(f.result() for f in futures)
        groups: dict[tuple[int, int], set[str]] = defaultdict(set)
        for item in evidence:
            if item.get("ok"):
                groups[(item["nonce_before"], item["nonce_after"])].add(item["provider"])
        if groups:
            pair, agreeing = max(groups.items(), key=lambda item: len(item[1]))
            if len(agreeing) >= 2:
                return {
                    "block": block,
                    "mailbox": mailbox,
                    "nonce_before": pair[0],
                    "nonce_after": pair[1],
                    "expected": pair[1] - pair[0],
                    "agreeing_providers": sorted(agreeing),
                    "agreement_count": len(agreeing),
                    "verified": True,
                    "evidence": evidence,
                    "provenance": "live_independent_posthoc_ground_truth_freeze",
                }
        if attempt < retries:
            time.sleep(0.5 * (2**attempt))
    return {
        "block": block,
        "mailbox": mailbox,
        "verified": False,
        "evidence": evidence,
        "provenance": "live_independent_posthoc_ground_truth_freeze",
    }


def pctile(values: list[float], p: float) -> float | None:
    if not values:
        return None
    ordered = sorted(values)
    return ordered[min(len(ordered) - 1, int(p * (len(ordered) - 1)))]


def reanalyze(samples: list[dict], truth: list[dict]) -> dict:
    by_block = {int(row["block"]): row for row in truth if row.get("verified")}
    by_mode_rep: dict[tuple[str, int], list[dict]] = defaultdict(list)
    for row in samples:
        expected = by_block.get(int(row["block"]), {}).get("expected")
        item = dict(row)
        item["frozen_expected"] = expected
        item["frozen_count_complete"] = (
            expected is not None
            and bool(row.get("completed"))
            and int(row.get("returned") or 0) == int(expected)
        )
        by_mode_rep[(row["mode"], int(row["rep"]))].append(item)

    modes: dict[str, dict] = {}
    for mode in sorted({key[0] for key in by_mode_rep}):
        reps = []
        for rep in sorted(key[1] for key in by_mode_rep if key[0] == mode):
            rows = by_mode_rep[(mode, rep)]
            auditable = [r for r in rows if r["frozen_expected"] is not None]
            reps.append({
                "rep": rep,
                "issued": len(rows),
                "auditable": len(auditable),
                "count_complete": sum(bool(r["frozen_count_complete"]) for r in auditable),
                "count_incomplete": sum(not bool(r["frozen_count_complete"]) for r in auditable),
            })
        modes[mode] = {
            "reps": reps,
            "mean_issued": statistics.fmean(r["issued"] for r in reps),
            "mean_auditable": statistics.fmean(r["auditable"] for r in reps),
            "mean_count_complete": statistics.fmean(r["count_complete"] for r in reps),
            "all_responses_auditable": all(r["auditable"] == r["issued"] for r in reps),
        }
    return modes


def consistency_checks(samples: list[dict], truth: list[dict]) -> dict:
    """Require the new oracle to agree with every successful old oracle read."""
    by_block = {int(row["block"]): int(row["expected"]) for row in truth if row.get("verified")}
    comparable = [row for row in samples if row.get("expected") is not None]
    mismatches = [
        {
            "block": int(row["block"]),
            "mode": row["mode"],
            "rep": int(row["rep"]),
            "saved_expected": int(row["expected"]),
            "frozen_expected": by_block.get(int(row["block"])),
        }
        for row in comparable
        if by_block.get(int(row["block"])) != int(row["expected"])
    ]
    return {
        "saved_oracle_values_checked": len(comparable),
        "saved_vs_frozen_mismatches": len(mismatches),
        "mismatch_examples": mismatches[:10],
        "pass": not mismatches,
    }


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--workers", type=int, default=8)
    parser.add_argument("--timeout", type=float, default=15.0)
    parser.add_argument("--retries", type=int, default=1)
    parser.add_argument(
        "--resume",
        action="store_true",
        help="reuse verified rows in the existing output and retry only gaps",
    )
    args = parser.parse_args()

    samples = load_jsonl(SAMPLES)
    blocks = {int(row["block"]) for row in samples}
    mailbox = mailbox_for_blocks(blocks)
    print(f"freezing {len(blocks)} unique blocks for {mailbox}", flush=True)
    existing: dict[int, dict] = {}
    if args.resume and OUT.exists():
        existing = {
            int(row["block"]): row
            for row in load_jsonl(OUT)
            if row.get("verified") and int(row["block"]) in blocks
        }
        print(f"resume: keeping {len(existing)} verified blocks", flush=True)
    pending = sorted(blocks - set(existing))
    rows: list[dict] = list(existing.values())
    lock = threading.Lock()
    done = 0
    with ThreadPoolExecutor(max_workers=args.workers) as pool:
        futures = {
            pool.submit(freeze_one, mailbox, block, args.timeout, args.retries): block
            for block in pending
        }
        for future in as_completed(futures):
            row = future.result()
            rows.append(row)
            with lock:
                done += 1
                if done % 50 == 0 or done == len(pending):
                    ok = sum(bool(r.get("verified")) for r in rows)
                    print(f"ground truth retry {done}/{len(pending)} total_verified={ok}", flush=True)

    rows.sort(key=lambda row: int(row["block"]))
    frozen_at = datetime.now(timezone.utc).isoformat()
    with OUT.open("w") as handle:
        for row in rows:
            row["frozen_at"] = frozen_at
            handle.write(json.dumps(row, sort_keys=True) + "\n")

    verified = [row for row in rows if row.get("verified")]
    consistency = consistency_checks(samples, rows)
    summary = {
        "gate": "S4_independent_ground_truth",
        "frozen_at": frozen_at,
        "provenance": "live_independent_posthoc_ground_truth_freeze",
        "note": (
            "Frozen after the original S4 request execution, before this reanalysis; "
            "raw S4 samples are unchanged. Each verified block requires matching "
            "historical Mailbox.nonce() pairs from two provider organizations."
        ),
        "query_blocks": len(rows),
        "verified_blocks": len(verified),
        "coverage_pct": 100.0 * len(verified) / len(rows) if rows else 0.0,
        "provider_organizations": [name for name, _ in PROVIDERS],
        "min_agreement": min((row["agreement_count"] for row in verified), default=0),
        "modes": reanalyze(samples, rows),
        "consistency": consistency,
        "artifact": str(OUT.relative_to(ROOT)),
    }
    SUMMARY.write_text(json.dumps(summary, indent=2, sort_keys=True) + "\n")
    print(json.dumps(summary, indent=2, sort_keys=True), flush=True)
    complete = len(verified) == len(rows) and consistency["pass"]
    raise SystemExit(0 if complete else 2)


if __name__ == "__main__":
    main()
