#!/usr/bin/env python3
"""Gate 6: multi-pair, multi-epoch verified capability frontier baselines."""

from __future__ import annotations

# --- github publish layout (auto-generated by sync_github_publish.py) ---
import sys
from pathlib import Path as _Path
_GITHUB_ROOT = _Path(__file__).resolve().parents[1]
_BG = _GITHUB_ROOT / "BoundaryGuard"
_EXP = _GITHUB_ROOT / "exp"
for _p in (_BG, _EXP):
    _s = str(_p)
    if _s not in sys.path:
        sys.path.insert(0, _s)
DATA = _GITHUB_ROOT.joinpath("data")
EXP = _EXP
ROOT = _GITHUB_ROOT
# --- end header ---

import argparse
import json
import time
from collections import defaultdict
from pathlib import Path

from audit_hyperlane_ground_truth import rpc
from hyperlane_identity import DISPATCH_TOPIC, normalize, verify_dispatch


ROOT = _GITHUB_ROOT
MESSAGES = DATA / "hyperlane_messages.jsonl"
PROBE = DATA / "provider_frontier_multiday_probe.jsonl"
EVAL = DATA / "provider_frontier_multiday_eval.json"

PAIRS = {
    "ethereum": {
        "flashbots": "https://rpc.flashbots.net",
        "zeroxrpc": "https://0xrpc.io/eth",
        "publicnode": "https://ethereum-rpc.publicnode.com",
    },
    "optimism": {
        "1rpc": "https://public.1rpc.io/op",
        "official": "https://mainnet.optimism.io",
        "drpc": "https://optimism.drpc.org",
    },
}


def samples(chain: str, count: int = 24) -> list[dict]:
    rows = []
    with MESSAGES.open() as handle:
        for line in handle:
            row = json.loads(line)
            if row["chain"] == chain:
                rows.append(row)
    rows.sort(key=lambda r: r["origin_block_height"])
    if len(rows) < count:
        return rows
    return [rows[round(i * (len(rows) - 1) / (count - 1))] for i in range(count)]


def semantics(logs: object, expected: dict) -> bool:
    return isinstance(logs, list) and any(
        isinstance(log, dict) and verify_dispatch(log, expected)["valid"] for log in logs
    )


def next_epoch(existing: list[dict]) -> int:
    if not existing:
        return 0
    return 1 + max(int(row.get("epoch", 0)) for row in existing)


def probe(epoch: int, per_chain: int, timeout: float, delay: float) -> None:
    existing = [json.loads(line) for line in PROBE.read_text().splitlines()] if PROBE.exists() else []
    done = {(row["epoch"], row["chain"], row["nonce"], row["provider"], row["method"]) for row in existing}
    with PROBE.open("a") as handle:
        for chain, providers in PAIRS.items():
            for message in samples(chain, per_chain):
                block = message["origin_block_height"]
                block_hash = normalize(message["origin_block_hash"])
                mailbox = normalize(message["origin_mailbox"])
                methods = {
                    "blockHash": [{"blockHash": block_hash, "address": mailbox, "topics": [DISPATCH_TOPIC]}],
                    "singleBlock": [{"fromBlock": hex(block), "toBlock": hex(block), "address": mailbox,
                                     "topics": [DISPATCH_TOPIC]}],
                }
                for provider, url in providers.items():
                    for method, params in methods.items():
                        key = (epoch, chain, message["nonce"], provider, method)
                        if key in done:
                            continue
                        response = rpc(url, "eth_getLogs", params, timeout)
                        logs = response.pop("result", None)
                        valid = response["outcome"] == "ok" and semantics(logs, message)
                        record = {
                            "provenance": "live_natural_observation",
                            "observed_at": time.time(),
                            "epoch": epoch,
                            "chain": chain,
                            "nonce": message["nonce"],
                            "block": block,
                            "provider": provider,
                            "method": method,
                            "outcome": response["outcome"],
                            "latency_ms": response.get("latency_ms"),
                            "semantic_match": valid,
                            "result_count": len(logs) if isinstance(logs, list) else None,
                            "error": response.get("error"),
                        }
                        handle.write(json.dumps(record, sort_keys=True) + "\n")
                        handle.flush()
                        print(epoch, chain, provider, method, valid, response["outcome"], flush=True)
                        time.sleep(delay)


def frontier_for(profile: list[tuple[int, bool]]) -> int | None:
    """Oldest block at/after which all newer samples are semantically complete."""
    profile = sorted(profile, key=lambda x: x[0])
    # Find first index where suffix is all True and prefix has a False, or all True => min block
    if not profile:
        return None
    if all(ok for _, ok in profile):
        return profile[0][0]
    if not any(ok for _, ok in profile):
        return None
    # last False then next True
    last_false = max((block for block, ok in profile if not ok), default=None)
    if last_false is None:
        return profile[0][0]
    newer = [block for block, ok in profile if block > last_false and ok]
    return min(newer) if newer else None


def epoch_health(rows: list[dict], epoch: int) -> dict:
    """An epoch is healthy if ethereum:blockHash has at least one semantic hit."""
    eth_bh = [
        row for row in rows
        if int(row["epoch"]) == epoch
        and row.get("chain") == "ethereum"
        and row.get("method") == "blockHash"
    ]
    semantic_ok = sum(
        1 for row in eth_bh
        if row.get("semantic_match") and row.get("outcome") == "ok"
    )
    return {
        "epoch": epoch,
        "eth_blockhash_rows": len(eth_bh),
        "eth_blockhash_semantic_ok": semantic_ok,
        "healthy": semantic_ok > 0,
    }


def evaluate(prefer_epochs: list[int] | None = None) -> dict:
    rows = [json.loads(line) for line in PROBE.read_text().splitlines()] if PROBE.exists() else []
    epochs = sorted({int(row["epoch"]) for row in rows})
    health = [epoch_health(rows, ep) for ep in epochs]
    healthy = [h["epoch"] for h in health if h["healthy"]]
    # Prefer an explicit freeze list, else latest healthy epoch (skip collapsed probes).
    if prefer_epochs:
        use = [ep for ep in prefer_epochs if ep in epochs]
        latest = use[-1] if use else (healthy[-1] if healthy else (epochs[-1] if epochs else 0))
        eval_epochs = use or ([latest] if epochs else [])
    else:
        latest = healthy[-1] if healthy else (epochs[-1] if epochs else 0)
        eval_epochs = healthy if healthy else epochs
    # Include non-ok outcomes so failed eth_getLogs count as undelivered rather
    # than shrinking the nonce intersection to the luckiest provider.
    latest_rows = [row for row in rows if int(row["epoch"]) == latest]
    results = {
        "epochs": eval_epochs,
        "all_epochs_observed": epochs,
        "latest_epoch": latest,
        "epoch_health": health,
        "collapsed_epochs_excluded_from_headline": [
            h["epoch"] for h in health if not h["healthy"]
        ],
        "pairs": {},
        "baselines": {},
    }
    sla_thresholds = [800, 1000, 1300, 1600, 2000]

    for chain, providers in PAIRS.items():
        for method in ("blockHash", "singleBlock"):
            key = f"{chain}:{method}"
            by_provider = defaultdict(list)
            for row in latest_rows:
                if row["chain"] == chain and row["method"] == method:
                    by_provider[row["provider"]].append(row)
            frontiers = {}
            for provider, prow in by_provider.items():
                profile = [
                    (int(r["block"]), bool(r.get("semantic_match") and r.get("outcome") == "ok"))
                    for r in prow
                ]
                frontiers[provider] = frontier_for(profile)
            results["pairs"][key] = {
                "providers": sorted(by_provider),
                "frontiers": frontiers,
                "samples": {p: len(v) for p, v in by_provider.items()},
                "semantic_ok": {
                    p: sum(1 for r in v if r.get("semantic_match") and r.get("outcome") == "ok")
                    for p, v in by_provider.items()
                },
            }

            # Align on nonces attempted by every provider (including explicit failures).
            nonces = None
            for prow in by_provider.values():
                nset = {r["nonce"] for r in prow}
                nonces = nset if nonces is None else (nonces & nset)
            if not nonces:
                continue
            nonces = sorted(nonces)
            table = {}
            for provider, prow in by_provider.items():
                table[provider] = {r["nonce"]: r for r in prow}

            def delivered(row: dict) -> bool:
                return bool(row.get("outcome") == "ok" and row.get("semantic_match"))

            reliable = max(
                by_provider,
                key=lambda p: sum(1 for r in by_provider[p] if delivered(r)),
            )
            # latency-only static: lowest mean latency among providers with >0 success
            latency_static = min(
                by_provider,
                key=lambda p: (
                    0 if any(delivered(r) for r in by_provider[p]) else 1,
                    sum(r.get("latency_ms") or 0 for r in by_provider[p] if delivered(r))
                    / max(sum(1 for r in by_provider[p] if delivered(r)), 1),
                ),
            )
            provider_cycle = sorted(by_provider)
            policies = {
                "reliable_static": [],
                "latency_static": [],
                "round_robin": [],
                "verified_frontier": [],
                "offline_oracle": [],
            }
            # Precompute mean success latency per provider (policy input only).
            # Do NOT use per-sample latency or per-sample delivery when choosing.
            mean_lat = {}
            for p in provider_cycle:
                lats = [
                    r.get("latency_ms")
                    for r in by_provider[p]
                    if delivered(r) and r.get("latency_ms") is not None
                ]
                mean_lat[p] = (sum(lats) / len(lats)) if lats else 1e9

            for idx, nonce in enumerate(nonces):
                # offline oracle: hindsight best successful provider (benchmark only)
                candidates = [
                    (table[p][nonce].get("latency_ms") or 1e9, p)
                    for p in provider_cycle
                    if delivered(table[p][nonce])
                ]
                oracle_p = min(candidates)[1] if candidates else reliable
                rr_p = provider_cycle[idx % len(provider_cycle)]
                block = int(table[reliable][nonce]["block"])
                # Verified frontier: among providers whose precomputed frontier
                # covers this block, pick lowest mean historical latency.
                # Never condition on this sample's ok/latency (no hindsight).
                eligible = []
                for p in provider_cycle:
                    fr = frontiers.get(p)
                    if fr is not None and block >= fr:
                        eligible.append(p)
                if eligible:
                    frontier_choice = min(eligible, key=lambda p: (mean_lat[p], p))
                else:
                    frontier_choice = reliable
                choices = {
                    "reliable_static": reliable,
                    "latency_static": latency_static,
                    "round_robin": rr_p,
                    "verified_frontier": frontier_choice,
                    "offline_oracle": oracle_p,
                }
                for name, prov in choices.items():
                    row = table[prov][nonce]
                    policies[name].append({
                        "nonce": nonce,
                        "provider": prov,
                        "delivered": delivered(row),
                        "latency_ms": row.get("latency_ms"),
                    })

            def metrics(items: list[dict]) -> dict:
                delivered_items = [x for x in items if x["delivered"]]
                lats = sorted(x["latency_ms"] for x in delivered_items if x["latency_ms"] is not None)
                out = {
                    "delivery_rate": len(delivered_items) / len(items) if items else 0.0,
                    "mean_success_latency_ms": (sum(lats) / len(lats)) if lats else None,
                    "p95_success_latency_ms": lats[min(len(lats) - 1, int(round(0.95 * (len(lats) - 1))))] if lats else None,
                    "n": len(items),
                    "sla": {},
                }
                for thr in sla_thresholds:
                    out["sla"][str(thr)] = (
                        sum(1 for x in delivered_items if (x["latency_ms"] or 1e9) <= thr) / len(items)
                        if items else 0.0
                    )
                return out

            results["baselines"][key] = {
                "reliable_provider": reliable,
                "latency_provider": latency_static,
                "frontiers": frontiers,
                "policies": {name: metrics(items) for name, items in policies.items()},
            }
    # Stability across observed epochs for ethereum flashbots frontier
    stability = []
    for epoch in epochs:
        eth = [
            row for row in rows
            if int(row["epoch"]) == epoch and row["chain"] == "ethereum"
            and row["provider"] == "flashbots" and row["method"] == "blockHash" and row["outcome"] == "ok"
        ]
        fr = frontier_for([(int(r["block"]), bool(r["semantic_match"])) for r in eth])
        stability.append({"epoch": epoch, "flashbots_frontier": fr, "samples": len(eth)})
    results["frontier_stability"] = stability
    results["provenance"] = "live_natural_observation"
    return results


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--per-chain", type=int, default=24)
    parser.add_argument("--timeout", type=float, default=12.0)
    parser.add_argument("--delay", type=float, default=0.04)
    parser.add_argument("--eval-only", action="store_true")
    parser.add_argument(
        "--freeze-epochs",
        default=None,
        help="Comma-separated epochs to keep as canonical headline (e.g. 0,1)",
    )
    parser.add_argument(
        "--write-freeze",
        action="store_true",
        help="Also write provider_frontier_multiday_eval.frozen.json",
    )
    args = parser.parse_args()
    if not args.eval_only:
        existing = [json.loads(line) for line in PROBE.read_text().splitlines()] if PROBE.exists() else []
        epoch = next_epoch(existing)
        probe(epoch, args.per_chain, args.timeout, args.delay)
    prefer = None
    if args.freeze_epochs:
        prefer = [int(x.strip()) for x in args.freeze_epochs.split(",") if x.strip()]
    results = evaluate(prefer_epochs=prefer)
    EVAL.write_text(json.dumps(results, indent=2, sort_keys=True) + "\n")
    if args.write_freeze:
        frozen = DATA / "provider_frontier_multiday_eval.frozen.json"
        frozen.write_text(json.dumps(results, indent=2, sort_keys=True) + "\n")
    print(json.dumps({
        "epochs": results["epochs"],
        "latest_epoch": results["latest_epoch"],
        "epoch_health": results.get("epoch_health"),
        "collapsed_epochs_excluded_from_headline": results.get(
            "collapsed_epochs_excluded_from_headline"
        ),
        "pairs": list(results["pairs"]),
        "baseline_keys": list(results["baselines"]),
        "frontier_stability": results["frontier_stability"],
        "sample_baseline": next(iter(results["baselines"].values()), None),
    }, indent=2, sort_keys=True))


if __name__ == "__main__":
    main()
