#!/usr/bin/env python3
"""Zero-cost Gate3/A4 dry-run checklist (no destination txs required).

Checks configuration, RPC health, signer wiring, and whether a funded mainnet
run is likely to produce Mailbox.process evidence — without spending gas.

Exit codes:
  0 = all blocking checks passed (funded run may still need IGP/self-dispatch)
  1 = one or more blocking failures
  2 = checklist could not run (missing deps/files)
"""

from __future__ import annotations

# --- github publish layout (auto-generated by sync_github_publish.py) ---
import sys
from pathlib import Path as _Path
_GITHUB_ROOT = _Path(__file__).resolve().parents[1]
_BG = _GITHUB_ROOT / "BoundaryGuard"
_EXP = _GITHUB_ROOT / "exp"
for _p in (_BG, _EXP):
    _s = str(_p)
    if _s not in sys.path:
        sys.path.insert(0, _s)
DATA = _GITHUB_ROOT.joinpath("data")
EXP = _EXP
ROOT = _GITHUB_ROOT
# --- end header ---

import json
import os
import re
import subprocess
import sys
import urllib.request
from dataclasses import dataclass, asdict
from datetime import datetime, timezone
from pathlib import Path


ROOT = _GITHUB_ROOT
WORK = ROOT / "work"
DATA = WORK / "data"
LOGS = WORK / "logs"
OUT = DATA / "gate3_dryrun_checklist.json"

OP_MAILBOX = "0xd4c1905bb1d26bc93dac913e13cacc278cdcc80d"
NONCE_SELECTOR = "0xaffed0e0"


@dataclass
class Check:
    id: str
    title: str
    severity: str  # blocker | warn | info
    ok: bool
    detail: str


def rpc(url: str, method: str, params: list, timeout: float = 15.0) -> dict:
    payload = json.dumps({"jsonrpc": "2.0", "id": 1, "method": method, "params": params}).encode()
    req = urllib.request.Request(url, data=payload, headers={"content-type": "application/json"})
    try:
        with urllib.request.urlopen(req, timeout=timeout) as resp:
            body = json.loads(resp.read())
            if "error" in body:
                return {"ok": False, "error": body["error"], "result": None}
            return {"ok": True, "error": None, "result": body.get("result")}
    except Exception as exc:
        return {"ok": False, "error": f"{type(exc).__name__}:{exc}", "result": None}


def load_key() -> tuple[str | None, str]:
    env = os.environ.get("HYP_DEFAULTSIGNER_KEY", "").strip()
    if env:
        return env, "env:HYP_DEFAULTSIGNER_KEY"
    for rel, label in (
        (WORK / ".env", "work/.env"),
        (WORK / "configs" / "gate3_funded.key", "gate3_funded.key"),
        (WORK / "configs" / "gate3_ephemeral.key", "gate3_ephemeral.key"),
    ):
        if not rel.exists():
            continue
        text = rel.read_text().strip()
        if rel.name == ".env":
            for line in text.splitlines():
                line = line.strip()
                if not line or line.startswith("#") or "=" not in line:
                    continue
                k, v = line.split("=", 1)
                if "PK" in k.upper() or "KEY" in k.upper() or "SIGNER" in k.upper():
                    return v.strip().strip('"').strip("'"), f"{label}:{k}"
        else:
            return text, label
    return None, "none"


def derive_address(key: str) -> str | None:
    try:
        from eth_account import Account
    except ImportError:
        return None
    raw = key.strip()
    if not raw.startswith("0x"):
        raw = "0x" + raw
    return Account.from_key(raw).address


def balance(url: str, addr: str) -> tuple[bool, int | None, str]:
    res = rpc(url, "eth_getBalance", [addr, "latest"])
    if not res["ok"]:
        return False, None, str(res["error"])
    try:
        return True, int(res["result"], 16), "ok"
    except Exception as exc:
        return False, None, str(exc)


def parse_relayer_log(path: Path) -> dict:
    if not path.exists():
        return {"exists": False}
    text = path.read_text(errors="ignore")
    patterns = {
        "no_signer": r"No signer found in provider",
        "missing_config": r"MissingConfiguration",
        "archive_token": r"Archive requests require a personal token",
        "process_attempt": r"Mailbox\.process|process_message|Submitting transaction|submit.*process",
        "delivered": r"delivered|Delivery|Message delivered",
        "insufficient_funds": r"insufficient funds|InsufficientFunds",
        "igp": r"gas_payments|IgpSync|InterchainGas",
    }
    counts = {k: len(re.findall(v, text, flags=re.I)) for k, v in patterns.items()}
    return {
        "exists": True,
        "bytes": path.stat().st_size,
        "counts": counts,
        "tail_errors": [
            line.strip()[:240]
            for line in text.splitlines()
            if "ERROR" in line
        ][-8:],
    }


def main() -> int:
    checks: list[Check] = []

    # 1. Docker / image
    try:
        subprocess.run(["docker", "info"], check=True, capture_output=True)
        docker_ok = True
        detail = "docker daemon reachable"
    except Exception as exc:
        docker_ok = False
        detail = str(exc)
    checks.append(Check("docker", "Docker daemon", "blocker", docker_ok, detail))

    try:
        out = subprocess.run(
            ["docker", "images", "-q", "ghcr.io/hyperlane-xyz/hyperlane-agent:agents-v2.2.0"],
            capture_output=True, text=True, check=True,
        )
        image_ok = bool(out.stdout.strip())
        checks.append(Check(
            "image", "Hyperlane agent image present", "blocker", image_ok,
            "agents-v2.2.0 present" if image_ok else "image missing; pull required",
        ))
    except Exception as exc:
        checks.append(Check("image", "Hyperlane agent image present", "blocker", False, str(exc)))

    # 2. Scripts / proxy config defaults
    gate3 = WORK / "relayer_official_gate3.py"
    checks.append(Check("script", "relayer_official_gate3.py exists", "blocker", gate3.exists(), str(gate3)))
    proxy = WORK / "boundaryguard_proxy.py"
    checks.append(Check("proxy", "boundaryguard_proxy.py exists", "blocker", proxy.exists(), str(proxy)))

    # 3. Signer key format (never print key)
    key, key_src = load_key()
    if not key:
        checks.append(Check("signer_key", "Signer key discoverable", "warn", False,
                            "no key in env/.env/funded/ephemeral — dry-run can continue without funded path"))
        addr = None
    else:
        hexpart = key[2:] if key.startswith("0x") else key
        fmt_ok = bool(re.fullmatch(r"[0-9a-fA-F]{64}", hexpart))
        checks.append(Check("signer_key", "Signer key format", "blocker" if fmt_ok else "blocker",
                            fmt_ok, f"source={key_src}; 32-byte hex={fmt_ok}"))
        addr = derive_address(key) if fmt_ok else None
        checks.append(Check(
            "signer_addr", "Derive signer address", "blocker" if fmt_ok else "warn",
            addr is not None,
            addr or "eth_account unavailable or key invalid",
        ))

    # 4. Balances (informational for dry-run)
    if addr:
        for name, url, sev in (
            ("optimism_balance", "https://mainnet.optimism.io", "warn"),
            ("ethereum_balance", "https://ethereum.publicnode.com", "warn"),
        ):
            ok, wei, err = balance(url, addr)
            if ok and wei is not None:
                checks.append(Check(
                    name, f"{name} for {addr}", sev,
                    True,
                    f"ETH={wei/1e18:.6f}; funded_precheck_op_ge_0.001={'YES' if (name.startswith('optimism') and wei >= 10**15) else 'n/a'}",
                ))
            else:
                # try alternate
                alt = "https://optimism-rpc.publicnode.com" if "optimism" in name else "https://rpc.ankr.com/eth"
                ok2, wei2, err2 = balance(alt, addr)
                if ok2 and wei2 is not None:
                    checks.append(Check(name, f"{name} for {addr}", sev, True,
                                        f"via_alt ETH={wei2/1e18:.6f}; rpc_err_primary={err}"))
                else:
                    checks.append(Check(name, f"{name} for {addr}", "warn", False, f"{err}; alt={err2}"))

    # 5. Optimism tip RPC + mailbox nonce (needed by BoundaryGuard)
    tip = rpc("https://mainnet.optimism.io", "eth_blockNumber", [])
    checks.append(Check("op_tip", "Optimism tip eth_blockNumber", "blocker", tip["ok"],
                        str(tip["result"] or tip["error"])))
    if tip["ok"]:
        block = tip["result"]
        nonce = rpc(
            "https://mainnet.optimism.io", "eth_call",
            [{"to": OP_MAILBOX, "data": NONCE_SELECTOR}, block],
        )
        checks.append(Check(
            "op_mailbox_nonce", "Mailbox.nonce() at tip", "blocker", nonce["ok"],
            f"result={nonce['result']}" if nonce["ok"] else str(nonce["error"]),
        ))

    # 6. Ethereum archive suitability for Hyperlane IGP sync
    # Probe a historically deep eth_getLogs-like call via eth_getBlockByNumber old block
    old = rpc("https://ethereum-rpc.publicnode.com", "eth_getBlockByNumber", [hex(18_000_000), False])
    archive_ok = old["ok"]
    checks.append(Check(
        "eth_archive_publicnode", "Ethereum publicnode archive/historical access", "blocker",
        archive_ok,
        "ok" if archive_ok else f"FAIL (known issue): {old['error']}",
    ))
    # alternate
    for label, url in (
        ("eth_llama", "https://eth.llamarpc.com"),
        ("eth_ankr", "https://rpc.ankr.com/eth"),
    ):
        alt = rpc(url, "eth_getBlockByNumber", [hex(18_000_000), False])
        checks.append(Check(
            f"eth_hist_{label}", f"Ethereum historical via {label}", "warn",
            alt["ok"], "ok" if alt["ok"] else str(alt["error"]),
        ))

    # 7. Prior relayer log autopsy
    log_info = parse_relayer_log(LOGS / "gate3_official_relayer.log")
    if log_info.get("exists"):
        c = log_info["counts"]
        checks.append(Check(
            "log_no_signer", "Prior run: destination signer errors", "warn",
            c["no_signer"] == 0,
            f"no_signer_hits={c['no_signer']} (expected if previous run had no key)",
        ))
        checks.append(Check(
            "log_archive", "Prior run: archive-token errors", "blocker",
            c["archive_token"] == 0,
            f"archive_token_hits={c['archive_token']}",
        ))
        checks.append(Check(
            "log_process", "Prior run: process/submit evidence", "info",
            c["process_attempt"] > 0 or c["delivered"] > 0,
            f"process_like={c['process_attempt']}, delivered_like={c['delivered']}",
        ))
    else:
        checks.append(Check("log_prior", "Prior official relayer log", "info", False, "no local log; check cloud"))

    # 8. Protocol feasibility warnings (always relevant)
    checks.append(Check(
        "igp_model", "IGP payment model understood", "warn", False,
        "Own relayer usually will NOT deliver messages paid to Hyperlane's default IGP. "
        "Funded dry-run without self-dispatch/IGP likely yields 0 Mailbox.process.",
    ))
    checks.append(Check(
        "evidence_gap", "Summary currently counts proxy accepts only", "warn", False,
        "relayer_official_gate3.py does not yet assert destination tx inclusion; "
        "funded success needs explorer/tx-hash evidence.",
    ))
    checks.append(Check(
        "spend_guards", "Spend guards present", "warn", False,
        "No transaction_gas_limit / max-tx / mid-run balance cap in current harness.",
    ))

    # 9. Cloud status if reachable (optional)
    cloud = {"reachable": False}
    try:
        remote = subprocess.run(
            [
                "ssh", "-o", "ConnectTimeout=8", "-o", "BatchMode=yes",
                "<BG_CLOUD_HOST>",
                "docker images -q ghcr.io/hyperlane-xyz/hyperlane-agent:agents-v2.2.0; "
                "test -f /data/boundaryguard/work/logs/gate3_official_relayer.log && "
                "grep -c 'No signer found' /data/boundaryguard/work/logs/gate3_official_relayer.log || true; "
                "grep -c 'Archive requests require' /data/boundaryguard/work/logs/gate3_official_relayer.log || true; "
                "grep -ciE 'process|delivered|submit' /data/boundaryguard/work/logs/gate3_official_relayer.log || true",
            ],
            capture_output=True, text=True, timeout=20,
        )
        if remote.returncode == 0:
            lines = [ln.strip() for ln in remote.stdout.splitlines() if ln.strip()]
            cloud = {
                "reachable": True,
                "image": bool(lines[0]) if lines else False,
                "no_signer_hits": int(lines[1]) if len(lines) > 1 and lines[1].isdigit() else lines[1:],
                "archive_hits": int(lines[2]) if len(lines) > 2 and lines[2].isdigit() else None,
                "process_like_hits": int(lines[3]) if len(lines) > 3 and lines[3].isdigit() else None,
            }
            checks.append(Check(
                "cloud_image", "Cloud agent image", "blocker", bool(cloud.get("image")),
                str(cloud),
            ))
            checks.append(Check(
                "cloud_archive_log", "Cloud prior archive errors", "blocker",
                (cloud.get("archive_hits") or 0) == 0,
                f"archive_hits={cloud.get('archive_hits')}",
            ))
    except Exception as exc:
        checks.append(Check("cloud", "Cloud SSH dry-run probes", "info", False, str(exc)))

    blockers = [c for c in checks if c.severity == "blocker" and not c.ok]
    warns = [c for c in checks if c.severity == "warn" and not c.ok]
    report = {
        "observed_at": datetime.now(timezone.utc).isoformat(),
        "address": addr,
        "key_source": key_src if key else None,
        "blocking_failures": [asdict(c) for c in blockers],
        "warnings": [asdict(c) for c in warns],
        "checks": [asdict(c) for c in checks],
        "prior_log": log_info,
        "cloud": cloud,
        "recommendation": (
            "DO_NOT_FUND_YET"
            if blockers or any(c.id in {"igp_model", "eth_archive_publicnode"} and not c.ok for c in checks)
            else "FUNDED_RUN_ONLY_WITH_SELF_DISPATCH"
        ),
        "next_zero_cost_steps": [
            "Replace ethereum-rpc.publicnode.com with an archive-capable ETH RPC in gate3 harness",
            "Short signed run (30-60s) with key + transaction_gas_limit; confirm 'No signer' errors disappear",
            "Confirm log still shows 0 process attempts without self-dispatch/IGP",
            "Only then decide testnet self-send vs mainnet self-send",
        ],
    }
    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text(json.dumps(report, indent=2, sort_keys=True) + "\n")

    print(json.dumps({
        "recommendation": report["recommendation"],
        "address": addr,
        "blocking": [(c.id, c.detail) for c in blockers],
        "warnings": [(c.id, c.detail[:120]) for c in warns],
        "artifact": str(OUT.relative_to(ROOT)),
    }, indent=2))
    return 1 if blockers else 0


if __name__ == "__main__":
    sys.exit(main())
