#!/usr/bin/env python3
"""Honest Gate-2 calendar inventory: what multi-day evidence already exists.

Does NOT invent timestamps or replay old responses as new calendar days.
Reports which live artifacts fall on which UTC dates and whether they can
support the Gate-2 silent-fault schedule claim.
"""

from __future__ import annotations

# --- github publish layout (auto-generated by sync_github_publish.py) ---
import sys
from pathlib import Path as _Path
_GITHUB_ROOT = _Path(__file__).resolve().parents[1]
_BG = _GITHUB_ROOT / "BoundaryGuard"
_EXP = _GITHUB_ROOT / "exp"
for _p in (_BG, _EXP):
    _s = str(_p)
    if _s not in sys.path:
        sys.path.insert(0, _s)
DATA = _GITHUB_ROOT.joinpath("data")
EXP = _EXP
ROOT = _GITHUB_ROOT
# --- end header ---

import json
from collections import Counter
from datetime import datetime, timezone
from pathlib import Path


ROOT = _GITHUB_ROOT
DATA = DATA
OUT = DATA / "gate2_calendar_inventory.json"


def utc_day(ts: object) -> str | None:
    if isinstance(ts, (int, float)):
        value = float(ts)
        if value > 1e14:
            value /= 1000.0
        if value > 1e12:
            value /= 1000.0
        return datetime.fromtimestamp(value, timezone.utc).date().isoformat()
    if isinstance(ts, str) and len(ts) >= 10:
        return ts[:10]
    return None


def classify_silent(row: dict) -> bool:
    if row.get("failure_class") == "successful_empty":
        return True
    if row.get("silent_semantic_failure"):
        return True
    return (
        row.get("outcome") == "ok"
        and row.get("semantic_match") is False
        and row.get("result_count") == 0
    )


def scan(path: Path) -> dict:
    days: Counter[str] = Counter()
    silent_days: Counter[str] = Counter()
    silent_providers: Counter[str] = Counter()
    rows = 0
    for line in path.open():
        if not line.strip():
            continue
        row = json.loads(line)
        rows += 1
        day = utc_day(row.get("observed_at") or row.get("ts") or row.get("timestamp"))
        if day:
            days[day] += 1
        if classify_silent(row):
            silent_providers[str(row.get("provider") or "?")] += 1
            if day:
                silent_days[day] += 1
    return {
        "path": str(path.relative_to(ROOT) if str(path).startswith(str(ROOT)) else path),
        "rows": rows,
        "utc_days": dict(days),
        "silent_empty_events": sum(silent_providers.values()),
        "silent_by_day": dict(silent_days),
        "silent_by_provider": dict(silent_providers),
    }


def main() -> None:
    targets = [
        DATA / "natural_fault_multiday.jsonl",
        DATA / "natural_fault_expansion.jsonl",
        DATA / "natural_fault_targeted.jsonl",
        DATA / "rpc_probe.jsonl",
        DATA / "density_action_gate.jsonl",
        DATA / "hyperlane_ground_truth_audit.jsonl",
        DATA / "hyperlane_ground_truth_audit_10.jsonl",
        DATA / "provider_frontier_multiday_probe.jsonl",
    ]
    studies = [scan(path) for path in targets if path.exists()]
    schedule_days = sorted({
        day
        for study in studies
        if "natural_fault_multiday" in study["path"]
        for day in study["utc_days"]
    })
    all_live_days = sorted({day for study in studies for day in study["utc_days"]})
    report = {
        "provenance_rule": (
            "Saved responses must not be re-labeled as new calendar days. "
            "Only live observation timestamps count toward Gate-2 multi-day."
        ),
        "shortcut_verdict": (
            f"Multiday schedule traces span {len(schedule_days)} UTC day(s): "
            f"{schedule_days}. Printed freeze is natural_fault_gate2_submit_freeze.json "
            "(4,416 records; five days 2026-08-03/04/05/06/18; UTC 2026-08-19 omitted). "
            "Do not treat natural_fault_gate2_summary.json (includes 2026-08-19) as the "
            "printed corpus. Saved responses must not be re-labeled as new calendar days."
        ),
        "accelerate_without_lying": [
            "Printed Gate-2 freeze is already fixed in natural_fault_gate2_submit_freeze.json.",
            "Re-running this inventory does not change the printed freeze.",
            "Collector dump natural_fault_gate2_summary.json may include excluded UTC dates.",
        ],
        "all_live_artifact_utc_days": all_live_days,
        "gate2_schedule_utc_days": schedule_days,
        "studies": studies,
    }
    OUT.write_text(json.dumps(report, indent=2, sort_keys=True) + "\n")
    print(json.dumps(report, indent=2, sort_keys=True))


if __name__ == "__main__":
    main()
