#!/usr/bin/env python3
"""Controlled integrity tests for set-complete Hyperlane message batches."""

from __future__ import annotations

# --- github publish layout (auto-generated by sync_github_publish.py) ---
import sys
from pathlib import Path as _Path
_GITHUB_ROOT = _Path(__file__).resolve().parents[1]
_BG = _GITHUB_ROOT / "BoundaryGuard"
_EXP = _GITHUB_ROOT / "exp"
for _p in (_BG, _EXP):
    _s = str(_p)
    if _s not in sys.path:
        sys.path.insert(0, _s)
DATA = _GITHUB_ROOT.joinpath("data")
EXP = _EXP
ROOT = _GITHUB_ROOT
# --- end header ---

from strong_accept_suite import run_identity_gate


def main() -> None:
    output = run_identity_gate()
    print(
        {
            "all_expected": output["all_expected"],
            "cases": sorted(output["cases"]),
            "provenance": output["provenance"],
        }
    )


if __name__ == "__main__":
    main()
