#!/usr/bin/env python3
"""Audit real Hyperlane messages across providers and query forms.

Every record has provenance=live_natural_observation. No fault is injected.
"""

from __future__ import annotations

# --- github publish layout (auto-generated by sync_github_publish.py) ---
import sys
from pathlib import Path as _Path
_GITHUB_ROOT = _Path(__file__).resolve().parents[1]
_BG = _GITHUB_ROOT / "BoundaryGuard"
_EXP = _GITHUB_ROOT / "exp"
for _p in (_BG, _EXP):
    _s = str(_p)
    if _s not in sys.path:
        sys.path.insert(0, _s)
DATA = _GITHUB_ROOT.joinpath("data")
EXP = _EXP
ROOT = _GITHUB_ROOT
# --- end header ---

import argparse
import json
import time
from collections import defaultdict
from pathlib import Path

from audit_hyperlane_ground_truth import rpc
from hyperlane_identity import DISPATCH_TOPIC, normalize, verify_dispatch


PROVIDERS = {
    "ethereum": {
        "1rpc": "https://public.1rpc.io/eth", "publicnode": "https://ethereum-rpc.publicnode.com",
        "drpc": "https://eth.drpc.org", "llamarpc": "https://eth.llamarpc.com",
        "flashbots": "https://rpc.flashbots.net", "cloudflare": "https://cloudflare-eth.com",
        "merkle": "https://eth.merkle.io", "zeroxrpc": "https://0xrpc.io/eth",
    },
    "arbitrum": {
        "1rpc": "https://public.1rpc.io/arb", "publicnode": "https://arbitrum-one-rpc.publicnode.com",
        "drpc": "https://arbitrum.drpc.org", "official": "https://arb1.arbitrum.io/rpc",
    },
    "optimism": {
        "1rpc": "https://public.1rpc.io/op", "official": "https://mainnet.optimism.io",
        "drpc": "https://optimism.drpc.org", "nodies": "https://op-pokt.nodies.app",
        "tatum": "https://optimism-mainnet.gateway.tatum.io",
    },
    "polygon": {
        "1rpc": "https://public.1rpc.io/matic", "tenderly": "https://tenderly.rpc.polygon.community",
        "drpc": "https://polygon.drpc.org", "quicknode": "https://rpc-mainnet.matic.quiknode.pro",
        "llamarpc": "https://polygon.llamarpc.com",
        "blast": "https://polygon-mainnet.public.blastapi.io",
    },
}


def load_samples(path: Path, per_chain: int) -> list[dict]:
    grouped: dict[str, list[dict]] = defaultdict(list)
    for line in path.read_text().splitlines():
        row = json.loads(line)
        grouped[row["chain"]].append(row)
    result = []
    for chain in sorted(grouped):
        rows = sorted(grouped[chain], key=lambda x: x["nonce"])
        for k in range(per_chain):
            result.append(rows[round((k + 1) * (len(rows) - 1) / (per_chain + 1))])
    return result


def semantic_logs(logs: object, expected: dict) -> dict:
    if not isinstance(logs, list):
        return {"semantic_match": False, "identity_valid": False, "result_count": None,
                "matching_logs": 0, "identity_failures": []}
    candidates = []
    failures = []
    for log in logs:
        if not isinstance(log, dict) or not log.get("topics"):
            continue
        if normalize(log["topics"][0]) != DISPATCH_TOPIC:
            continue
        verdict = verify_dispatch(log, expected)
        if verdict["valid"]:
            candidates.append(verdict["identity"])
        else:
            failures.append(verdict.get("checks", verdict.get("reason")))
    return {"semantic_match": bool(candidates), "identity_valid": bool(candidates),
            "result_count": len(logs), "matching_logs": len(candidates),
            "matched_identities": candidates, "identity_failures": failures}


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--input", type=Path, default=Path("data/hyperlane_messages.jsonl"))
    parser.add_argument("--output", type=Path, default=Path("data/natural_fault_expansion.jsonl"))
    parser.add_argument("--per-chain", type=int, default=8)
    parser.add_argument("--timeout", type=float, default=15.0)
    parser.add_argument("--delay", type=float, default=0.08)
    args = parser.parse_args()
    args.output.parent.mkdir(parents=True, exist_ok=True)
    completed = set()
    if args.output.exists():
        for line in args.output.read_text().splitlines():
            row = json.loads(line)
            completed.add((row["chain"], row["nonce"], row["provider"], row["method"]))

    with args.output.open("a", encoding="utf-8") as out:
        for message in load_samples(args.input, args.per_chain):
            chain = message["chain"]
            block_hash = normalize(message["origin_block_hash"])
            block = int(message["origin_block_height"])
            mailbox = normalize(message["origin_mailbox"])
            tx_hash = normalize(message["origin_tx_hash"])
            methods = {
                "eth_getLogs:blockHash": ("eth_getLogs", [{"blockHash": block_hash, "address": mailbox,
                                                              "topics": [DISPATCH_TOPIC]}]),
                "eth_getLogs:singleBlock": ("eth_getLogs", [{"fromBlock": hex(block), "toBlock": hex(block),
                                                                "address": mailbox, "topics": [DISPATCH_TOPIC]}]),
                "eth_getTransactionReceipt": ("eth_getTransactionReceipt", [tx_hash]),
            }
            for provider, url in PROVIDERS[chain].items():
                for label, (method, params) in methods.items():
                    key = (chain, message["nonce"], provider, label)
                    if key in completed:
                        continue
                    response = rpc(url, method, params, args.timeout)
                    result = response.pop("result", None)
                    if method == "eth_getLogs":
                        semantics = semantic_logs(result, message)
                    else:
                        valid = bool(isinstance(result, dict)
                                     and normalize(result.get("transactionHash")) == tx_hash
                                     and normalize(result.get("blockHash")) == block_hash)
                        semantics = {"semantic_match": valid, "identity_valid": valid,
                                     "result_count": 1 if isinstance(result, dict) else None}
                    record = {
                        "provenance": "live_natural_observation", "observed_at": time.time(),
                        "chain": chain, "nonce": message["nonce"], "provider": provider,
                        "method": label, "block": block, "block_hash": block_hash,
                        "tx_hash": tx_hash, **semantics, **response,
                    }
                    out.write(json.dumps(record, sort_keys=True) + "\n")
                    out.flush()
                    print(chain, message["nonce"], provider, label, response["outcome"],
                          semantics["semantic_match"], flush=True)
                    time.sleep(args.delay)


if __name__ == "__main__":
    main()
