#!/usr/bin/env python3
"""Targeted hunt for a third successful_empty provider org.

Re-probes known silent (chain, nonce, method) contexts against an expanded
public-RPC set. Writes live observations only; does not invent failures.
"""

from __future__ import annotations

# --- github publish layout (auto-generated by sync_github_publish.py) ---
import sys
from pathlib import Path as _Path
_GITHUB_ROOT = _Path(__file__).resolve().parents[1]
_BG = _GITHUB_ROOT / "BoundaryGuard"
_EXP = _GITHUB_ROOT / "exp"
for _p in (_BG, _EXP):
    _s = str(_p)
    if _s not in sys.path:
        sys.path.insert(0, _s)
DATA = _GITHUB_ROOT.joinpath("data")
EXP = _EXP
ROOT = _GITHUB_ROOT
# --- end header ---

import json
import time
from collections import Counter
from pathlib import Path

from natural_fault_gate2_complete import (
    EXTRA,
    PROVIDERS,
    TARGETED,
    consolidate,
    load_jsonl,
    message_index,
    query_one,
)


ROOT = _GITHUB_ROOT
EXPANSION = DATA / "natural_fault_expansion.jsonl"
MULTIDAY = DATA / "natural_fault_multiday.jsonl"
OUT = DATA / "natural_fault_third_hunt_round2.jsonl"
SUMMARY = DATA / "natural_fault_gate2_summary.json"

# Additional orgs beyond PROVIDERS+EXTRA already probed in prior hunts.
ROUND2 = {
    "ethereum": {
        "ankr": "https://rpc.ankr.com/eth",
        "onfinality": "https://eth.api.onfinality.io/public",
        "omnia": "https://endpoints.omniatech.io/v1/eth/mainnet/public",
        "payload": "https://rpc.payload.de",
        "merkle": "https://eth.merkle.io",
        "securerpc": "https://api.securerpc.com/v1",
        "lokibuilder": "https://rpc.lokibuilder.xyz",
        "builder0x69": "https://builder0x69.io",
        "rsync": "https://rsync-builder.xyz",
        "beaver": "https://rpc.beaverbuild.org",
        "tenderly_gateway": "https://mainnet.gateway.tenderly.co",
        "publicnode_alt": "https://ethereum.publicnode.com",
        "lm": "https://eth.llamarpc.com",
        "blockpi_alt": "https://ethereum.blockpi.network/v1/rpc/public",
        "gatewayfm": "https://rpc.eth.gateway.fm",
        "mantrachain": "https://eth.rpc.blxrbdn.com",
        "zan": "https://api.zan.top/node/v1/eth/mainnet/public",
        "starry": "https://ethereum.rpc.thirdweb.com",
    },
    "optimism": {
        "ankr": "https://rpc.ankr.com/optimism",
        "onfinality": "https://optimism.api.onfinality.io/public",
        "omnia": "https://endpoints.omniatech.io/v1/op/mainnet/public",
        "publicnode_alt": "https://optimism.publicnode.com",
        "blockpi": "https://optimism.blockpi.network/v1/rpc/public",
        "gatewayfm": "https://rpc.optimism.gateway.fm",
        "zan": "https://api.zan.top/node/v1/opt/mainnet/public",
        "starry": "https://optimism.rpc.thirdweb.com",
        "meow": "https://op.meowrpc.com",
        "blast_alt": "https://optimism-mainnet.public.blastapi.io",
    },
}


def known_silent_contexts() -> list[dict]:
    """Union of expansion + multiday successful_empty contexts."""
    keyed: dict[tuple, dict] = {}
    for row in load_jsonl(EXPANSION):
        if row.get("outcome") != "ok" or row.get("semantic_match") is not False:
            continue
        if (row.get("result_count") or 0) != 0:
            continue
        key = (row["chain"], int(row["nonce"]), row["method"])
        keyed[key] = {
            "chain": row["chain"],
            "nonce": int(row["nonce"]),
            "method": row["method"],
            "block": row["block"],
            "source_provider": row["provider"],
        }
    for row in load_jsonl(MULTIDAY):
        if row.get("failure_class") != "successful_empty":
            continue
        key = (row["chain"], int(row["nonce"]), row["method"])
        keyed.setdefault(key, {
            "chain": row["chain"],
            "nonce": int(row["nonce"]),
            "method": row["method"],
            "block": row.get("block"),
            "source_provider": row["provider"],
        })
    return list(keyed.values())


def provider_set(chain: str) -> dict[str, str]:
    merged = {}
    merged.update(PROVIDERS.get(chain, {}))
    merged.update(EXTRA.get(chain, {}))
    merged.update(ROUND2.get(chain, {}))
    return merged


def main() -> None:
    messages = message_index()
    contexts = known_silent_contexts()
    print(f"silent_contexts={len(contexts)}", flush=True)

    existing = {
        (row["chain"], row["nonce"], row["provider"], row["method"])
        for row in load_jsonl(OUT)
    }
    # Also skip pairs already present in targeted with non-empty coverage,
    # but still allow ROUND2-only provider names.
    targeted_done = {
        (row["chain"], row["nonce"], row["provider"], row["method"])
        for row in load_jsonl(TARGETED)
    }

    written = 0
    class_counts: Counter[str] = Counter()
    silent_hits: list[dict] = []
    OUT.parent.mkdir(parents=True, exist_ok=True)
    with OUT.open("a") as handle:
        for ctx in contexts:
            chain = ctx["chain"]
            if (chain, ctx["nonce"]) not in messages and (chain, int(ctx["nonce"])) not in messages:
                print("skip_missing_message", chain, ctx["nonce"], flush=True)
                continue
            message = messages[(chain, int(ctx["nonce"]))]
            for provider, url in provider_set(chain).items():
                key = (chain, ctx["nonce"], provider, ctx["method"])
                if key in existing or key in targeted_done:
                    continue
                # Only probe ROUND2-new orgs this round to save time; EXTRA/PROVIDERS
                # were already covered by prior targeted/third hunts.
                if provider not in ROUND2.get(chain, {}):
                    continue
                got = query_one(url, message, ctx["method"], timeout=12.0)
                record = {
                    "provenance": "live_natural_observation",
                    "observed_at": time.time(),
                    "kind": "third_silent_hunt_round2",
                    "source_provider": ctx["source_provider"],
                    "chain": chain,
                    "nonce": ctx["nonce"],
                    "block": ctx.get("block") or int(message["origin_block_height"]),
                    "provider": provider,
                    "method": ctx["method"],
                    **got,
                }
                handle.write(json.dumps(record, sort_keys=True) + "\n")
                handle.flush()
                written += 1
                class_counts[got["failure_class"]] += 1
                print(
                    "hunt", chain, provider, ctx["method"], got["failure_class"],
                    flush=True,
                )
                if got["failure_class"] == "successful_empty":
                    silent_hits.append(record)
                time.sleep(0.05)

    # Fold round2 rows into targeted so consolidate() sees them.
    round2_rows = load_jsonl(OUT)
    existing_targeted = {
        (row["chain"], row["nonce"], row["provider"], row["method"])
        for row in load_jsonl(TARGETED)
    }
    appended = 0
    with TARGETED.open("a") as handle:
        for row in round2_rows:
            key = (row["chain"], row["nonce"], row["provider"], row["method"])
            if key in existing_targeted:
                continue
            handle.write(json.dumps(row, sort_keys=True) + "\n")
            appended += 1
            existing_targeted.add(key)

    summary = consolidate()
    # Recompute limitation now that we have ≥3 calendar days.
    if len(summary.get("calendar_days") or []) >= 3 and not summary.get("meets_three_silent_providers"):
        summary["limitation_note"] = (
            "Observed successful_empty from only two provider orgs "
            f"({', '.join(summary.get('silent_empty_providers') or [])}) after expanded "
            "targeted third-org hunt; second failure class truncated_or_stale_nonempty is present."
        )
    SUMMARY.write_text(json.dumps(summary, indent=2, sort_keys=True) + "\n")

    report = {
        "written": written,
        "appended_to_targeted": appended,
        "class_counts": dict(class_counts),
        "new_successful_empty": [
            {
                "chain": r["chain"],
                "provider": r["provider"],
                "nonce": r["nonce"],
                "method": r["method"],
            }
            for r in silent_hits
        ],
        "silent_empty_providers": summary.get("silent_empty_providers"),
        "meets_three_silent_providers": summary.get("meets_three_silent_providers"),
        "calendar_days": summary.get("calendar_days"),
        "second_failure_class_observed": summary.get("second_failure_class_observed"),
        "limitation_note": summary.get("limitation_note"),
    }
    print(json.dumps(report, indent=2, sort_keys=True))


if __name__ == "__main__":
    main()
