#!/usr/bin/env python3
"""Gate 2 completion: confirm ≥3 silent providers and hunt a second failure class.

Re-probes known silent contexts from the expansion study across additional
providers, appends a fresh multiday epoch, and writes a consolidated summary.
Calendar multi-day is reported honestly from observation timestamps.
"""

from __future__ import annotations

# --- github publish layout (auto-generated by sync_github_publish.py) ---
import sys
from pathlib import Path as _Path
_GITHUB_ROOT = _Path(__file__).resolve().parents[1]
_BG = _GITHUB_ROOT / "BoundaryGuard"
_EXP = _GITHUB_ROOT / "exp"
for _p in (_BG, _EXP):
    _s = str(_p)
    if _s not in sys.path:
        sys.path.insert(0, _s)
DATA = _GITHUB_ROOT.joinpath("data")
EXP = _EXP
ROOT = _GITHUB_ROOT
# --- end header ---

import hashlib
import json
import time
from collections import Counter, defaultdict
from datetime import datetime, timezone
from pathlib import Path

from audit_hyperlane_ground_truth import rpc
from hyperlane_identity import DISPATCH_TOPIC, normalize, verify_dispatch
from natural_fault_multiday import (
    PROVIDERS,
    body_hash,
    classify,
    ensure_schedule,
    message_index,
    next_epoch,
)


ROOT = _GITHUB_ROOT
EXPANSION = DATA / "natural_fault_expansion.jsonl"
MULTIDAY = DATA / "natural_fault_multiday.jsonl"
TARGETED = DATA / "natural_fault_targeted.jsonl"
SUMMARY = DATA / "natural_fault_gate2_summary.json"

# Extra Ethereum/Optimism endpoints to hunt a third silent org.
EXTRA = {
    "ethereum": {
        "blast": "https://eth-mainnet.public.blastapi.io",
        "meow": "https://eth.meowrpc.com",
        "nodies": "https://eth-pokt.nodies.app",
        "blockpi": "https://ethereum.blockpi.network/v1/rpc/public",
        "tenderly": "https://ethereum.gateway.tenderly.co",
    },
    "optimism": {
        "blast": "https://optimism-mainnet.public.blastapi.io",
        "publicnode": "https://optimism-rpc.publicnode.com",
        "llamarpc": "https://optimism.llamarpc.com",
        "tenderly": "https://optimism.gateway.tenderly.co",
    },
}


def load_jsonl(path: Path) -> list[dict]:
    if not path.exists():
        return []
    return [json.loads(line) for line in path.read_text().splitlines() if line.strip()]


def known_silent_contexts() -> list[dict]:
    """Unique (chain, nonce, method) that previously returned successful-empty."""
    keyed = {}
    for row in load_jsonl(EXPANSION):
        if row.get("outcome") != "ok" or row.get("semantic_match") is not False:
            continue
        if (row.get("result_count") or 0) != 0:
            continue
        key = (row["chain"], int(row["nonce"]), row["method"])
        keyed[key] = {
            "chain": row["chain"],
            "nonce": int(row["nonce"]),
            "method": row["method"],
            "block": row["block"],
            "source_provider": row["provider"],
        }
    return list(keyed.values())


def query_one(url: str, message: dict, method: str, timeout: float) -> dict:
    block_hash = normalize(message["origin_block_hash"])
    block = int(message["origin_block_height"])
    mailbox = normalize(message["origin_mailbox"])
    tx_hash = normalize(message["origin_tx_hash"])
    if method == "eth_getLogs:blockHash":
        rpc_method, params = "eth_getLogs", [{"blockHash": block_hash, "address": mailbox,
                                              "topics": [DISPATCH_TOPIC]}]
    elif method == "eth_getLogs:singleBlock":
        rpc_method, params = "eth_getLogs", [{"fromBlock": hex(block), "toBlock": hex(block),
                                              "address": mailbox, "topics": [DISPATCH_TOPIC]}]
    else:
        rpc_method, params = "eth_getTransactionReceipt", [tx_hash]
    response = rpc(url, rpc_method, params, timeout)
    result = response.pop("result", None)
    semantics = classify(result, message, method)
    failure = semantics["class"] if response["outcome"] == "ok" else f"explicit:{response['outcome']}"
    return {
        "outcome": response["outcome"],
        "latency_ms": response.get("latency_ms"),
        "error": response.get("error"),
        "response_sha256": body_hash(result),
        "failure_class": failure,
        "semantic_match": semantics.get("semantic_match"),
        "result_count": semantics.get("result_count"),
    }


def run_targeted(timeout: float = 12.0, delay: float = 0.05) -> int:
    messages = message_index()
    contexts = known_silent_contexts()
    existing = {
        (row["chain"], row["nonce"], row["provider"], row["method"])
        for row in load_jsonl(TARGETED)
    }
    written = 0
    with TARGETED.open("a") as handle:
        for ctx in contexts:
            chain = ctx["chain"]
            message = messages[(chain, ctx["nonce"])]
            providers = {**PROVIDERS.get(chain, {}), **EXTRA.get(chain, {})}
            for provider, url in providers.items():
                key = (chain, ctx["nonce"], provider, ctx["method"])
                if key in existing:
                    continue
                got = query_one(url, message, ctx["method"], timeout)
                record = {
                    "provenance": "live_natural_observation",
                    "observed_at": time.time(),
                    "kind": "targeted_silent_reprobe",
                    "source_provider": ctx["source_provider"],
                    "chain": chain,
                    "nonce": ctx["nonce"],
                    "block": ctx["block"],
                    "provider": provider,
                    "method": ctx["method"],
                    **got,
                }
                handle.write(json.dumps(record, sort_keys=True) + "\n")
                handle.flush()
                written += 1
                print("targeted", chain, provider, ctx["method"], got["failure_class"], flush=True)
                time.sleep(delay)
    return written


def run_epoch(per_chain: int = 8, timeout: float = 12.0, delay: float = 0.05) -> int:
    schedule = ensure_schedule(per_chain)
    messages = message_index()
    existing = load_jsonl(MULTIDAY)
    epoch = next_epoch(existing)
    done = {
        (row["epoch"], row["chain"], row["nonce"], row["provider"], row["method"])
        for row in existing
    }
    written = 0
    with MULTIDAY.open("a") as handle:
        for entry in schedule["entries"]:
            key = (epoch, entry["chain"], entry["nonce"], entry["provider"], entry["method"])
            if key in done:
                continue
            message = messages[(entry["chain"], entry["nonce"])]
            url = PROVIDERS[entry["chain"]][entry["provider"]]
            got = query_one(url, message, entry["method"], timeout)
            record = {
                "provenance": "live_natural_observation",
                "observed_at": time.time(),
                "epoch": epoch,
                "schedule_sha256": schedule["schedule_sha256"],
                "chain": entry["chain"],
                "nonce": entry["nonce"],
                "block": int(message["origin_block_height"]),
                "provider": entry["provider"],
                "method": entry["method"],
                **got,
            }
            handle.write(json.dumps(record, sort_keys=True) + "\n")
            handle.flush()
            written += 1
            print(epoch, entry["chain"], entry["provider"], entry["method"],
                  record["failure_class"], flush=True)
            time.sleep(delay)
    return written


def consolidate() -> dict:
    silent_classes = {"successful_empty", "truncated_or_stale_nonempty", "successful_null"}
    rows = []
    for path, source in (
        (EXPANSION, "expansion"),
        (MULTIDAY, "multiday"),
        (TARGETED, "targeted"),
    ):
        for row in load_jsonl(path):
            item = dict(row)
            item["_source"] = source
            # Normalize expansion rows into failure_class.
            if "failure_class" not in item:
                if item.get("outcome") == "ok" and item.get("semantic_match") is False:
                    # Distinguish true empty from missing count.
                    if item.get("result_count") == 0:
                        item["failure_class"] = "successful_empty"
                    elif isinstance(item.get("result_count"), int) and item["result_count"] > 0:
                        item["failure_class"] = "truncated_or_stale_nonempty"
                    else:
                        item["failure_class"] = "successful_empty_or_null"
                        # Keep out of primary silent_empty provider gate unless clearly empty.
                elif item.get("outcome") == "ok":
                    item["failure_class"] = "complete"
                else:
                    item["failure_class"] = f"explicit:{item.get('outcome')}"
            if "response_sha256" not in item:
                # Prefer identity-bearing fields so distinct empties do not collapse.
                payload = json.dumps(
                    {
                        k: item.get(k)
                        for k in (
                            "chain", "nonce", "block", "provider", "method",
                            "result_count", "matching_logs", "outcome", "error",
                            "observed_at",
                        )
                    },
                    sort_keys=True,
                    default=str,
                ).encode()
                item["response_sha256"] = hashlib.sha256(payload).hexdigest()
                item["response_sha256_synthetic"] = True
            rows.append(item)

    # Dedup only within (source, epoch|None, context). Different multiday epochs
    # on different UTC days must be retained for calendar-day accounting.
    source_rank = {"expansion": 0, "multiday": 1, "targeted": 2}
    keyed: dict[tuple, dict] = {}
    for row in sorted(rows, key=lambda r: source_rank.get(r["_source"], 9)):
        key = (
            row.get("_source"),
            row.get("epoch"),
            row.get("chain"),
            row.get("nonce"),
            row.get("provider"),
            row.get("method"),
        )
        if key not in keyed:
            keyed[key] = row
    rows = list(keyed.values())

    silent = [row for row in rows if row.get("failure_class") in silent_classes]
    empty = [row for row in silent if row["failure_class"] == "successful_empty"]
    # Unique contexts across all epochs/sources for provider-diversity gate.
    unique_empty_ctx = {
        (r.get("chain"), r.get("nonce"), r.get("provider"), r.get("method")) for r in empty
    }
    by_provider = Counter(row["provider"] for row in empty)
    by_chain_provider = Counter((row["chain"], row["provider"]) for row in empty)
    # Provider gate uses unique contexts, not duplicated source rows.
    by_provider_unique = Counter(ctx[2] for ctx in unique_empty_ctx)
    by_chain_provider_unique = Counter((ctx[0], ctx[2]) for ctx in unique_empty_ctx)
    classes = Counter(row["failure_class"] for row in silent)
    clusters = defaultdict(list)
    for row in silent:
        clusters[row["response_sha256"]].append(row)
    days = sorted({
        datetime.fromtimestamp(row["observed_at"], timezone.utc).date().isoformat()
        for row in rows if isinstance(row.get("observed_at"), (int, float))
    })
    epochs = sorted({int(row["epoch"]) for row in rows if "epoch" in row})
    providers_silent = sorted(by_provider_unique)
    return {
        "provenance": "live_natural_observation",
        "records": len(rows),
        "sources": {
            "expansion": sum(1 for r in rows if r["_source"] == "expansion"),
            "multiday": sum(1 for r in rows if r["_source"] == "multiday"),
            "targeted": sum(1 for r in rows if r["_source"] == "targeted"),
        },
        "calendar_days": days,
        "epochs": epochs,
        "silent_response_events": len(silent),
        "silent_empty_unique_contexts": len(unique_empty_ctx),
        "silent_unique_response_hashes": len(clusters),
        "silent_unique_nonces": len({(r["chain"], r["nonce"]) for r in silent}),
        "silent_unique_blocks": len({(r["chain"], r["block"]) for r in silent if "block" in r}),
        "silent_empty_providers": providers_silent,
        "silent_empty_provider_count": len(providers_silent),
        "silent_empty_by_provider": dict(by_provider_unique),
        "silent_empty_by_chain_provider": {
            f"{c}/{p}": n for (c, p), n in by_chain_provider_unique.most_common()
        },
        "silent_empty_by_provider_raw_rows": dict(by_provider),
        "failure_class_counts": dict(classes),
        "second_failure_class_observed": any(cls != "successful_empty" for cls in classes),
        "meets_three_silent_providers": len(providers_silent) >= 3,
        "limitation_note": (
            None if len(days) >= 2
            else "All live natural-fault timestamps currently share one UTC calendar day; "
                 "multi-epoch same-day collection is complete and the frozen schedule supports resume."
        ),
    }


def main() -> None:
    print("targeted written", run_targeted(), flush=True)
    print("epoch written", run_epoch(), flush=True)
    summary = consolidate()
    SUMMARY.write_text(json.dumps(summary, indent=2, sort_keys=True) + "\n")
    # Keep multiday summary aligned for freeze scripts.
    from natural_fault_multiday import summarize
    multi = load_jsonl(MULTIDAY)
    (DATA / "natural_fault_multiday_summary.json").write_text(
        json.dumps(summarize(multi), indent=2, sort_keys=True) + "\n"
    )
    print(json.dumps(summary, indent=2, sort_keys=True))


if __name__ == "__main__":
    main()
