#!/usr/bin/env python3
"""Gate 2 multi-day resume runner.

Runs one frozen-schedule epoch when today's UTC date is not yet covered
(or when --force). The target is configurable and defaults to 14 distinct UTC
calendar dates for the Computer Networks recurrence study. Does not rewrite the
frozen schedule.

Examples:
  python3 work/natural_fault_daily_resume.py           # skip if today already present
  python3 work/natural_fault_daily_resume.py --force   # always add one epoch
  python3 work/natural_fault_daily_resume.py --status  # print day/epoch coverage
"""

from __future__ import annotations

# --- github publish layout (auto-generated by sync_github_publish.py) ---
import sys
from pathlib import Path as _Path
_GITHUB_ROOT = _Path(__file__).resolve().parents[1]
_BG = _GITHUB_ROOT / "BoundaryGuard"
_EXP = _GITHUB_ROOT / "exp"
for _p in (_BG, _EXP):
    _s = str(_p)
    if _s not in sys.path:
        sys.path.insert(0, _s)
DATA = _GITHUB_ROOT.joinpath("data")
EXP = _EXP
ROOT = _GITHUB_ROOT
# --- end header ---

import argparse
import json
import subprocess
import sys
from collections import Counter
from datetime import datetime, timezone
from pathlib import Path


ROOT = _GITHUB_ROOT
MULTIDAY = DATA / "natural_fault_multiday.jsonl"
SUMMARY = DATA / "natural_fault_gate2_summary.json"
LOG = ROOT / "logs" / "gate2_daily_resume.log"


def load_rows() -> list[dict]:
    if not MULTIDAY.exists():
        return []
    return [json.loads(line) for line in MULTIDAY.read_text().splitlines() if line.strip()]


def calendar_days(rows: list[dict]) -> list[str]:
    days = sorted({
        datetime.fromtimestamp(row["observed_at"], timezone.utc).date().isoformat()
        for row in rows
        if isinstance(row.get("observed_at"), (int, float))
    })
    return days


def status(target_days: int = 14) -> dict:
    rows = load_rows()
    days = calendar_days(rows)
    epochs = sorted({int(row.get("epoch", 0)) for row in rows})
    today = datetime.now(timezone.utc).date().isoformat()
    by_day = Counter(
        datetime.fromtimestamp(row["observed_at"], timezone.utc).date().isoformat()
        for row in rows
        if isinstance(row.get("observed_at"), (int, float))
    )
    return {
        "utc_now": datetime.now(timezone.utc).isoformat(),
        "utc_today": today,
        "calendar_days": days,
        "day_count": len(days),
        "meets_target_calendar_days": len(days) >= target_days,
        "today_already_covered": today in days,
        "epochs": epochs,
        "rows": len(rows),
        "rows_by_day": dict(by_day),
        "target_calendar_days": target_days,
    }


def append_log(message: str) -> None:
    LOG.parent.mkdir(parents=True, exist_ok=True)
    with LOG.open("a") as handle:
        handle.write(f"{datetime.now(timezone.utc).isoformat()} {message}\n")


def run_epoch() -> int:
    # One full schedule epoch via the existing Gate-2 script path:
    # natural_fault_multiday.main logic is invoked through gate2_complete's run_epoch
    # when targeted is skipped; call multiday directly for a clean daily resume.
    cmd = [sys.executable, str(ROOT / "natural_fault_multiday.py")]
    append_log(f"start {' '.join(cmd)}")
    completed = subprocess.run(cmd, cwd=str(ROOT), check=False)
    append_log(f"exit {completed.returncode}")
    # Refresh consolidated Gate-2 summary (includes expansion/targeted).
    consolidate = subprocess.run(
        [sys.executable, "-c",
         "from natural_fault_gate2_complete import consolidate, SUMMARY; "
         "import json; "
         "s=consolidate(); SUMMARY.write_text(json.dumps(s, indent=2, sort_keys=True)+chr(10)); "
         "print(json.dumps({k:s[k] for k in ['calendar_days','silent_empty_providers',"
         "'meets_three_silent_providers','second_failure_class_observed','records']}, indent=2))"],
        cwd=str(ROOT),
        check=False,
    )
    return completed.returncode or consolidate.returncode


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--status", action="store_true")
    parser.add_argument("--force", action="store_true",
                        help="Run an epoch even if today's UTC date is already covered")
    parser.add_argument("--target-days", type=int, default=14,
                        help="Distinct UTC dates required before normal runs stop")
    args = parser.parse_args()

    if args.target_days < 1:
        parser.error("--target-days must be positive")
    info = status(args.target_days)
    print(json.dumps(info, indent=2, sort_keys=True))
    if args.status:
        return

    if info["meets_target_calendar_days"] and not args.force:
        print("already_meets_target_calendar_days; use --force to add another epoch")
        append_log(f"skip already_meets_target_days target={args.target_days}")
        return

    if info["today_already_covered"] and not args.force:
        print("skip: utc_today already covered; wait for next UTC date or pass --force")
        append_log(f"skip today_covered {info['utc_today']}")
        return

    code = run_epoch()
    info_after = status(args.target_days)
    print(json.dumps({"run_exit": code, "after": info_after}, indent=2, sort_keys=True))
    if code != 0:
        raise SystemExit(code)


if __name__ == "__main__":
    main()
