#!/usr/bin/env python3
"""Gate 2: multi-epoch natural-fault collection with response hashing/clustering.

Each epoch reuses the same frozen message/provider/method schedule. Calendar
multi-day collection is supported via resume; this script also records epoch
index and response body hashes so repeats are clustered, not double-counted as
independent root causes.
"""

from __future__ import annotations

# --- github publish layout (auto-generated by sync_github_publish.py) ---
import sys
from pathlib import Path as _Path
_GITHUB_ROOT = _Path(__file__).resolve().parents[1]
_BG = _GITHUB_ROOT / "BoundaryGuard"
_EXP = _GITHUB_ROOT / "exp"
for _p in (_BG, _EXP):
    _s = str(_p)
    if _s not in sys.path:
        sys.path.insert(0, _s)
DATA = _GITHUB_ROOT.joinpath("data")
EXP = _EXP
ROOT = _GITHUB_ROOT
# --- end header ---

import argparse
import hashlib
import json
import time
from collections import Counter, defaultdict
from datetime import datetime, timezone
from pathlib import Path

from audit_hyperlane_ground_truth import rpc
from hyperlane_identity import DISPATCH_TOPIC, normalize, verify_dispatch


ROOT = _GITHUB_ROOT
MESSAGES = DATA / "hyperlane_messages.jsonl"
OUT = DATA / "natural_fault_multiday.jsonl"
SUMMARY = DATA / "natural_fault_multiday_summary.json"
SCHEDULE = DATA / "natural_fault_schedule.json"

PROVIDERS = {
    "ethereum": {
        "1rpc": "https://public.1rpc.io/eth",
        "publicnode": "https://ethereum-rpc.publicnode.com",
        "drpc": "https://eth.drpc.org",
        "llamarpc": "https://eth.llamarpc.com",
        "flashbots": "https://rpc.flashbots.net",
        "zeroxrpc": "https://0xrpc.io/eth",
        "cloudflare": "https://cloudflare-eth.com",
    },
    "arbitrum": {
        "1rpc": "https://public.1rpc.io/arb",
        "publicnode": "https://arbitrum-one-rpc.publicnode.com",
        "drpc": "https://arbitrum.drpc.org",
        "official": "https://arb1.arbitrum.io/rpc",
    },
    "optimism": {
        "1rpc": "https://public.1rpc.io/op",
        "official": "https://mainnet.optimism.io",
        "drpc": "https://optimism.drpc.org",
        "nodies": "https://op-pokt.nodies.app",
    },
    "polygon": {
        "1rpc": "https://public.1rpc.io/matic",
        "tenderly": "https://tenderly.rpc.polygon.community",
        "drpc": "https://polygon.drpc.org",
        "quicknode": "https://rpc-mainnet.matic.quiknode.pro",
        "llamarpc": "https://polygon.llamarpc.com",
    },
}


def load_samples(per_chain: int) -> list[dict]:
    grouped: dict[str, list[dict]] = defaultdict(list)
    with MESSAGES.open() as handle:
        for line in handle:
            row = json.loads(line)
            grouped[row["chain"]].append(row)
    result = []
    for chain in sorted(grouped):
        rows = sorted(grouped[chain], key=lambda x: x["nonce"])
        for k in range(per_chain):
            result.append(rows[round((k + 1) * (len(rows) - 1) / (per_chain + 1))])
    return result


def classify(result: object, expected: dict, method: str) -> dict:
    if method.startswith("eth_getLogs"):
        if not isinstance(result, list):
            return {"class": "malformed_result", "semantic_match": False, "result_count": None}
        matches = []
        for log in result:
            if not isinstance(log, dict) or not log.get("topics"):
                continue
            if normalize(log["topics"][0]) != DISPATCH_TOPIC:
                continue
            verdict = verify_dispatch(log, expected)
            if verdict["valid"]:
                matches.append(verdict["identity"])
        if matches:
            return {"class": "complete", "semantic_match": True, "result_count": len(result),
                    "matching_logs": len(matches)}
        if len(result) == 0:
            return {"class": "successful_empty", "semantic_match": False, "result_count": 0}
        return {"class": "truncated_or_stale_nonempty", "semantic_match": False,
                "result_count": len(result)}
    # receipt path
    valid = bool(isinstance(result, dict)
                 and normalize(result.get("transactionHash")) == normalize(expected["origin_tx_hash"])
                 and normalize(result.get("blockHash")) == normalize(expected["origin_block_hash"]))
    if valid:
        return {"class": "complete", "semantic_match": True, "result_count": 1}
    if result is None:
        return {"class": "successful_null", "semantic_match": False, "result_count": 0}
    return {"class": "truncated_or_stale_nonempty", "semantic_match": False, "result_count": 1}


def body_hash(result: object) -> str:
    payload = json.dumps(result, sort_keys=True, default=str).encode()
    return hashlib.sha256(payload).hexdigest()


def ensure_schedule(per_chain: int) -> dict:
    if SCHEDULE.exists():
        return json.loads(SCHEDULE.read_text())
    samples = load_samples(per_chain)
    entries = []
    for message in samples:
        chain = message["chain"]
        for provider in PROVIDERS[chain]:
            for method in ("eth_getLogs:blockHash", "eth_getLogs:singleBlock", "eth_getTransactionReceipt"):
                entries.append({
                    "chain": chain,
                    "nonce": message["nonce"],
                    "provider": provider,
                    "method": method,
                    "block": message["origin_block_height"],
                    "msg_id": message["msg_id"],
                })
    schedule = {
        "created_at": datetime.now(timezone.utc).isoformat(),
        "per_chain": per_chain,
        "entries": entries,
        "schedule_sha256": hashlib.sha256(json.dumps(entries, sort_keys=True).encode()).hexdigest(),
    }
    SCHEDULE.write_text(json.dumps(schedule, indent=2, sort_keys=True) + "\n")
    return schedule


def message_index() -> dict[tuple[str, int], dict]:
    index = {}
    with MESSAGES.open() as handle:
        for line in handle:
            row = json.loads(line)
            index[(row["chain"], int(row["nonce"]))] = row
    return index


def next_epoch(existing: list[dict]) -> int:
    if not existing:
        return 0
    return 1 + max(int(row.get("epoch", 0)) for row in existing)


def summarize(records: list[dict]) -> dict:
    silent = [row for row in records if row.get("failure_class") in
              ("successful_empty", "truncated_or_stale_nonempty", "successful_null")]
    by_provider = Counter((row["chain"], row["provider"]) for row in silent
                          if row["failure_class"] == "successful_empty")
    classes = Counter(row["failure_class"] for row in silent)
    # cluster by response hash among silent failures
    clusters = defaultdict(list)
    for row in silent:
        clusters[row["response_sha256"]].append(row)
    unique_nonces = {(row["chain"], row["nonce"]) for row in silent}
    unique_blocks = {(row["chain"], row["block"]) for row in silent}
    days = sorted({
        datetime.fromtimestamp(row["observed_at"], timezone.utc).date().isoformat()
        for row in records if row.get("observed_at")
    })
    providers_silent = sorted({row["provider"] for row in silent if row["failure_class"] == "successful_empty"})
    return {
        "provenance": "live_natural_observation",
        "records": len(records),
        "epochs": sorted({int(row.get("epoch", 0)) for row in records}),
        "calendar_days": days,
        "silent_response_events": len(silent),
        "silent_unique_response_hashes": len(clusters),
        "silent_unique_nonces": len(unique_nonces),
        "silent_unique_blocks": len(unique_blocks),
        "silent_empty_providers": providers_silent,
        "silent_empty_provider_count": len(providers_silent),
        "failure_class_counts": dict(classes),
        "silent_empty_by_chain_provider": {
            f"{c}/{p}": n for (c, p), n in by_provider.most_common()
        },
        "second_failure_class_observed": any(
            cls != "successful_empty" for cls in classes
        ),
        "meets_three_silent_providers": len(providers_silent) >= 3,
        "schedule_sha256": records[0]["schedule_sha256"] if records else None,
    }


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--per-chain", type=int, default=8)
    parser.add_argument("--timeout", type=float, default=12.0)
    parser.add_argument("--delay", type=float, default=0.05)
    parser.add_argument("--max-queries", type=int, default=0, help="0 means full epoch")
    args = parser.parse_args()

    schedule = ensure_schedule(args.per_chain)
    messages = message_index()
    existing = [json.loads(line) for line in OUT.read_text().splitlines()] if OUT.exists() else []
    epoch = next_epoch(existing)
    done = {
        (row["epoch"], row["chain"], row["nonce"], row["provider"], row["method"])
        for row in existing
    }
    written = 0
    with OUT.open("a") as handle:
        for entry in schedule["entries"]:
            key = (epoch, entry["chain"], entry["nonce"], entry["provider"], entry["method"])
            if key in done:
                continue
            message = messages[(entry["chain"], entry["nonce"])]
            url = PROVIDERS[entry["chain"]][entry["provider"]]
            block_hash = normalize(message["origin_block_hash"])
            block = int(message["origin_block_height"])
            mailbox = normalize(message["origin_mailbox"])
            tx_hash = normalize(message["origin_tx_hash"])
            if entry["method"] == "eth_getLogs:blockHash":
                method, params = "eth_getLogs", [{"blockHash": block_hash, "address": mailbox,
                                                  "topics": [DISPATCH_TOPIC]}]
            elif entry["method"] == "eth_getLogs:singleBlock":
                method, params = "eth_getLogs", [{"fromBlock": hex(block), "toBlock": hex(block),
                                                  "address": mailbox, "topics": [DISPATCH_TOPIC]}]
            else:
                method, params = "eth_getTransactionReceipt", [tx_hash]
            response = rpc(url, method, params, args.timeout)
            result = response.pop("result", None)
            semantics = classify(result, message, entry["method"])
            record = {
                "provenance": "live_natural_observation",
                "observed_at": time.time(),
                "epoch": epoch,
                "schedule_sha256": schedule["schedule_sha256"],
                "chain": entry["chain"],
                "nonce": entry["nonce"],
                "block": block,
                "provider": entry["provider"],
                "method": entry["method"],
                "outcome": response["outcome"],
                "latency_ms": response.get("latency_ms"),
                "error": response.get("error"),
                "response_sha256": body_hash(result),
                "failure_class": semantics["class"] if response["outcome"] == "ok" else f"explicit:{response['outcome']}",
                "semantic_match": semantics.get("semantic_match"),
                "result_count": semantics.get("result_count"),
            }
            handle.write(json.dumps(record, sort_keys=True) + "\n")
            handle.flush()
            written += 1
            print(epoch, entry["chain"], entry["provider"], entry["method"],
                  record["failure_class"], response["outcome"], flush=True)
            if args.max_queries and written >= args.max_queries:
                break
            time.sleep(args.delay)
    records = [json.loads(line) for line in OUT.read_text().splitlines()] if OUT.exists() else []
    summary = summarize(records)
    SUMMARY.write_text(json.dumps(summary, indent=2, sort_keys=True) + "\n")
    print(json.dumps(summary, indent=2, sort_keys=True))


if __name__ == "__main__":
    main()
