#!/usr/bin/env python3
"""Expand live detect-localize-repair timing over saved natural failures.

The failed primary observation is unmodified and kept at its real block. The
surrounding batch is a canonical trace replay; boundary and repair RPCs are live.
"""

from __future__ import annotations

# --- github publish layout (auto-generated by sync_github_publish.py) ---
import sys
from pathlib import Path as _Path
_GITHUB_ROOT = _Path(__file__).resolve().parents[1]
_BG = _GITHUB_ROOT / "BoundaryGuard"
_EXP = _GITHUB_ROOT / "exp"
for _p in (_BG, _EXP):
    _s = str(_p)
    if _s not in sys.path:
        sys.path.insert(0, _s)
DATA = _GITHUB_ROOT.joinpath("data")
EXP = _EXP
ROOT = _GITHUB_ROOT
# --- end header ---

import json
import time
from collections import defaultdict
from pathlib import Path

from boundaryguard_batch_gate import Chunk, locate_bad_chunks
from boundaryguard_scale_gate import DISPATCH_TOPIC, NONCE_SELECTOR, normalize, rpc_retry


ROOT = _GITHUB_ROOT
OUTPUT = ROOT / "data/natural_e2e_expanded.jsonl"
CONFIG = {
    "optimism": {"width": 1_000, "boundary": "https://optimism.drpc.org",
                 "repair": "https://mainnet.optimism.io", "repair_name": "official"},
    "ethereum": {"width": 1_000, "boundary": "https://eth.drpc.org",
                 "repair": "https://0xrpc.io/eth", "repair_name": "0xrpc"},
}


class TimedBoundary:
    def __init__(self, url: str, mailbox: str):
        self.url, self.mailbox = url, mailbox
        self.cache = {}
        self.records = []
        self.calls = 0

    def nonce(self, block: int) -> int:
        if block in self.cache:
            return self.cache[block]
        started = time.perf_counter()
        response = rpc_retry(self.url, "eth_call", [{"to": self.mailbox, "data": NONCE_SELECTOR}, hex(block)])
        wall = (time.perf_counter() - started) * 1000
        raw = response.pop("result", None)
        if response["outcome"] != "ok" or not isinstance(raw, str):
            raise RuntimeError(f"boundary unavailable: {block} {response}")
        value = int(raw, 16)
        self.cache[block] = value; self.calls += 1
        self.records.append({"block": block, "nonce": value, "wall_ms": wall, **response})
        return value


def messages_by_chain() -> dict[str, list[dict]]:
    result = defaultdict(list)
    for line in (ROOT / "data/hyperlane_messages.jsonl").read_text().splitlines():
        row = json.loads(line)
        if row["chain"] in CONFIG:
            result[row["chain"]].append(row)
    for rows in result.values():
        rows.sort(key=lambda r: r["origin_block_height"])
    return result


def natural_failures() -> list[dict]:
    rows = []
    for path in (ROOT / "data/hyperlane_ground_truth_audit_10.jsonl",
                 ROOT / "data/natural_fault_expansion.jsonl"):
        for line in path.read_text().splitlines():
            row = json.loads(line)
            if row["chain"] in CONFIG and row["outcome"] == "ok" and not row.get("semantic_match", False):
                rows.append(row)
    unique = {}
    for row in rows:
        unique[(row["chain"], row["provider"], row["method"], row["nonce"])] = row
    return list(unique.values())


def make_chunks(rows: list[dict], block: int, width: int) -> list[Chunk]:
    start = (block // width) * width - 4 * width
    lo, hi = rows[0]["origin_block_height"] + 1, rows[-1]["origin_block_height"] - 1
    start = max(lo, min(start, hi - 8 * width + 1))
    return [Chunk(start + i * width, start + (i + 1) * width - 1) for i in range(8)]


def run(failure: dict, rows: list[dict]) -> dict:
    message = next(row for row in rows if row["nonce"] == failure["nonce"])
    cfg = CONFIG[failure["chain"]]
    block = message["origin_block_height"]
    chunks = make_chunks(rows, block, cfg["width"])
    expected_counts = [sum(c.start <= r["origin_block_height"] <= c.end for r in rows) for c in chunks]
    bad_index = next(i for i, c in enumerate(chunks) if c.start <= block <= c.end)
    observed = list(expected_counts)
    omitted = sum(r["origin_block_height"] == block for r in rows)
    observed[bad_index] -= omitted
    boundary = TimedBoundary(cfg["boundary"], normalize(message["origin_mailbox"]))
    decisions = []
    started = time.perf_counter()
    # The first two uncached calls are detection. Subsequent calls localize.
    located = locate_bad_chunks(chunks, observed, boundary, decisions=decisions)
    audit_wall = (time.perf_counter() - started) * 1000
    detect_ms = sum(r["wall_ms"] for r in boundary.records[:2])
    localize_ms = audit_wall - detect_ms
    repair_started = time.perf_counter()
    repairs = []
    for index in located:
        chunk = chunks[index]
        response = rpc_retry(cfg["repair"], "eth_getLogs", [{"fromBlock": hex(chunk.start),
            "toBlock": hex(chunk.end), "address": normalize(message["origin_mailbox"]),
            "topics": [DISPATCH_TOPIC]}])
        logs = response.pop("result", None)
        count = len(logs) if isinstance(logs, list) else None
        expected = boundary.nonce(chunk.end) - boundary.nonce(chunk.start - 1)
        repairs.append({"chunk": index, "count": count, "expected": expected,
                        "success": count == expected, **response})
    repair_ms = (time.perf_counter() - repair_started) * 1000
    return {
        "provenance": "saved_natural_failure_trace_replay_live_boundary_repair",
        "chain": failure["chain"], "source_provider": failure["provider"],
        "source_method": failure["method"], "nonce": failure["nonce"], "block": block,
        "source_result_count": failure.get("result_count"), "actual_bad_chunk": bad_index,
        "located_chunks": located, "correctly_localized": located == [bad_index],
        "repair_provider": cfg["repair_name"], "all_repairs_succeeded": all(r["success"] for r in repairs),
        "detect_ms": detect_ms, "localize_ms": localize_ms, "repair_ms": repair_ms,
        "total_ms": detect_ms + localize_ms + repair_ms,
        "boundary_records": boundary.records, "decisions": decisions, "repairs": repairs,
    }


def main() -> None:
    grouped = messages_by_chain()
    prior = [json.loads(line) for line in OUTPUT.read_text().splitlines()] if OUTPUT.exists() else []
    done = {(r["chain"], r["source_provider"], r["source_method"], r["nonce"]) for r in prior}
    for failure in natural_failures():
        key = (failure["chain"], failure["provider"], failure["method"], failure["nonce"])
        if key in done:
            continue
        try:
            record = run(failure, grouped[failure["chain"]])
        except Exception as exc:
            record = {"provenance": "saved_natural_failure_trace_replay_live_boundary_repair",
                      "chain": failure["chain"], "source_provider": failure["provider"],
                      "source_method": failure["method"], "nonce": failure["nonce"],
                      "unavailable": f"{type(exc).__name__}: {exc}"}
        with OUTPUT.open("a") as handle:
            handle.write(json.dumps(record, sort_keys=True) + "\n")
        print(key, "localized", record.get("correctly_localized"), "repair",
              record.get("all_repairs_succeeded"), "total_ms", record.get("total_ms"), flush=True)


if __name__ == "__main__":
    main()
