#!/usr/bin/env python3
"""Pre-submit strengthening: live miss sanity, truncated uniques, fault-path, Wormhole live.

Outputs under data/:
  truncated_unique_stats.json
  live_natural_miss_sanity.jsonl / .json
  fault_path_silent_compare.jsonl / .json
  wormhole_live_boundary.json
"""

from __future__ import annotations

# --- github publish layout (auto-generated by sync_github_publish.py) ---
import sys
from pathlib import Path as _Path
_GITHUB_ROOT = _Path(__file__).resolve().parents[1]
_BG = _GITHUB_ROOT / "BoundaryGuard"
_EXP = _GITHUB_ROOT / "exp"
for _p in (_BG, _EXP):
    _s = str(_p)
    if _s not in sys.path:
        sys.path.insert(0, _s)
DATA = _GITHUB_ROOT.joinpath("data")
EXP = _EXP
ROOT = _GITHUB_ROOT
# --- end header ---

import argparse
import json
import statistics
import time
from collections import Counter, defaultdict
from pathlib import Path

from hyperlane_identity import DISPATCH_TOPIC, normalize, verify_dispatch
from natural_fault_expansion import PROVIDERS
from rpc_probe import rpc
from boundaryguard_scale_gate import NONCE_SELECTOR, rpc_retry

ROOT = _GITHUB_ROOT
DATA = DATA
MESSAGES = DATA / "hyperlane_messages.jsonl"
WORMHOLE_DUMP = DATA / "wormhole_transactions.clean.jsonl.gz"

BOUNDARY = {
    "optimism": "https://optimism.drpc.org",
    "ethereum": "https://eth.drpc.org",
}
REPAIR = {
    "optimism": ("official", "https://mainnet.optimism.io"),
    "ethereum": ("drpc", "https://eth.drpc.org"),
}
DUAL_SECONDARY = {
    "optimism": "https://mainnet.optimism.io",
    "ethereum": "https://0xrpc.io/eth",
}

WH_CORE = {
    "ethereum": "0x98f3c9e6E3fAce36bAAd05FE09d375Ef1464288B",
}
WH_TOPIC = "0x6eb224fb001ed210e379b335e35efe88672a8ce935d981a6896b27ffdf52a3b2"
WH_NEXT_SEQ = "0x4cf842b5"  # nextSequence(address)


def load_messages() -> dict[tuple[str, int], dict]:
    out = {}
    with MESSAGES.open() as handle:
        for line in handle:
            row = json.loads(line)
            out[(row["chain"], int(row["nonce"]))] = row
    return out


def iter_fault_rows() -> list[dict]:
    rows = []
    for name in (
        "natural_fault_expansion.jsonl",
        "natural_fault_multiday.jsonl",
        "natural_fault_targeted.jsonl",
        "hyperlane_ground_truth_audit_10.jsonl",
    ):
        path = DATA / name
        if not path.exists():
            continue
        source = name
        for line in path.open():
            row = json.loads(line)
            row["_source_file"] = source
            rows.append(row)
    return rows


def summarize_truncated(rows: list[dict]) -> dict:
    truncated = [r for r in rows if r.get("failure_class") == "truncated_or_stale_nonempty"]
    empty = [r for r in rows if r.get("failure_class") == "successful_empty"]
    hashes = {r.get("response_sha256") for r in truncated if r.get("response_sha256")}
    cbp = {(r.get("chain"), r.get("block"), r.get("provider")) for r in truncated}
    cbp_method = {(r.get("chain"), r.get("block"), r.get("provider"), r.get("method")) for r in truncated}
    empty_nonces = {(r.get("chain"), r.get("nonce")) for r in empty if r.get("nonce") is not None}
    trunc_nonces = {(r.get("chain"), r.get("nonce")) for r in truncated if r.get("nonce") is not None}
    by_provider = Counter(r.get("provider") for r in truncated)
    by_chain = Counter(r.get("chain") for r in truncated)
    return {
        "provenance": "derived_from_live_natural_observation_jsonl",
        "raw_truncated_or_stale_nonempty": len(truncated),
        "unique_response_sha256": len(hashes),
        "unique_chain_block_provider": len(cbp),
        "unique_chain_block_provider_method": len(cbp_method),
        "unique_chain_nonce": len(trunc_nonces),
        "successful_empty_unique_chain_nonce": len(empty_nonces),
        "overlap_chain_nonce_with_successful_empty": len(trunc_nonces & empty_nonces),
        "by_provider": dict(by_provider),
        "by_chain": dict(by_chain),
        "note": "raw_truncated counts include multi-epoch re-probes; unique_* de-duplicate.",
    }


def build_query(message: dict, method: str) -> tuple[str, list]:
    mailbox = normalize(message["origin_mailbox"])
    block = int(message["origin_block_height"])
    if method.endswith("blockHash") or method == "eth_getLogs:blockHash":
        block_hash = message.get("origin_block_hash") or message.get("block_hash")
        if not block_hash:
            raise RuntimeError("missing block hash")
        return "eth_getLogs", [{"blockHash": block_hash, "address": mailbox, "topics": [DISPATCH_TOPIC]}]
    return "eth_getLogs", [{
        "fromBlock": hex(block), "toBlock": hex(block),
        "address": mailbox, "topics": [DISPATCH_TOPIC],
    }]


def count_dispatches(logs: object, message: dict | None = None) -> dict:
    """Count Mailbox Dispatch logs; optionally check target-message presence."""
    if not isinstance(logs, list):
        return {
            "semantic_match": False,
            "result_count": None,
            "dispatch_count": 0,
            "matching_logs": 0,
            "target_present": False,
        }
    from hyperlane_identity import decode_dynamic_bytes, decode_message

    dispatch_count = 0
    target_present = False
    target_nonce = int(message["nonce"]) if message is not None else None
    for log in logs:
        if not isinstance(log, dict) or not log.get("topics"):
            continue
        if normalize(log["topics"][0]) != DISPATCH_TOPIC:
            continue
        dispatch_count += 1
        if message is None or target_present:
            continue
        try:
            decoded = decode_message(decode_dynamic_bytes(log.get("data", "0x")))
            if target_nonce is not None and int(decoded["nonce"]) == target_nonce:
                target_present = True
        except Exception:
            continue
    return {
        "semantic_match": target_present if message is not None else dispatch_count > 0,
        "result_count": len(logs),
        "dispatch_count": dispatch_count,
        "matching_logs": dispatch_count,
        "target_present": target_present,
    }


def semantic_match(logs: object, message: dict) -> dict:
    return count_dispatches(logs, message)


def read_nonce(url: str, mailbox: str, block: int) -> dict:
    response = rpc_retry(url, "eth_call", [{"to": mailbox, "data": NONCE_SELECTOR}, hex(block)], attempts=3)
    raw = response.pop("result", None)
    value = None
    if response["outcome"] == "ok" and isinstance(raw, str) and len(raw) > 2:
        try:
            value = int(raw, 16)
        except ValueError:
            response["outcome"] = "rpc_error"
    return {"value": value, **response}


def unique_empty_contexts(rows: list[dict], messages: dict) -> list[dict]:
    unique = {}
    for row in rows:
        method = row.get("method") or ""
        if not str(method).startswith("eth_getLogs"):
            continue
        fc = row.get("failure_class")
        is_empty = fc == "successful_empty" or (
            fc is None
            and row.get("outcome") == "ok"
            and row.get("semantic_match") is False
            and (row.get("result_count") in (0, None) or row.get("result_count") == 0)
        )
        # Expansion-era rows: ok + semantic_match false + empty/missing count.
        if row.get("outcome") == "ok" and row.get("semantic_match") is False:
            rc = row.get("result_count")
            if rc == 0 or (rc is None and fc in (None, "successful_empty")):
                is_empty = True
        if not is_empty or row.get("outcome") != "ok":
            continue
        chain, provider = row.get("chain"), row.get("provider")
        if chain not in PROVIDERS or provider not in PROVIDERS.get(chain, {}):
            continue
        if row.get("nonce") is None or row.get("block") is None:
            continue
        key = (chain, provider, method, row.get("block"), row.get("nonce"))
        message = messages.get((chain, int(row["nonce"])))
        if not message:
            continue
        unique[key] = {
            "chain": chain,
            "provider": provider,
            "method": method,
            "block": int(row["block"]),
            "nonce": int(row["nonce"]),
            "message": message,
            "primary_url": PROVIDERS[chain][provider],
        }
    ordered = sorted(unique.values(), key=lambda r: (r["chain"], r["provider"], r["nonce"]))
    return ordered


def unique_truncated_contexts(rows: list[dict], messages: dict, limit: int = 12) -> list[dict]:
    unique = {}
    for row in rows:
        if row.get("failure_class") != "truncated_or_stale_nonempty" or row.get("outcome") != "ok":
            continue
        method = row.get("method") or ""
        if not str(method).startswith("eth_getLogs"):
            continue
        chain, provider = row.get("chain"), row.get("provider")
        if chain not in BOUNDARY or chain not in PROVIDERS or provider not in PROVIDERS.get(chain, {}):
            continue
        key = (chain, provider, method, row.get("block"), row.get("nonce"))
        message = messages.get((chain, int(row["nonce"]))) if row.get("nonce") is not None else None
        if not message:
            continue
        unique[key] = {
            "chain": chain,
            "provider": provider,
            "method": method,
            "block": int(row["block"]),
            "nonce": int(row["nonce"]),
            "message": message,
            "primary_url": PROVIDERS[chain][provider],
            "saved_result_count": row.get("result_count"),
        }
    return sorted(unique.values(), key=lambda r: (r["chain"], r["nonce"]))[:limit]


def run_modes_on_context(
    ctx: dict,
    timeout: float = 15.0,
    primary_policy: str = "auto",
) -> dict:
    """Fault-path compare on one known silent context.

    primary_policy:
      auto — use live incomplete if still present, else saved empty body
      saved_empty — always use saved successful-empty body
      live_only — never substitute saved empty (for truncated live detect)
    """
    chain = ctx["chain"]
    message = ctx["message"]
    mailbox = normalize(message["origin_mailbox"])
    block = int(message["origin_block_height"])
    # Observe with the original method form; repair/dual always use single-block
    # ranges so archive providers are not blocked on missing blockHash support.
    obs_method, obs_params = build_query(message, ctx["method"])
    repair_method, repair_params = build_query(message, "eth_getLogs:singleBlock")
    repair_name, repair_url = REPAIR[chain]
    boundary_url = BOUNDARY[chain]
    dual_url = DUAL_SECONDARY[chain]

    t0 = time.perf_counter()
    primary = rpc(ctx["primary_url"], obs_method, obs_params, timeout)
    primary_live_ms = (time.perf_counter() - t0) * 1000
    live_logs = primary.get("result") if primary.get("outcome") == "ok" else None
    live_sem = semantic_match(live_logs, message)

    t1 = time.perf_counter()
    before = read_nonce(boundary_url, mailbox, block - 1)
    after = read_nonce(boundary_url, mailbox, block)
    boundary_ms = (time.perf_counter() - t1) * 1000
    boundary_ok = before.get("value") is not None and after.get("value") is not None
    expected = (after["value"] - before["value"]) if boundary_ok else None

    live_incomplete = bool(
        primary.get("outcome") == "ok"
        and expected is not None
        and expected > 0
        and (
            (live_sem.get("dispatch_count") or 0) < expected
            or not live_sem.get("target_present")
        )
    )

    if primary_policy == "live_only":
        primary_logs = live_logs if isinstance(live_logs, list) else []
        primary_ms = primary_live_ms
        primary_mode = "live_primary"
        primary_outcome = primary.get("outcome") or "error"
    elif primary_policy == "saved_empty" or (primary_policy == "auto" and not live_incomplete):
        primary_logs = []
        primary_ms = 0.0
        primary_mode = "saved_natural_empty_body"
        primary_outcome = "ok"
    else:
        primary_logs = live_logs if isinstance(live_logs, list) else []
        primary_ms = primary_live_ms
        primary_mode = "live_natural_incomplete"
        primary_outcome = "ok"

    primary_sem = semantic_match(primary_logs, message)

    t2 = time.perf_counter()
    secondary = rpc(dual_url, repair_method, repair_params, timeout)
    dual_ms = (time.perf_counter() - t2) * 1000
    sec_logs = secondary.get("result") if secondary.get("outcome") == "ok" else None
    sec_sem = semantic_match(sec_logs, message)
    dual_target = bool(primary_sem.get("target_present") or sec_sem.get("target_present"))
    dual = {
        "completed": dual_target,
        "silent_miss": primary_outcome == "ok" and secondary.get("outcome") == "ok" and not dual_target,
        "fail_closed": primary_outcome != "ok" and secondary.get("outcome") != "ok",
        "requests": 2,
        "matching_logs": max(primary_sem.get("dispatch_count") or 0, sec_sem.get("dispatch_count") or 0),
        "primary_matching": primary_sem.get("dispatch_count"),
        "secondary_matching": sec_sem.get("dispatch_count"),
        "dual_query_ms": dual_ms,
        "secondary_outcome": secondary.get("outcome"),
    }
    unchecked = {
        "completed": primary_outcome == "ok" and bool(primary_sem.get("target_present")),
        "silent_miss": primary_outcome == "ok" and not primary_sem.get("target_present"),
        "fail_closed": primary_outcome != "ok",
        "requests": 1,
        "matching_logs": primary_sem.get("dispatch_count"),
        "result_count": primary_sem.get("result_count"),
    }

    bg_path_requests = 0
    repair_ms = 0.0
    bg_fail_closed = False
    bg_completed = False
    final_matching = primary_sem.get("dispatch_count")
    incomplete = True
    total_path_ms = primary_ms + boundary_ms
    repair_outcome = None

    if not boundary_ok:
        bg_fail_closed = True
        bg_path_requests = 2
    else:
        bg_path_requests = 1 + 2
        primary_dispatches = primary_sem.get("dispatch_count") or 0
        incomplete = (expected or 0) > 0 and (
            primary_dispatches < (expected or 0) or not primary_sem.get("target_present")
        )
        if not incomplete and primary_sem.get("target_present"):
            bg_completed = True
        else:
            t3 = time.perf_counter()
            repaired = rpc_retry(repair_url, repair_method, repair_params, attempts=3)
            repair_ms = (time.perf_counter() - t3) * 1000
            bg_path_requests += 1
            repair_outcome = repaired.get("outcome")
            rlogs = repaired.get("result") if repaired.get("outcome") == "ok" else None
            repair_sem = semantic_match(rlogs, message)
            final_matching = repair_sem.get("dispatch_count")
            repair_dispatches = repair_sem.get("dispatch_count") or 0
            if repaired.get("outcome") != "ok":
                bg_fail_closed = True
            elif expected is not None and repair_dispatches < expected:
                bg_fail_closed = True
            elif repair_sem.get("target_present") and repair_dispatches >= expected:
                bg_completed = True
            else:
                bg_fail_closed = True
            total_path_ms = primary_ms + boundary_ms + repair_ms

    bg = {
        "completed": bg_completed,
        "silent_miss": False,
        "fail_closed": bg_fail_closed,
        "requests": bg_path_requests,
        "matching_logs": final_matching,
        "detect_ms": boundary_ms,
        "repair_ms": repair_ms,
        "total_path_ms": total_path_ms,
        "repair_provider": repair_name,
        "repair_outcome": repair_outcome,
        "expected_delta": expected,
        "repaired": incomplete and bg_completed,
    }

    return {
        "provenance": primary_mode + "_live_boundary_repair",
        "chain": chain,
        "provider": ctx["provider"],
        "method": ctx["method"],
        "block": block,
        "nonce": ctx["nonce"],
        "primary_mode": primary_mode,
        "live_primary_still_incomplete": live_incomplete,
        "live_primary_outcome": primary.get("outcome"),
        "primary_outcome": primary_outcome,
        "primary_matching_logs": primary_sem.get("dispatch_count"),
        "primary_result_count": primary_sem.get("result_count"),
        "boundary_ok": boundary_ok,
        "expected_delta": expected,
        "primary_ms": primary_ms,
        "live_primary_ms": primary_live_ms,
        "modes": {"unchecked": unchecked, "always_dual": dual, "boundaryguard": bg},
    }


def wormhole_next_sequence(url: str, core: str, emitter: str, block: int | str) -> dict:
    data = WH_NEXT_SEQ + normalize(emitter).removeprefix("0x").zfill(64)
    response = rpc_retry(url, "eth_call", [{"to": core, "data": data}, block if isinstance(block, str) else hex(block)], attempts=3)
    raw = response.pop("result", None)
    value = None
    if response["outcome"] == "ok" and isinstance(raw, str) and len(raw) > 2:
        try:
            value = int(raw, 16)
        except ValueError:
            response["outcome"] = "rpc_error"
    return {"value": value, **response}


def pick_wormhole_emitters(limit: int = 4) -> list[str]:
    import gzip

    counts: Counter[str] = Counter()
    if not WORMHOLE_DUMP.exists():
        return []
    with gzip.open(WORMHOLE_DUMP, "rt") as handle:
        for line in handle:
            row = json.loads(line)
            # emitter field formats vary; prefer explicit emitter address on ethereum
            emitter = row.get("emitterAddress") or row.get("emitter") or row.get("sourceAddress")
            chain = str(row.get("emitterChain") or row.get("sourceChain") or row.get("chain") or "")
            if emitter and ("2" in chain or chain.lower() in {"ethereum", "eth", "2"}):
                # wormhole emitter often bytes32; take last 20 bytes if long
                text = normalize(str(emitter))
                if len(text) >= 42:
                    text = "0x" + text[-40:]
                counts[text.lower()] += 1
            if sum(counts.values()) > 20000:
                break
    return [e for e, _ in counts.most_common(limit)]


def run_wormhole_live(n_windows: int = 16) -> dict:
    url = "https://eth.drpc.org"
    core = WH_CORE["ethereum"]
    tip_resp = rpc(url, "eth_blockNumber", [], 12.0)
    if tip_resp.get("outcome") != "ok":
        return {"ok": False, "error": tip_resp}
    tip = int(tip_resp["result"], 16)
    emitters = ["0x3ee18B2214AFF97000D974cf647E7C347E8fa585"]  # Token Bridge
    width = 200
    cases = []
    matches = 0
    readable = 0
    for i in range(n_windows):
        emitter = emitters[i % len(emitters)]
        end = tip - 64 - i * (width + 50)
        start = end - width + 1
        if start <= 0:
            break
        print(f"  wormhole window {i+1}/{n_windows} [{start},{end}]", flush=True)
        t0 = time.perf_counter()
        before = wormhole_next_sequence(url, core, emitter, start - 1)
        after = wormhole_next_sequence(url, core, emitter, end)
        boundary_ms = (time.perf_counter() - t0) * 1000
        if before.get("value") is None or after.get("value") is None:
            cases.append({
                "emitter": emitter, "start": start, "end": end,
                "boundary_ok": False, "boundary_ms": boundary_ms,
                "before": before.get("outcome"), "after": after.get("outcome"),
            })
            continue
        readable += 1
        expected = after["value"] - before["value"]
        topic1 = "0x" + normalize(emitter).removeprefix("0x").zfill(64)
        t1 = time.perf_counter()
        logs_resp = rpc(
            url,
            "eth_getLogs",
            [{
                "fromBlock": hex(start),
                "toBlock": hex(end),
                "address": core,
                "topics": [WH_TOPIC, topic1],
            }],
            20.0,
        )
        logs_ms = (time.perf_counter() - t1) * 1000
        logs = logs_resp.get("result") if logs_resp.get("outcome") == "ok" else None
        count = len(logs) if isinstance(logs, list) else None
        ok = count is not None and count == expected
        if ok:
            matches += 1
        cases.append({
            "emitter": emitter,
            "start": start,
            "end": end,
            "boundary_ok": True,
            "expected_delta": expected,
            "log_count": count,
            "prefix_match": ok,
            "detects_empty_omission": expected > 0,
            "boundary_ms": boundary_ms,
            "logs_ms": logs_ms,
            "logs_outcome": logs_resp.get("outcome"),
        })
        time.sleep(0.05)
    return {
        "provenance": "live_natural_observation",
        "protocol": "wormhole_core_nextSequence",
        "chain": "ethereum",
        "rpc": url,
        "core": core,
        "windows": len(cases),
        "boundary_readable": readable,
        "prefix_matches": matches,
        "prefix_match_rate_of_readable": (matches / readable) if readable else None,
        "emitters": emitters,
        "cases": cases,
        "claim": "Monotone nextSequence boundary is live-readable and matches LogMessagePublished counts when RPC logs are complete; empty omission against a positive delta is detectable.",
    }


def percentile(values: list[float], p: float) -> float | None:
    if not values:
        return None
    ordered = sorted(values)
    if len(ordered) == 1:
        return ordered[0]
    idx = min(len(ordered) - 1, max(0, int(round((p / 100.0) * (len(ordered) - 1)))))
    return ordered[idx]


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--live-limit", type=int, default=10)
    parser.add_argument("--truncated-detect-limit", type=int, default=8)
    parser.add_argument("--wormhole-windows", type=int, default=24)
    parser.add_argument("--skip-live", action="store_true")
    parser.add_argument("--skip-wormhole", action="store_true")
    args = parser.parse_args()

    rows = iter_fault_rows()
    messages = load_messages()

    truncated_stats = summarize_truncated(rows)
    (DATA / "truncated_unique_stats.json").write_text(json.dumps(truncated_stats, indent=2) + "\n")
    print("truncated_unique_stats:", json.dumps({k: truncated_stats[k] for k in (
        "raw_truncated_or_stale_nonempty", "unique_response_sha256",
        "unique_chain_block_provider", "overlap_chain_nonce_with_successful_empty",
    )}))

    live_records = []
    truncated_detect = []
    if not args.skip_live:
        all_ctx = unique_empty_contexts(rows, messages)
        # Prefer one method per (chain, provider, nonce) for an 8–10 window sanity band.
        picked = []
        seen_keys = set()
        for ctx in all_ctx:
            key = (ctx["chain"], ctx["provider"], ctx["nonce"])
            if key in seen_keys:
                continue
            seen_keys.add(key)
            picked.append(ctx)
            if len(picked) >= args.live_limit:
                break
        print(f"sanity-band contexts: {len(picked)}", flush=True)
        out_live = DATA / "live_natural_miss_sanity.jsonl"
        out_fault = DATA / "fault_path_silent_compare.jsonl"
        out_live.write_text("")
        out_fault.write_text("")
        for ctx in picked:
            try:
                record = run_modes_on_context(ctx, primary_policy="saved_empty")
            except Exception as exc:  # noqa: BLE001
                record = {
                    "provenance": "saved_natural_empty_body_live_boundary_repair",
                    "chain": ctx["chain"], "provider": ctx["provider"],
                    "method": ctx["method"], "block": ctx["block"], "nonce": ctx["nonce"],
                    "error": str(exc), "live_primary_still_incomplete": False,
                }
            live_records.append(record)
            with out_live.open("a") as handle:
                handle.write(json.dumps(record) + "\n")
            with out_fault.open("a") as handle:
                handle.write(json.dumps(record) + "\n")
            bg = (record.get("modes") or {}).get("boundaryguard", {})
            print(
                f"  {ctx['chain']}/{ctx['provider']} nonce={ctx['nonce']} "
                f"bg_ok={bg.get('completed')} fail_closed={bg.get('fail_closed')} "
                f"total_ms={bg.get('total_path_ms')} live_still={record.get('live_primary_still_incomplete')}",
                flush=True,
            )
            time.sleep(0.05)

        for ctx in unique_truncated_contexts(rows, messages, args.truncated_detect_limit):
            try:
                record = run_modes_on_context(ctx, primary_policy="live_only")
                outcome = record.get("live_primary_outcome")
                result_count = record.get("primary_result_count")
                expected = record.get("expected_delta")
                target_present = bool(
                    record.get("modes", {}).get("unchecked", {}).get("completed")
                )
                if outcome != "ok":
                    reprobe_class = "explicit_error"
                elif isinstance(result_count, int) and result_count > 0 and not target_present:
                    reprobe_class = "persistent_nonempty_target_omission"
                elif target_present:
                    reprobe_class = "complete"
                else:
                    reprobe_class = "successful_empty_or_unclassified"
                detected_persistent = bool(
                    reprobe_class == "persistent_nonempty_target_omission"
                    and record.get("boundary_ok")
                    and expected is not None
                    and expected > 0
                )
                truncated_detect.append({
                    "chain": ctx["chain"], "provider": ctx["provider"], "method": ctx["method"],
                    "block": ctx["block"], "nonce": ctx["nonce"],
                    "saved_result_count": ctx.get("saved_result_count"),
                    "live_result_count": result_count,
                    "live_primary_matching": record.get("primary_matching_logs"),
                    "live_primary_outcome": outcome,
                    "expected_delta": expected,
                    "reprobe_class": reprobe_class,
                    "bg_detects_persistent_nonempty_omission": detected_persistent,
                    "bg_completed": record.get("modes", {}).get("boundaryguard", {}).get("completed"),
                    "bg_fail_closed": record.get("modes", {}).get("boundaryguard", {}).get("fail_closed"),
                })
                print(
                    f"  nonempty-omission reprobe {ctx['chain']}/{ctx['provider']} "
                    f"nonce={ctx['nonce']} class={reprobe_class}",
                    flush=True,
                )
            except Exception as exc:  # noqa: BLE001
                truncated_detect.append({"chain": ctx["chain"], "nonce": ctx["nonce"], "error": str(exc)})
            time.sleep(0.05)

    usable = [r for r in live_records if "modes" in r]
    still = [r for r in usable if r.get("live_primary_still_incomplete")]
    totals = [
        r["modes"]["boundaryguard"]["total_path_ms"]
        for r in usable
        if r["modes"]["boundaryguard"].get("total_path_ms") is not None
        and r["modes"]["boundaryguard"].get("completed")
    ]
    mode_summary = {}
    for mode in ("unchecked", "always_dual", "boundaryguard"):
        subset = [r["modes"][mode] for r in usable]
        if not subset:
            mode_summary[mode] = {"n": 0}
            continue
        mode_summary[mode] = {
            "n": len(subset),
            "completed": sum(1 for m in subset if m.get("completed")),
            "silent_miss": sum(1 for m in subset if m.get("silent_miss")),
            "fail_closed": sum(1 for m in subset if m.get("fail_closed")),
            "mean_requests": statistics.mean(m["requests"] for m in subset),
        }

    live_summary = {
        "provenance": "saved_natural_empty_body_live_boundary_repair",
        "note": "Single-block windows: natural successful-empty body + live boundary/repair; no canonical surround. Live primary still-incomplete counted separately when providers still omit.",
        "attempted_contexts": len(live_records),
        "usable_contexts": len(usable),
        "still_incomplete_live": len(still),
        "bg_completed": mode_summary.get("boundaryguard", {}).get("completed", 0),
        "bg_fail_closed": mode_summary.get("boundaryguard", {}).get("fail_closed", 0),
        "post_primary_audit_repair_ms_completed": {
            "n": len(totals),
            "p50": percentile(totals, 50),
            "p95": percentile(totals, 95),
            "mean": statistics.mean(totals) if totals else None,
        },
        "fault_path_modes": mode_summary,
        "saved_nonempty_omission_reprobe": {
            "n": len(truncated_detect),
            "persistent_nonempty_target_omission": sum(
                1 for r in truncated_detect
                if r.get("reprobe_class") == "persistent_nonempty_target_omission"
            ),
            "explicit_error": sum(
                1 for r in truncated_detect if r.get("reprobe_class") == "explicit_error"
            ),
            "complete": sum(
                1 for r in truncated_detect if r.get("reprobe_class") == "complete"
            ),
            "cases": truncated_detect,
        },
        "claim": "Preserved natural empty body with live boundary and repair; latency excludes the original primary response.",
    }
    (DATA / "live_natural_miss_sanity.json").write_text(json.dumps(live_summary, indent=2) + "\n")
    (DATA / "fault_path_silent_compare.json").write_text(json.dumps({
        "provenance": live_summary["provenance"],
        "on_saved_empty_windows": mode_summary,
        "n": len(usable),
        "cases": usable,
    }, indent=2) + "\n")
    truncated_stats["saved_context_reprobe"] = live_summary["saved_nonempty_omission_reprobe"]
    (DATA / "truncated_unique_stats.json").write_text(json.dumps(truncated_stats, indent=2) + "\n")
    print("live_summary:", json.dumps({k: live_summary[k] for k in (
        "attempted_contexts", "usable_contexts", "still_incomplete_live", "bg_completed",
        "bg_fail_closed", "post_primary_audit_repair_ms_completed", "fault_path_modes",
    )}, indent=2), flush=True)

    if not args.skip_wormhole:
        wh = run_wormhole_live(args.wormhole_windows)
        (DATA / "wormhole_live_boundary.json").write_text(json.dumps(wh, indent=2) + "\n")
        print("wormhole_live:", json.dumps({
            "windows": wh.get("windows"),
            "boundary_readable": wh.get("boundary_readable"),
            "prefix_matches": wh.get("prefix_matches"),
            "prefix_match_rate_of_readable": wh.get("prefix_match_rate_of_readable"),
        }, indent=2), flush=True)


if __name__ == "__main__":
    main()
