#!/usr/bin/env python3
"""Capability-specific provider degradation and trace evaluation."""

from __future__ import annotations

# --- github publish layout (auto-generated by sync_github_publish.py) ---
import sys
from pathlib import Path as _Path
_GITHUB_ROOT = _Path(__file__).resolve().parents[1]
_BG = _GITHUB_ROOT / "BoundaryGuard"
_EXP = _GITHUB_ROOT / "exp"
for _p in (_BG, _EXP):
    _s = str(_p)
    if _s not in sys.path:
        sys.path.insert(0, _s)
DATA = _GITHUB_ROOT.joinpath("data")
EXP = _EXP
ROOT = _GITHUB_ROOT
# --- end header ---

import argparse
import json
from collections import defaultdict, deque
from dataclasses import dataclass, field
from pathlib import Path


@dataclass
class ProviderState:
    name: str
    status: str = "healthy"
    cooldown_left: int = 0
    canary_successes: int = 0
    recent_explicit: deque = field(default_factory=lambda: deque(maxlen=5))
    demotions: int = 0

    def observe(self, outcome: str, semantic_match: bool) -> None:
        explicit = outcome != "ok"
        self.recent_explicit.append(explicit)
        if outcome == "ok" and not semantic_match:
            self.status, self.cooldown_left, self.canary_successes = "quarantined", 20, 0
            self.demotions += 1
        elif sum(self.recent_explicit) >= 3:
            self.status, self.cooldown_left, self.canary_successes = "quarantined", 10, 0
            self.demotions += 1
        elif self.status == "probation":
            if outcome == "ok" and semantic_match:
                self.canary_successes += 1
                if self.canary_successes >= 3:
                    self.status = "healthy"
            else:
                self.status, self.cooldown_left, self.canary_successes = "quarantined", 20, 0

    def tick(self) -> None:
        if self.status == "quarantined":
            self.cooldown_left -= 1
            if self.cooldown_left <= 0:
                self.status, self.canary_successes = "probation", 0


class CapabilityRouter:
    """State is per (chain, RPC method), preventing global over-demotion."""

    def __init__(self, providers: list[str]):
        self.states = {name: ProviderState(name) for name in providers}

    def choose(self, exclude: set[str] | None = None) -> str | None:
        exclude = exclude or set()
        candidates = [s for s in self.states.values() if s.name not in exclude and s.status == "healthy"]
        if not candidates:
            candidates = [s for s in self.states.values() if s.name not in exclude and s.status == "probation"]
        return candidates[0].name if candidates else None

    def tick(self) -> None:
        for state in self.states.values():
            state.tick()


def load_records(path: Path) -> list[dict]:
    return [json.loads(line) for line in path.read_text().splitlines() if line.strip()]


def evaluate(records: list[dict]) -> dict:
    grouped: dict[tuple, dict[str, dict]] = defaultdict(dict)
    for row in records:
        grouped[(row["chain"], row["nonce"], row["method"])][row["provider"]] = row
    stats = defaultdict(int)
    baselines = defaultdict(lambda: defaultdict(int))
    per_capability = {}
    for capability in sorted({(r["chain"], r["method"]) for r in records}):
        chain, method = capability
        providers = sorted({r["provider"] for r in records if (r["chain"], r["method"]) == capability})
        router = CapabilityRouter(providers)
        keys = sorted((k for k in grouped if (k[0], k[2]) == capability), key=lambda k: k[1])
        provider_successes = {
            p: sum(grouped[k].get(p, {}).get("outcome") == "ok"
                   and grouped[k].get(p, {}).get("semantic_match", False) for k in keys)
            for p in providers
        }
        best_static = max(providers, key=lambda p: (provider_successes[p], -providers.index(p)))
        for key in keys:
            def valid(provider: str) -> bool:
                row = grouped[key].get(provider, {})
                return row.get("outcome") == "ok" and row.get("semantic_match", False)
            first = providers[0]
            baselines["fixed_first"]["operations"] += 1
            baselines["fixed_first"]["queries"] += 1
            baselines["fixed_first"]["delivered"] += int(valid(first))
            baselines["hindsight_best_static"]["operations"] += 1
            baselines["hindsight_best_static"]["queries"] += 1
            baselines["hindsight_best_static"]["delivered"] += int(valid(best_static))
            dual = providers[:2]
            baselines["always_dual"]["operations"] += 1
            baselines["always_dual"]["queries"] += len(dual)
            baselines["always_dual"]["delivered"] += int(any(valid(p) for p in dual))
            router.tick()
            probation = next((s.name for s in router.states.values() if s.status == "probation"
                              and s.name in grouped[key]), None)
            if probation is not None:
                canary = grouped[key][probation]
                stats["canary_queries"] += 1
                router.states[probation].observe(canary["outcome"], canary.get("semantic_match", False))
            chosen = router.choose()
            if chosen is None or chosen not in grouped[key]:
                stats["unavailable"] += 1
                continue
            row = grouped[key][chosen]
            stats["primary_queries"] += 1
            ok = row["outcome"] == "ok" and row.get("semantic_match", False)
            router.states[chosen].observe(row["outcome"], row.get("semantic_match", False))
            if not ok:
                stats["primary_failures"] += 1
                fallback = router.choose(exclude={chosen})
                if fallback is not None and fallback in grouped[key]:
                    stats["fallback_queries"] += 1
                    alt = grouped[key][fallback]
                    if alt["outcome"] == "ok" and alt.get("semantic_match", False):
                        stats["recovered"] += 1
                    else:
                        stats["unrecovered"] += 1
                else:
                    stats["unrecovered"] += 1
        per_capability[f"{chain}:{method}"] = {
            name: {"status": state.status, "demotions": state.demotions}
            for name, state in router.states.items()
        }
    total = stats["primary_queries"]
    baseline_results = {}
    for name, values in baselines.items():
        baseline_results[name] = dict(values)
        baseline_results[name]["delivery_rate"] = values["delivered"] / values["operations"]
    adaptive_delivered = stats["primary_queries"] - stats["primary_failures"] + stats["recovered"]
    adaptive_queries = stats["primary_queries"] + stats["fallback_queries"] + stats["canary_queries"]
    baseline_results["capability_aware_failover"] = {
        "operations": stats["primary_queries"] + stats["unavailable"], "queries": adaptive_queries,
        "delivered": adaptive_delivered,
        "delivery_rate": adaptive_delivered / (stats["primary_queries"] + stats["unavailable"])
        if stats["primary_queries"] + stats["unavailable"] else None,
    }
    return {
        "policy": {"semantic_mismatch": "immediate 20-batch quarantine",
                   "explicit_error": "3-of-5 then 10-batch quarantine",
                   "recovery": "3 successful probation canaries",
                   "scope": "per-chain, per-method capability"},
        "records": len(records), "operations": len(grouped), **stats,
        "primary_failure_rate": stats["primary_failures"] / total if total else None,
        "recovery_rate": stats["recovered"] / stats["primary_failures"] if stats["primary_failures"] else None,
        "baselines": baseline_results,
        "final_states": per_capability,
    }


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--input", type=Path, default=Path("data/natural_fault_expansion.jsonl"))
    parser.add_argument("--output", type=Path, default=Path("data/provider_failover_summary.json"))
    args = parser.parse_args()
    result = evaluate(load_records(args.input))
    args.output.write_text(json.dumps(result, indent=2, sort_keys=True) + "\n")
    print(json.dumps(result, indent=2, sort_keys=True))


if __name__ == "__main__":
    main()
