#!/usr/bin/env python3
"""Measure a semantic archive frontier using verified Ethereum messages."""

from __future__ import annotations

# --- github publish layout (auto-generated by sync_github_publish.py) ---
import sys
from pathlib import Path as _Path
_GITHUB_ROOT = _Path(__file__).resolve().parents[1]
_BG = _GITHUB_ROOT / "BoundaryGuard"
_EXP = _GITHUB_ROOT / "exp"
for _p in (_BG, _EXP):
    _s = str(_p)
    if _s not in sys.path:
        sys.path.insert(0, _s)
DATA = _GITHUB_ROOT.joinpath("data")
EXP = _EXP
ROOT = _GITHUB_ROOT
# --- end header ---

import json
import time
from pathlib import Path

from audit_hyperlane_ground_truth import rpc
from hyperlane_identity import DISPATCH_TOPIC, normalize, verify_dispatch


PROVIDERS = {"flashbots": "https://rpc.flashbots.net", "zeroxrpc": "https://0xrpc.io/eth"}
OUTPUT = Path("data/provider_frontier_probe.jsonl")


def samples(count: int = 32) -> list[dict]:
    rows = [json.loads(line) for line in Path("data/hyperlane_messages.jsonl").read_text().splitlines()]
    rows = sorted((r for r in rows if r["chain"] == "ethereum"), key=lambda r: r["origin_block_height"])
    return [rows[round(i * (len(rows)-1) / (count-1))] for i in range(count)]


def semantics(logs: object, expected: dict) -> bool:
    return isinstance(logs, list) and any(isinstance(log, dict) and verify_dispatch(log, expected)["valid"] for log in logs)


def main() -> None:
    prior = [json.loads(line) for line in OUTPUT.read_text().splitlines()] if OUTPUT.exists() else []
    done = {(r["nonce"], r["provider"], r["method"]) for r in prior}
    for message in samples():
        block, block_hash = message["origin_block_height"], normalize(message["origin_block_hash"])
        mailbox = normalize(message["origin_mailbox"])
        methods = {
            "blockHash": [{"blockHash": block_hash, "address": mailbox, "topics": [DISPATCH_TOPIC]}],
            "singleBlock": [{"fromBlock": hex(block), "toBlock": hex(block), "address": mailbox,
                             "topics": [DISPATCH_TOPIC]}],
        }
        for provider, url in PROVIDERS.items():
            for method, params in methods.items():
                if (message["nonce"], provider, method) in done:
                    continue
                response = rpc(url, "eth_getLogs", params, 12)
                logs = response.pop("result", None)
                valid = semantics(logs, message)
                record = {"provenance": "live_natural_observation", "observed_at": time.time(),
                          "chain": "ethereum", "nonce": message["nonce"], "block": block,
                          "provider": provider, "method": method, "outcome": response["outcome"],
                          "semantic_match": valid, "result_count": len(logs) if isinstance(logs, list) else None,
                          **response}
                with OUTPUT.open("a") as handle:
                    handle.write(json.dumps(record, sort_keys=True) + "\n")
                print(block, provider, method, response["outcome"], valid, flush=True)
                time.sleep(0.04)


if __name__ == "__main__":
    main()
