#!/usr/bin/env python3
"""Trace-based 2-of-3 quorum baseline on Gate-2 natural-fault replies.

Offline analytic comparison: no live RPCs. For each (epoch, chain, method,
nonce, block) group, a configured three-provider quorum is replayed from
saved replies and compared with always-dual and a protocol-state check.

Quorum policy (Hyperlane-style majority of successful bodies):
  accept the value shared by at least two of the three configured providers;
  disagreement or fewer than two successful replies is not a silent accept.

Completeness is judged against the Gate-2 semantic_match label for known
dispatched messages. Replica agreement on an incomplete body is a silent miss.
"""

from __future__ import annotations

# --- github publish layout (auto-generated by sync_github_publish.py) ---
import sys
from pathlib import Path as _Path
_GITHUB_ROOT = _Path(__file__).resolve().parents[1]
_BG = _GITHUB_ROOT / "BoundaryGuard"
_EXP = _GITHUB_ROOT / "exp"
for _p in (_BG, _EXP):
    _s = str(_p)
    if _s not in sys.path:
        sys.path.insert(0, _s)
DATA = _GITHUB_ROOT.joinpath("data")
EXP = _EXP
ROOT = _GITHUB_ROOT
# --- end header ---

import json
from collections import Counter, defaultdict
from datetime import datetime, timezone
from pathlib import Path


ROOT = _GITHUB_ROOT
INP = DATA / "natural_fault_multiday.jsonl"
OUT = DATA / "quorum_trace_baseline.json"
# Submission freeze: omit the UTC calendar day that coincides with
# manuscript submission. Replay remains offline on saved traces.
EXCLUDE_UTC_DATES = {"2026-08-19"}

# Same provider maps as natural_fault_multiday.py; first three names are the
# configured 2-of-3 set (deterministic, not a live Hyperlane agent config).
PROVIDERS = {
    "ethereum": ["1rpc", "publicnode", "drpc", "llamarpc", "flashbots", "zeroxrpc", "cloudflare"],
    "arbitrum": ["1rpc", "publicnode", "drpc", "official"],
    "optimism": ["1rpc", "official", "drpc", "nodies"],
    "polygon": ["1rpc", "tenderly", "drpc", "quicknode", "llamarpc"],
}

INCOMPLETE = {"successful_empty", "truncated_or_stale_nonempty"}


def load_rows(path: Path) -> list[dict]:
    rows = []
    with path.open() as handle:
        for line in handle:
            line = line.strip()
            if not line:
                continue
            try:
                row = json.loads(line)
            except json.JSONDecodeError:
                continue
            ts = row.get("observed_at")
            if isinstance(ts, (int, float)):
                day = datetime.fromtimestamp(ts, timezone.utc).date().isoformat()
                if day in EXCLUDE_UTC_DATES:
                    continue
            rows.append(row)
    return rows


def body_key(row: dict) -> tuple:
    sha = row.get("response_sha256")
    if sha:
        return ("sha", sha)
    return ("count_class", row.get("result_count"), row.get("failure_class"))


def quorum_decision(members: list[dict]) -> dict:
    successful = [r for r in members if r.get("outcome") == "ok"]
    if len(successful) < 2:
        return {
            "decision": "unavailable",
            "agreed_class": None,
            "agreed_semantic_match": None,
            "successful": len(successful),
        }
    votes = Counter(body_key(r) for r in successful)
    top_key, top_n = votes.most_common(1)[0]
    if top_n < 2:
        return {
            "decision": "disagreement",
            "agreed_class": None,
            "agreed_semantic_match": None,
            "successful": len(successful),
        }
    winners = [r for r in successful if body_key(r) == top_key]
    cls = winners[0].get("failure_class")
    match = bool(winners[0].get("semantic_match"))
    if cls in INCOMPLETE or match is False:
        decision = "silent_incomplete"
    else:
        decision = "accept_complete"
    return {
        "decision": decision,
        "agreed_class": cls,
        "agreed_semantic_match": match,
        "successful": len(successful),
        "majority_size": top_n,
    }


def dual_decision(a: dict | None, b: dict | None) -> str:
    """Larger-of-two-log-sets always-dual; silent if both successful and incomplete."""
    if a is None or b is None:
        return "unavailable"
    ok_a = a.get("outcome") == "ok"
    ok_b = b.get("outcome") == "ok"
    if not ok_a and not ok_b:
        return "unavailable"
    if ok_a and not ok_b:
        return "complete" if a.get("semantic_match") else "silent_incomplete"
    if ok_b and not ok_a:
        return "complete" if b.get("semantic_match") else "silent_incomplete"
    # both ok: union/max count; if both incomplete, silent miss
    if a.get("semantic_match") or b.get("semantic_match"):
        return "complete"
    if a.get("failure_class") in INCOMPLETE and b.get("failure_class") in INCOMPLETE:
        return "silent_incomplete"
    return "complete" if (a.get("semantic_match") or b.get("semantic_match")) else "silent_incomplete"


def bg_detects(primary: dict | None) -> str:
    """Protocol-state audit: incomplete successful primary is detected."""
    if primary is None or primary.get("outcome") != "ok":
        return "unavailable_or_explicit"
    if primary.get("semantic_match"):
        return "accept_complete"
    if primary.get("failure_class") in INCOMPLETE:
        return "detect_incomplete"
    return "accept_complete" if primary.get("semantic_match") else "detect_incomplete"


def main() -> None:
    rows = load_rows(INP)
    grouped: dict[tuple, dict[str, dict]] = defaultdict(dict)
    for row in rows:
        if not str(row.get("method", "")).startswith("eth_getLogs"):
            continue
        key = (
            int(row.get("epoch") or 0),
            row.get("chain"),
            row.get("method"),
            row.get("nonce"),
            row.get("block"),
        )
        grouped[key][row["provider"]] = row

    outcomes = Counter()
    dual_outcomes = Counter()
    bg_outcomes = Counter()
    silent_classes = Counter()
    all_three_incomplete = 0
    two_agree_empty = 0
    by_chain = defaultdict(Counter)
    silent_examples = []
    evaluable = 0
    for key, by_provider in grouped.items():
        epoch, chain, method, nonce, block = key
        names = PROVIDERS.get(chain) or []
        if len(names) < 3:
            continue
        qset = names[:3]
        if any(name not in by_provider for name in qset):
            continue
        members = [by_provider[name] for name in qset]
        evaluable += 1
        q = quorum_decision(members)
        outcomes[q["decision"]] += 1
        by_chain[chain][q["decision"]] += 1
        dual_outcomes[dual_decision(by_provider.get(qset[0]), by_provider.get(qset[1]))] += 1
        bg_outcomes[bg_detects(by_provider.get(qset[0]))] += 1
        if q["decision"] == "silent_incomplete":
            silent_classes[q.get("agreed_class") or "unknown"] += 1
            inc = [m for m in members if m.get("failure_class") in INCOMPLETE]
            if len(inc) == 3:
                all_three_incomplete += 1
            if q.get("agreed_class") == "successful_empty":
                two_agree_empty += 1
        if q["decision"] == "silent_incomplete" and len(silent_examples) < 12:
            silent_examples.append(
                {
                    "epoch": epoch,
                    "chain": chain,
                    "method": method,
                    "nonce": nonce,
                    "block": block,
                    "agreed_class": q.get("agreed_class"),
                    "providers": qset,
                    "classes": [m.get("failure_class") for m in members],
                }
            )

    # Exhaustive 3-subsets: does any configured-size quorum majority-accept
    # a successful empty? This is still analytic; it does not change the
    # headline first-three-provider numbers.
    from itertools import combinations

    empty_pair_count = 0
    empty_group_count = 0
    empty_triples = Counter()
    for key, by_provider in grouped.items():
        names = [n for n in (PROVIDERS.get(key[1]) or []) if n in by_provider]
        hit = False
        for triple in combinations(names, 3):
            members = [by_provider[n] for n in triple]
            q = quorum_decision(members)
            if q["decision"] == "silent_incomplete" and q.get("agreed_class") == "successful_empty":
                empty_pair_count += 1
                hit = True
                empty_triples[tuple(sorted(triple))] += 1
        if hit:
            empty_group_count += 1

    summary = {
        "gate": "quorum_trace_baseline",
        "provenance": "saved_natural_failure_analytic_replay",
        "observed_at": datetime.now(timezone.utc).isoformat(),
        "source": str(INP.relative_to(ROOT) if str(INP).startswith(str(ROOT)) else INP),
        "rows_loaded": len(rows),
        "getLogs_groups_with_configured_3": evaluable,
        "configured_quorum": {chain: names[:3] for chain, names in PROVIDERS.items()},
        "quorum_2of3": dict(outcomes),
        "quorum_silent_by_class": dict(silent_classes),
        "quorum_all_three_incomplete": all_three_incomplete,
        "quorum_majority_successful_empty": two_agree_empty,
        "any_triple_majority_successful_empty_groups": empty_group_count,
        "any_triple_majority_successful_empty_triples": empty_pair_count,
        "any_triple_successful_empty_sets": {
            ",".join(k): v for k, v in empty_triples.most_common(12)
        },
        "always_dual_first_two": dict(dual_outcomes),
        "boundaryguard_on_first_provider": dict(bg_outcomes),
        "quorum_by_chain": {k: dict(v) for k, v in sorted(by_chain.items())},
        "silent_incomplete_examples": silent_examples,
        "note": (
            "Analytic replay of saved Gate-2 eth_getLogs replies. "
            "2-of-3 uses the first three providers in the frozen schedule map. "
            "Agreement on a successful incomplete body is a silent miss; "
            "BoundaryGuard detects the same incomplete primary via the nonce interval. "
            "Not an official Hyperlane quorum-mode agent run. "
            "UTC dates in EXCLUDE_UTC_DATES are omitted from the replay."
        ),
        "exclude_utc_dates": sorted(EXCLUDE_UTC_DATES),
    }
    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text(json.dumps(summary, indent=2, sort_keys=True) + "\n")
    print(json.dumps(summary, indent=2, sort_keys=True))


if __name__ == "__main__":
    main()
