#!/usr/bin/env python3
"""Reanalyze Gate-3 proxy JSONL with explicit denominators.

The original prefix_complete_rate treated evaluation-oracle unavailability
(expected is None) as incompleteness. That conflates harness eth_call failures
with retrieval omissions. This script reports issued / completed / fail-closed /
auditable / prefix-complete-of-auditable separately and rewrites the summary.
"""

from __future__ import annotations

# --- github publish layout (auto-generated by sync_github_publish.py) ---
import sys
from pathlib import Path as _Path
_GITHUB_ROOT = _Path(__file__).resolve().parents[1]
_BG = _GITHUB_ROOT / "BoundaryGuard"
_EXP = _GITHUB_ROOT / "exp"
for _p in (_BG, _EXP):
    _s = str(_p)
    if _s not in sys.path:
        sys.path.insert(0, _s)
DATA = _GITHUB_ROOT.joinpath("data")
EXP = _EXP
ROOT = _GITHUB_ROOT
# --- end header ---

import json
from collections import defaultdict
from pathlib import Path


ROOT = _GITHUB_ROOT
IN = DATA / "relayer_proxy_live.jsonl"
OUT = DATA / "relayer_proxy_live_summary.json"
DETAIL = DATA / "relayer_proxy_denominators.json"


def pct(vals: list[float], p: float) -> float | None:
    if not vals:
        return None
    vals = sorted(vals)
    return vals[min(len(vals) - 1, int(round((p / 100) * (len(vals) - 1))))]


def mode_metrics(rows: list[dict]) -> dict:
    n = len(rows)
    completed_rows = [r for r in rows if r.get("completed")]
    fail_closed = n - len(completed_rows)
    # Auditable: released a non-empty result AND evaluation oracle known.
    auditable = [
        r for r in completed_rows if r.get("expected") is not None
    ]
    count_mismatch = [
        r for r in auditable if int(r.get("returned") or 0) != int(r["expected"])
    ]
    prefix_aud = [r for r in auditable if r.get("prefix_complete")]
    # Legacy (misleading) rate kept for provenance of prior paper drafts.
    legacy_prefix_issued = sum(1 for r in rows if r.get("prefix_complete")) / n if n else None
    overhead = [r["proxy_overhead_ms"] for r in rows if r.get("proxy_overhead_ms") is not None]
    return {
        "n": n,
        "completed": len(completed_rows),
        "fail_closed": fail_closed,
        "completion_rate": len(completed_rows) / n if n else None,
        "expected_known": sum(1 for r in rows if r.get("expected") is not None),
        "auditable": len(auditable),
        "prefix_complete_of_auditable": (len(prefix_aud) / len(auditable)) if auditable else None,
        "count_mismatch_of_auditable": len(count_mismatch),
        "legacy_prefix_complete_of_issued": legacy_prefix_issued,
        "requests": sum(int(r.get("requests") or 1) for r in rows),
        "bytes": sum(int(r.get("bytes") or 0) for r in rows),
        "overhead_ms": {
            "p50": pct(overhead, 50),
            "p95": pct(overhead, 95),
            "p99": pct(overhead, 99),
        },
        # Keep old field name but point readers at auditable metric.
        "prefix_complete_rate": (len(prefix_aud) / len(auditable)) if auditable else None,
    }


def main() -> None:
    rows = [json.loads(line) for line in IN.read_text().splitlines() if line.strip()]
    by_mode: dict[str, list[dict]] = defaultdict(list)
    by_msg: dict[str, dict[str, dict]] = defaultdict(dict)
    for row in rows:
        by_mode[row["mode"]].append(row)
        by_msg[row["msg_id"]][row["mode"]] = row

    modes = {
        mode: mode_metrics(by_mode[mode])
        for mode in ("unchecked", "error_fallback", "always_dual", "boundaryguard")
        if mode in by_mode
    }

    # Paired subset: BG completed and every mode has a known expected count.
    paired = []
    for modes_for_msg in by_msg.values():
        if "boundaryguard" not in modes_for_msg:
            continue
        bg = modes_for_msg["boundaryguard"]
        if not bg.get("completed"):
            continue
        if any(modes_for_msg.get(m, {}).get("expected") is None
               for m in ("unchecked", "error_fallback", "always_dual", "boundaryguard")):
            continue
        if any(m not in modes_for_msg for m in ("unchecked", "error_fallback", "always_dual")):
            continue
        paired.append(modes_for_msg)

    paired_prefix = {
        mode: sum(1 for m in paired if m[mode].get("prefix_complete")) / len(paired)
        if paired else None
        for mode in ("unchecked", "error_fallback", "always_dual", "boundaryguard")
    }

    bg = modes["boundaryguard"]
    dual = modes["always_dual"]
    detail = {
        "provenance": "live_natural_observation",
        "reanalysis": (
            "prefix_complete requires expected!=None; legacy issued rates mixed "
            "evaluation-oracle misses with retrieval omissions"
        ),
        "modes": modes,
        "paired_auditable_messages": len(paired),
        "paired_prefix_complete_rate": paired_prefix,
        "finding": {
            "count_mismatches_in_window": {
                mode: modes[mode]["count_mismatch_of_auditable"] for mode in modes
            },
            "boundaryguard_fail_closed": bg["fail_closed"],
            "request_saving_vs_dual_pct": 100.0 * (dual["requests"] - bg["requests"]) / dual["requests"],
            "byte_saving_vs_dual_pct": 100.0 * (dual["bytes"] - bg["bytes"]) / dual["bytes"],
            "note": (
                "In this Optimism window, every auditable completed response matched "
                "the evaluation nonce delta; the prior 87.5%/89% issued rates were "
                "dominated by expected=None, not silent omissions."
            ),
        },
    }
    DETAIL.write_text(json.dumps(detail, indent=2, sort_keys=True) + "\n")

    # Preserve proxy_stats if present.
    old = json.loads(OUT.read_text()) if OUT.exists() else {}
    summary = {
        "provenance": "live_natural_observation",
        "interface": "unmodified JSON-RPC eth_getLogs (Hyperlane-relayer-compatible)",
        "note": (
            "Destination delivery timestamps are from the frozen Hyperlane delivery "
            "trace; proxy path is live. Denominators: completion = non-empty release; "
            "fail-closed = not completed; auditable = completed with known evaluation "
            "nonce delta; prefix_complete_rate is of auditable only."
        ),
        "messages": len(by_msg),
        "modes": modes,
        "boundaryguard_completion": bg["completion_rate"],
        "boundaryguard_fail_closed": bg["fail_closed"],
        "boundaryguard_prefix_complete_of_auditable": bg["prefix_complete_of_auditable"],
        "cu_or_request_saving_vs_dual_pct": detail["finding"]["request_saving_vs_dual_pct"],
        "byte_saving_vs_dual_pct": detail["finding"]["byte_saving_vs_dual_pct"],
        "paired_auditable_messages": len(paired),
        "paired_prefix_complete_rate": paired_prefix,
        "proxy_stats": old.get("proxy_stats"),
        "denominator_reanalysis": str(DETAIL.name),
    }
    OUT.write_text(json.dumps(summary, indent=2, sort_keys=True) + "\n")
    print(json.dumps(summary, indent=2, sort_keys=True))


if __name__ == "__main__":
    main()
