#!/usr/bin/env python3
"""Pre-gate replay for semantic-prefix catch-up after real workload outages.

This replay intentionally gives every policy the same empirically feasible
provider/span action per chain.  It therefore tests scheduling value, not the
easy gain from giving only the proposed method better RPC choices.
"""

from __future__ import annotations

# --- github publish layout (auto-generated by sync_github_publish.py) ---
import sys
from pathlib import Path as _Path
_GITHUB_ROOT = _Path(__file__).resolve().parents[1]
_BG = _GITHUB_ROOT / "BoundaryGuard"
_EXP = _GITHUB_ROOT / "exp"
for _p in (_BG, _EXP):
    _s = str(_p)
    if _s not in sys.path:
        sys.path.insert(0, _s)
DATA = _GITHUB_ROOT.joinpath("data")
EXP = _EXP
ROOT = _GITHUB_ROOT
# --- end header ---

import argparse
import json
import math
import statistics
from collections import defaultdict
from datetime import datetime, timezone
from pathlib import Path


# Largest range with >= 2/3 success in the small public-RPC probe.  Latency is
# the observed median successful service time.  Cost is one RPC request; dRPC
# documents eth_getLogs as 20 CU, but using equal request cost is conservative
# and avoids inventing a 1RPC CU conversion.
ACTIONS = {
    "ethereum": {"provider": "drpc", "span": 1000, "latency_s": 1.608657},
    "arbitrum": {"provider": "1rpc", "span": 50, "latency_s": 0.946335},
    "optimism": {"provider": "drpc", "span": 10000, "latency_s": 1.040550},
    "polygon": {"provider": "drpc", "span": 100, "latency_s": 0.977985},
}


def stamp(text: str) -> float:
    return datetime.fromisoformat(text).replace(tzinfo=timezone.utc).timestamp()


def percentile(values: list[float], q: float) -> float:
    if not values:
        return 0.0
    ordered = sorted(values)
    pos = (len(ordered) - 1) * q
    lo = math.floor(pos)
    hi = math.ceil(pos)
    if lo == hi:
        return ordered[lo]
    return ordered[lo] * (hi - pos) + ordered[hi] * (pos - lo)


def load(path: Path) -> dict[str, list[dict]]:
    by_chain: dict[str, list[dict]] = defaultdict(list)
    with path.open(encoding="utf-8") as handle:
        for line in handle:
            row = json.loads(line)
            row["t"] = stamp(row["send_occurred_at"])
            by_chain[row["chain"]].append(row)
    for rows in by_chain.values():
        rows.sort(key=lambda row: row["nonce"])
    return dict(by_chain)


def chain_rates(rows: list[dict]) -> tuple[float, float]:
    seconds = rows[-1]["t"] - rows[0]["t"]
    block_rate = (rows[-1]["origin_block_height"] - rows[0]["origin_block_height"]) / seconds
    msg_per_block = (len(rows) - 1) / max(1, rows[-1]["origin_block_height"] - rows[0]["origin_block_height"])
    return block_rate, msg_per_block


def outage_slice(rows: list[dict], start: float, end: float) -> tuple[int, int, list[dict]] | None:
    before = [row for row in rows if row["t"] < start]
    during = [row for row in rows if start <= row["t"] <= end]
    if not before:
        return None
    covered = before[-1]["origin_block_height"]
    head = during[-1]["origin_block_height"] if during else covered
    return covered, head, during


def replay(
    by_chain: dict[str, list[dict]],
    start: float,
    outage_s: float,
    policy: str,
    eta: float = 1.0,
    value_cost: float = 0.0,
    sla_s: float = 60.0,
) -> dict | None:
    recovery = start + outage_s
    state: dict[str, dict] = {}
    for chain, rows in by_chain.items():
        sliced = outage_slice(rows, start, recovery)
        if sliced is None:
            return None
        covered, head, pending = sliced
        block_rate, density = chain_rates(rows)
        state[chain] = {
            "frontier": covered,
            "head": head,
            "pending": pending,
            "block_rate": block_rate,
            "density": density,
            "last_evidence": start,
            "debt": 0.0,
        }

    now = recovery
    latencies: list[float] = []
    per_chain: dict[str, list[float]] = defaultdict(list)
    requests = 0
    worker_s = 0.0
    guard = 0
    while any(item["frontier"] < item["head"] for item in state.values()):
        guard += 1
        if guard > 100000:
            raise RuntimeError("replay did not converge")
        candidates: list[tuple[float, str]] = []
        for chain, item in state.items():
            backlog_blocks = max(0, item["head"] - item["frontier"])
            if backlog_blocks == 0:
                continue
            action = ACTIONS[chain]
            service_blocks = min(action["span"], backlog_blocks)
            expected_msgs = max(1e-6, service_blocks * item["density"])
            evidence_age = now - item["last_evidence"]
            efficiency = expected_msgs / action["latency_s"]
            if policy == "cost_age":
                score = evidence_age * efficiency
            elif policy == "age_debt":
                score = max(item["debt"], evidence_age - sla_s, 0.0) * efficiency
            elif policy == "gaps":
                backlog_msgs = backlog_blocks * item["density"]
                score = ((backlog_msgs + eta * item["debt"]) * expected_msgs - value_cost) / action["latency_s"]
            else:
                raise ValueError(policy)
            candidates.append((score, chain))
        _, chosen = max(candidates, key=lambda entry: (entry[0], entry[1]))
        action = ACTIONS[chosen]
        duration = action["latency_s"]
        for item in state.values():
            age_before = now - item["last_evidence"]
            if age_before > sla_s:
                item["debt"] += duration
        now += duration
        requests += 1
        worker_s += duration
        item = state[chosen]
        item["frontier"] = min(item["head"], item["frontier"] + action["span"])
        item["last_evidence"] = now
        item["debt"] = max(0.0, item["debt"] - duration)
        newly_seen = [
            row for row in item["pending"]
            if not row.get("seen") and row["origin_block_height"] <= item["frontier"]
        ]
        for row in newly_seen:
            row["seen"] = True
            delay = now - row["t"]
            latencies.append(delay)
            per_chain[chosen].append(delay)

    # Remove per-run markers because rows are shared by all policy replays.
    for item in state.values():
        for row in item["pending"]:
            row.pop("seen", None)
    return {
        "policy": policy,
        "eta": eta,
        "value_cost": value_cost,
        "messages": len(latencies),
        "requests": requests,
        "worker_s": worker_s,
        "mean": statistics.fmean(latencies),
        "p95": percentile(latencies, 0.95),
        "p99": percentile(latencies, 0.99),
        "worst_chain_p95": max(percentile(values, 0.95) for values in per_chain.values()),
    }


def aggregate(results: list[dict]) -> dict:
    return {
        "runs": len(results),
        "requests": statistics.fmean(row["requests"] for row in results),
        "worker_s": statistics.fmean(row["worker_s"] for row in results),
        "mean": statistics.fmean(row["mean"] for row in results),
        "p95": statistics.fmean(row["p95"] for row in results),
        "p99": statistics.fmean(row["p99"] for row in results),
        "worst_chain_p95": statistics.fmean(row["worst_chain_p95"] for row in results),
    }


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--input", type=Path, default=Path("data/hyperlane_messages.jsonl"))
    parser.add_argument("--outage-minutes", type=float, default=60.0)
    args = parser.parse_args()
    by_chain = load(args.input)
    common_start = max(rows[0]["t"] for rows in by_chain.values())
    common_end = min(rows[-1]["t"] for rows in by_chain.values())
    outage_s = args.outage_minutes * 60
    # Six equally spaced, non-overlapping real workload windows.  The first
    # three tune GAPS; the last three are held out for the reported pre-gate.
    usable_end = common_end - outage_s
    starts = [common_start + (usable_end - common_start) * (k + 1) / 7 for k in range(6)]
    train_starts, test_starts = starts[:3], starts[3:]

    grid: list[tuple[float, float, float]] = []
    for eta in (0.25, 1.0, 4.0, 16.0):
        for value_cost in (0.0, 0.1, 1.0, 10.0):
            rows = [replay(by_chain, start, outage_s, "gaps", eta, value_cost) for start in train_starts]
            rows = [row for row in rows if row]
            if rows:
                stats = aggregate(rows)
                grid.append((stats["p95"], eta, value_cost))
    _, best_eta, best_value = min(grid)

    policies = [
        ("cost_age", 1.0, 0.0),
        ("age_debt", 1.0, 0.0),
        ("gaps", best_eta, best_value),
    ]
    print(f"common window: {datetime.fromtimestamp(common_start, timezone.utc)} -- {datetime.fromtimestamp(common_end, timezone.utc)}")
    print(f"held-out outage windows: {len(test_starts)}, duration={args.outage_minutes:.0f} min")
    print(f"GAPS train choice: eta={best_eta}, V={best_value}")
    summaries: dict[str, dict] = {}
    for policy, eta, value in policies:
        rows = [replay(by_chain, start, outage_s, policy, eta, value) for start in test_starts]
        rows = [row for row in rows if row]
        summaries[policy] = aggregate(rows)
        print(policy, json.dumps(summaries[policy], sort_keys=True))
    base = summaries["cost_age"]
    gaps = summaries["gaps"]
    print("gaps_vs_cost_age", json.dumps({
        "mean_pct": 100 * (base["mean"] - gaps["mean"]) / base["mean"],
        "p95_pct": 100 * (base["p95"] - gaps["p95"]) / base["p95"],
        "p99_pct": 100 * (base["p99"] - gaps["p99"]) / base["p99"],
        "worst_chain_p95_pct": 100 * (base["worst_chain_p95"] - gaps["worst_chain_p95"]) / base["worst_chain_p95"],
        "request_pct": 100 * (base["requests"] - gaps["requests"]) / base["requests"],
    }, sort_keys=True))


if __name__ == "__main__":
    main()
