#!/usr/bin/env python3
"""Gate 3 testnet: official Hyperlane relayer + BoundaryGuard on Sepolia/OP Sepolia.

Design goals (money-safe):
  - Testnet only (sepolia <-> optimismsepolia)
  - Funded signer required on destination chain
  - Hard runtime cap (--seconds)
  - Optional self-dispatch of a tiny message so delivery is not IGP-lottery
  - Summary records proxy accepts + relayer log delivery signals + balances

Provenance: live_natural_observation on public testnets (not mainnet).
"""

from __future__ import annotations

# --- github publish layout (auto-generated by sync_github_publish.py) ---
import sys
from pathlib import Path as _Path
_GITHUB_ROOT = _Path(__file__).resolve().parents[1]
_BG = _GITHUB_ROOT / "BoundaryGuard"
_EXP = _GITHUB_ROOT / "exp"
for _p in (_BG, _EXP):
    _s = str(_p)
    if _s not in sys.path:
        sys.path.insert(0, _s)
DATA = _GITHUB_ROOT.joinpath("data")
EXP = _EXP
ROOT = _GITHUB_ROOT
# --- end header ---

import argparse
import json
import os
import re
import signal
import subprocess
import time
import urllib.request
from datetime import datetime, timezone
from pathlib import Path


ROOT = _GITHUB_ROOT
REPO = ROOT.parent
DATA = DATA
LOGS = ROOT / "logs"
CFG = ROOT / "configs" / "gate3_proxy_optimismsepolia.json"
SUMMARY = DATA / "relayer_official_gate3_testnet_summary.json"
TRACE = DATA / "relayer_official_proxy_trace_testnet.jsonl"
IMAGE = "ghcr.io/hyperlane-xyz/hyperlane-agent:agents-v2.2.0"

# Official Hyperlane Mailbox addresses (docs.hyperlane.xyz)
CHAINS = {
    "optimismsepolia": {
        "agent_name": "optimismsepolia",
        "domain_id": 11155420,
        "mailbox": "0x6966b0E55883d49BFB24539356a2f8A673E02039",
        # URLs must be pairwise distinct (proxy invariant). Chosen for GCE reachability.
        "rpc": "https://optimism-sepolia.drpc.org",
        "boundary_rpc": "https://optimism-sepolia.gateway.tenderly.co",
        "repair_rpc": "https://optimism-sepolia-rpc.publicnode.com",
    },
    "sepolia": {
        "agent_name": "sepolia",
        "domain_id": 11155111,
        "mailbox": "0xfFAEF09B3cd11D9b20d1a19bECca54EEC2884766",
        "rpc": "https://1rpc.io/sepolia",
        "boundary_rpc": "https://sepolia.drpc.org",
        "repair_rpc": "https://rpc.sepolia.org",
    },
}

# Deployed on Sepolia for A4 self-dispatch handle() target (EOA cannot handle).
# DiyTestRecipient on Sepolia with AlwaysIsm (NULL/moduleType=6) so DIY process
# does not depend on Hyperlane multisig validator metadata.
DEFAULT_TEST_RECIPIENT = "0x1Af932B73352e0cBF8e63b44a39Fb6d14F90D090"
DEFAULT_TEST_RECIPIENT_ISM = "0x94e04D906b32f3E4373e2De29334528d0afC0A56"
GAS_PAYMENT_NONE = '[{"type":"none"}]'



def rpc(url: str, method: str, params: list, timeout: float = 20.0) -> dict:
    payload = json.dumps({"jsonrpc": "2.0", "id": 1, "method": method, "params": params}).encode()
    # Some public RPCs (drpc) 403 bare Python-urllib User-Agent.
    req = urllib.request.Request(
        url,
        data=payload,
        headers={
            "content-type": "application/json",
            "user-agent": "BoundaryGuardGate3/1.0 (+https://github.com/)",
        },
    )
    started = time.perf_counter()
    try:
        with urllib.request.urlopen(req, timeout=timeout) as response:
            body = json.loads(response.read())
            return {
                "ok": "error" not in body,
                "result": body.get("result"),
                "error": body.get("error"),
                "latency_ms": (time.perf_counter() - started) * 1000,
            }
    except Exception as exc:
        return {"ok": False, "result": None, "error": f"{type(exc).__name__}:{exc}",
                "latency_ms": (time.perf_counter() - started) * 1000}


def load_key(explicit: str | None) -> str:
    if explicit:
        return explicit.strip()
    env = os.environ.get("HYP_DEFAULTSIGNER_KEY", "").strip()
    if env:
        return env
    for path in (
        ROOT / "configs" / "gate3_funded.key",
        ROOT / ".env",
    ):
        if not path.exists():
            continue
        text = path.read_text().strip()
        if path.name == ".env":
            for line in text.splitlines():
                line = line.strip()
                if not line or line.startswith("#") or "=" not in line:
                    continue
                k, v = line.split("=", 1)
                if any(x in k.upper() for x in ("PK", "KEY", "SIGNER")):
                    return v.strip().strip('"').strip("'")
        else:
            return text
    raise SystemExit("No signer key: set --signer-key, HYP_DEFAULTSIGNER_KEY, or work/.env")


def address_of(key: str) -> str:
    from eth_account import Account
    raw = key if key.startswith("0x") else "0x" + key
    return Account.from_key(raw).address


def eth_balance(url: str, addr: str) -> int:
    res = rpc(url, "eth_getBalance", [addr, "latest"])
    if not res["ok"] or not res["result"]:
        raise RuntimeError(f"balance failed on {url}: {res['error']}")
    return int(res["result"], 16)


def write_proxy_config(source: str) -> Path:
    cfg = CHAINS[source]
    payload = {
        "chain_id": source,
        "mailbox": cfg["mailbox"],
        "primary_url": cfg["rpc"],
        "boundary_url": cfg["boundary_rpc"],
        "repair_url": cfg["repair_rpc"],
        "timeout_s": 20.0,
        "retry_count": 1,
        "retry_base_s": 0.25,
        "chunk_count": 4,
        "confirmation_depth": 12,
        "finalized_tip": None,
        "byzantine_inclusion": False,
        "trace_path": str(TRACE),
    }
    CFG.parent.mkdir(parents=True, exist_ok=True)
    CFG.write_text(json.dumps(payload, indent=2) + "\n")
    return CFG


def start_proxy(config: Path, port: int) -> subprocess.Popen:
    LOGS.mkdir(parents=True, exist_ok=True)
    log = (LOGS / "gate3_testnet_proxy.log").open("w")
    return subprocess.Popen(
        ["python3", str(ROOT / "boundaryguard_proxy.py"),
         "--config", str(config), "--listen", "0.0.0.0", "--port", str(port)],
        cwd=str(REPO), stdout=log, stderr=subprocess.STDOUT,
    )


def run_relayer(source: str, dest: str, port: int, signer_key: str, seconds: int,
                gas_limit: int, gas_payment_enforcement: str,
                index_from: int | None, whitelist: str | None) -> dict:
    src = CHAINS[source]
    dst = CHAINS[dest]
    db_dir = DATA / "hyperlane_db_relayer_gate3_testnet"
    db_dir.mkdir(parents=True, exist_ok=True)
    proxy_url = f"http://host.docker.internal:{port}"
    key = signer_key.strip()
    if key.startswith("0x"):
        key = key[2:]
    # Prefer env signer so the private key is not visible in `ps`/`docker inspect`.
    env_flags = [
        "-e", f"HYP_CHAINS_{src['agent_name'].upper()}_CUSTOMRPCURLS={proxy_url}",
        "-e", f"HYP_CHAINS_{src['agent_name'].upper()}_RPCCONSENSUSTYPE=fallback",
        "-e", f"HYP_CHAINS_{dst['agent_name'].upper()}_CUSTOMRPCURLS={dst['rpc']}",
        "-e", f"HYP_CHAINS_{dst['agent_name'].upper()}_RPCCONSENSUSTYPE=fallback",
        "-e", f"HYP_GASPAYMENTENFORCEMENT={gas_payment_enforcement}",
        "-e", f"HYP_DEFAULTSIGNER_KEY=0x{key}",
    ]
    # Avoid multi-million-block backfill against non-archive public RPCs.
    if index_from is not None:
        env_flags += [
            "-e", f"HYP_CHAINS_{src['agent_name'].upper()}_INDEX_FROM={index_from}",
            "-e", f"HYP_CHAINS_{dst['agent_name'].upper()}_INDEX_FROM={max(0, index_from // 4)}",
        ]
    if whitelist:
        env_flags += ["-e", f"HYP_WHITELIST={whitelist}"]
    cmd = [
        "docker", "run", "--rm",
        "--name", "boundaryguard-hyperlane-relayer-testnet",
        "-u", "0:0",
        "--add-host=host.docker.internal:host-gateway",
        *env_flags,
        "--mount", f"type=bind,source={db_dir},target=/hyperlane_db",
        IMAGE,
        "./relayer",
        "--db", "/hyperlane_db",
        "--relayChains", f"{src['agent_name']},{dst['agent_name']}",
        "--allowLocalCheckpointSyncers", "true",
        "--transactionGasLimit", str(gas_limit),
        "--gasPaymentEnforcement", gas_payment_enforcement,
    ]
    if whitelist:
        cmd.extend(["--whitelist", whitelist])

    LOGS.mkdir(parents=True, exist_ok=True)
    log_path = LOGS / "gate3_testnet_relayer.log"
    with log_path.open("w") as log:
        proc = subprocess.Popen(cmd, stdout=log, stderr=subprocess.STDOUT)
        try:
            proc.wait(timeout=seconds)
            timed_out = False
            rc = proc.returncode
        except subprocess.TimeoutExpired:
            proc.send_signal(signal.SIGTERM)
            try:
                proc.wait(timeout=20)
            except subprocess.TimeoutExpired:
                proc.kill()
            timed_out = True
            rc = proc.returncode
    return {
        "command": [
            ("HYP_DEFAULTSIGNER_KEY=0x***redacted***" if isinstance(c, str) and c.startswith("HYP_DEFAULTSIGNER_KEY=") else c)
            for c in cmd
        ],
        "log_path": str(log_path.relative_to(REPO)),
        "returncode": rc,
        "timed_out": timed_out,
        "ran_seconds": seconds,
        "proxy_url": proxy_url,
        "transaction_gas_limit": gas_limit,
    }


def classify_log(path: Path) -> dict:
    if not path.exists():
        return {"exists": False}
    text = path.read_text(errors="ignore")
    patterns = {
        "no_signer": r"No signer found in provider",
        "archive_token": r"Archive requests require a personal token",
        "insufficient_funds": r"insufficient funds|InsufficientFunds",
        "process_like": r"Mailbox\.process|process_message|Submitting transaction|submit_tx|Transaction submitted",
        "delivered_like": r"Message delivered|delivered message|Delivery confirmed|Processed message",
        "errors": r"\bERROR\b",
    }
    return {
        "exists": True,
        "bytes": path.stat().st_size,
        "counts": {k: len(re.findall(v, text, flags=re.I)) for k, v in patterns.items()},
    }


# OP Sepolia MerkleTreeHook (skip IGP so public relayer won't race us).
OP_SEPOLIA_MERKLE_HOOK = "0x86fb9f1c124fb20ff130c41a79a432f770f67afd"


def try_self_dispatch(source: str, dest: str, key: str, addr: str,
                      recipient_addr: str, unpaid: bool = False) -> dict:
    """Dispatch to a TestRecipient contract (EOA cannot implement handle())."""
    cast = Path.home() / ".foundry" / "bin" / "cast"
    if not cast.exists():
        cast = Path("/usr/local/bin/cast")
    if not cast.exists():
        return _try_self_dispatch_web3(source, dest, key, addr, recipient_addr, unpaid)
    src = CHAINS[source]
    dst = CHAINS[dest]
    recipient = "0x" + recipient_addr.lower().replace("0x", "").rjust(64, "0")
    body = "0x426f756e64617279477561726403"  # BoundaryGuard + marker
    try:
        if unpaid and source == "optimismsepolia":
            quote = subprocess.run(
                [str(cast), "call", src["mailbox"],
                 "quoteDispatch(uint32,bytes32,bytes,bytes,address)(uint256)",
                 str(dst["domain_id"]), recipient, body, "0x", OP_SEPOLIA_MERKLE_HOOK,
                 "--rpc-url", src["rpc"]],
                capture_output=True, text=True, timeout=60,
            )
            fee_wei = 1
            if quote.returncode == 0:
                try:
                    fee_wei = max(1, int(quote.stdout.strip().split()[0]))
                except Exception:
                    fee_wei = 1
            send = subprocess.run(
                [str(cast), "send", src["mailbox"],
                 "dispatch(uint32,bytes32,bytes,bytes,address)(bytes32)",
                 str(dst["domain_id"]), recipient, body, "0x", OP_SEPOLIA_MERKLE_HOOK,
                 "--value", f"{fee_wei}wei",
                 "--private-key", key if key.startswith("0x") else "0x" + key,
                 "--rpc-url", src["rpc"], "--json"],
                capture_output=True, text=True, timeout=120,
            )
        else:
            quote = subprocess.run(
                [str(cast), "call", src["mailbox"],
                 "quoteDispatch(uint32,bytes32,bytes)(uint256)",
                 str(dst["domain_id"]), recipient, body,
                 "--rpc-url", src["rpc"]],
                capture_output=True, text=True, timeout=60,
            )
            fee_wei = None
            if quote.returncode == 0:
                try:
                    fee_wei = int(quote.stdout.strip().split()[0]) + 10**12
                except Exception:
                    fee_wei = None
            value_args = ["--value", f"{fee_wei}wei"] if fee_wei is not None else ["--value", "0.001ether"]
            send = subprocess.run(
                [str(cast), "send", src["mailbox"],
                 "dispatch(uint32,bytes32,bytes)(bytes32)",
                 str(dst["domain_id"]), recipient, body,
                 "--private-key", key if key.startswith("0x") else "0x" + key,
                 "--rpc-url", src["rpc"], "--json", *value_args],
                capture_output=True, text=True, timeout=120,
            )
        if send.returncode != 0:
            return {
                "attempted": True,
                "ok": False,
                "unpaid": unpaid,
                "recipient": recipient_addr,
                "fee_wei": fee_wei,
                "stderr": (send.stderr or send.stdout)[-500:],
            }
        receipt = json.loads(send.stdout)
        message_id = None
        for log in receipt.get("logs") or []:
            topics = log.get("topics") or []
            # DispatchId(bytes32)
            if topics and topics[0].startswith("0x788dbc") and len(topics) > 1:
                message_id = topics[1]
                break
        return {
            "attempted": True,
            "ok": True,
            "unpaid": unpaid,
            "recipient": recipient_addr,
            "fee_wei": fee_wei,
            "tx": receipt.get("transactionHash"),
            "message_id": message_id,
            "status": receipt.get("status"),
            "explorer": f"https://sepolia-optimism.etherscan.io/tx/{receipt.get('transactionHash')}"
            if source == "optimismsepolia"
            else f"https://sepolia.etherscan.io/tx/{receipt.get('transactionHash')}",
        }
    except Exception as exc:
        return {"attempted": True, "ok": False, "error": f"{type(exc).__name__}:{exc}"}


def _try_self_dispatch_web3(source: str, dest: str, key: str, addr: str,
                            recipient_addr: str, unpaid: bool) -> dict:
    """Fallback dispatch via eth_account when cast is unavailable (cloud)."""
    try:
        from eth_account import Account
        from eth_abi import encode
        from eth_utils import keccak, to_checksum_address
    except Exception as exc:
        return {"attempted": False, "reason": f"cast/web3 unavailable:{exc}"}
    src = CHAINS[source]
    dst = CHAINS[dest]
    recipient32 = bytes.fromhex(recipient_addr.lower().replace("0x", "").rjust(64, "0"))
    body = b"BoundaryGuard\x03"
    raw_key = key if key.startswith("0x") else "0x" + key
    acct = Account.from_key(raw_key)
    if unpaid and source == "optimismsepolia":
        selector = keccak(text="dispatch(uint32,bytes32,bytes,bytes,address)")[:4]
        encoded = encode(
            ["uint32", "bytes32", "bytes", "bytes", "address"],
            [dst["domain_id"], recipient32, body, b"", to_checksum_address(OP_SEPOLIA_MERKLE_HOOK)],
        )
        fee_wei = 1
        data = "0x" + (selector + encoded).hex()
        chain_id = 11155420
    else:
        selector = keccak(text="dispatch(uint32,bytes32,bytes)")[:4]
        encoded = encode(
            ["uint32", "bytes32", "bytes"],
            [dst["domain_id"], recipient32, body],
        )
        fee_wei = 2 * 10**13
        data = "0x" + (selector + encoded).hex()
        chain_id = 11155420 if source == "optimismsepolia" else 11155111
    nonce_res = rpc(src["rpc"], "eth_getTransactionCount", [acct.address, "pending"])
    gas_price_res = rpc(src["rpc"], "eth_gasPrice", [])
    if not nonce_res["ok"] or not gas_price_res["ok"]:
        return {"attempted": True, "ok": False, "error": "nonce/gasPrice rpc failed", "unpaid": unpaid}
    tx = {
        "to": to_checksum_address(src["mailbox"]),
        "value": fee_wei,
        "gas": 500_000,
        "gasPrice": int(gas_price_res["result"], 16),
        "nonce": int(nonce_res["result"], 16),
        "data": data,
        "chainId": chain_id,
    }
    signed = acct.sign_transaction(tx)
    raw = getattr(signed, "raw_transaction", None) or getattr(signed, "rawTransaction")
    send_res = rpc(src["rpc"], "eth_sendRawTransaction", ["0x" + raw.hex()])
    if not send_res["ok"] or not send_res["result"]:
        return {"attempted": True, "ok": False, "error": send_res.get("error"), "unpaid": unpaid}
    tx_hash = send_res["result"]
    message_id = None
    status = None
    for _ in range(30):
        time.sleep(2)
        rcpt = rpc(src["rpc"], "eth_getTransactionReceipt", [tx_hash])
        if rcpt["ok"] and rcpt["result"]:
            status = rcpt["result"].get("status")
            for log in rcpt["result"].get("logs") or []:
                topics = log.get("topics") or []
                if topics and topics[0].startswith("0x788dbc") and len(topics) > 1:
                    message_id = topics[1]
                    break
            break
    return {
        "attempted": True,
        "ok": status in ("0x1", 1, "1"),
        "unpaid": unpaid,
        "recipient": recipient_addr,
        "fee_wei": fee_wei,
        "tx": tx_hash,
        "message_id": message_id,
        "status": status,
        "via": "web3",
        "explorer": (
            f"https://sepolia-optimism.etherscan.io/tx/{tx_hash}"
            if source == "optimismsepolia"
            else f"https://sepolia.etherscan.io/tx/{tx_hash}"
        ),
    }


def _dest_rpcs(dest: str) -> list[str]:
    dst = CHAINS[dest]
    urls = [dst["rpc"], dst.get("boundary_rpc") or "", dst.get("repair_rpc") or ""]
    if dest == "sepolia":
        urls.extend(
            [
                "https://ethereum-sepolia.publicnode.com",
                "https://sepolia.gateway.tenderly.co",
                "https://rpc2.sepolia.org",
            ]
        )
    # Drop known-dead / quota-exhausted endpoints from the fallback list.
    bad = {"https://rpc.sepolia.org", "https://1rpc.io/sepolia"}
    urls = [u for u in urls if u not in bad]
    out: list[str] = []
    for url in urls:
        if url and url not in out:
            out.append(url)
    return out


def mailbox_delivered(dest: str, message_id: str) -> dict | None:
    if not message_id:
        return None
    dst = CHAINS[dest]
    cast = Path.home() / ".foundry" / "bin" / "cast"
    errors: list[str] = []
    for url in _dest_rpcs(dest):
        if cast.exists():
            try:
                out = subprocess.run(
                    [str(cast), "call", dst["mailbox"], "delivered(bytes32)(bool)", message_id,
                     "--rpc-url", url],
                    capture_output=True, text=True, timeout=20,
                )
            except subprocess.TimeoutExpired:
                errors.append(f"cast_timeout:{url}")
                continue
            if out.returncode == 0:
                text = out.stdout.strip().split()[0].lower()
                return {"message_id": message_id, "delivered": text in ("true", "1"), "rpc": url}
            errors.append(out.stderr.strip()[:160] or f"cast_rc={out.returncode}")
        data = "0xe495f1d4" + message_id.lower().replace("0x", "").rjust(64, "0")
        res = rpc(url, "eth_call", [{"to": dst["mailbox"], "data": data}, "latest"])
        if res.get("ok") and res.get("result"):
            return {
                "message_id": message_id,
                "delivered": int(res["result"], 16) != 0,
                "rpc": url,
            }
        errors.append(str(res.get("error") or "empty"))
    return {"message_id": message_id, "delivered": None, "error": "; ".join(errors[:3])}


def find_process_tx(dest: str, message_id: str, lookback: int = 8000) -> dict | None:
    """Locate Mailbox ProcessId(bytes32) for message_id and return tx sender."""
    if not message_id:
        return None
    from eth_utils import keccak

    dst = CHAINS[dest]
    topic0 = "0x" + keccak(text="ProcessId(bytes32)").hex()
    last_err = None
    for url in _dest_rpcs(dest):
        tip_res = rpc(url, "eth_blockNumber", [])
        if not tip_res.get("ok") or not tip_res.get("result"):
            last_err = tip_res.get("error")
            continue
        tip = int(tip_res["result"], 16)
        logs_res = rpc(
            url,
            "eth_getLogs",
            [{
                "address": dst["mailbox"],
                "topics": [topic0, message_id],
                "fromBlock": hex(max(0, tip - lookback)),
                "toBlock": "latest",
            }],
        )
        if not logs_res.get("ok"):
            last_err = logs_res.get("error")
            continue
        logs = logs_res.get("result") or []
        if not logs:
            return {"message_id": message_id, "found": False, "rpc": url}
        lg = logs[-1]
        txh = lg.get("transactionHash")
        tx = rpc(url, "eth_getTransactionByHash", [txh]).get("result") or {}
        return {
            "message_id": message_id,
            "found": True,
            "tx": txh,
            "from": tx.get("from"),
            "block": int(lg.get("blockNumber"), 16) if lg.get("blockNumber") else None,
            "explorer": f"https://sepolia.etherscan.io/tx/{txh}",
            "rpc": url,
        }
    return {"message_id": message_id, "found": False, "error": last_err}


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--source", default="optimismsepolia", choices=sorted(CHAINS))
    parser.add_argument("--dest", default="sepolia", choices=sorted(CHAINS))
    parser.add_argument("--port", type=int, default=18555)
    parser.add_argument("--seconds", type=int, default=300)
    parser.add_argument("--gas-limit", type=int, default=300_000,
                        help="Relayer transactionGasLimit spend guard")
    parser.add_argument("--min-dest-wei", type=int, default=10**15,
                        help="Refuse to start if destination balance below this")
    parser.add_argument("--signer-key", default=None)
    parser.add_argument("--skip-pull", action="store_true")
    parser.add_argument("--self-dispatch", action="store_true",
                        help="Attempt a tiny Mailbox.dispatch on source before relayer")
    parser.add_argument("--dispatch-only", action="store_true")
    parser.add_argument("--recipient", default=DEFAULT_TEST_RECIPIENT,
                        help="Sepolia TestRecipient for handle() (not an EOA)")
    parser.add_argument("--gas-payment-enforcement", default=GAS_PAYMENT_NONE,
                        help='JSON gasPaymentEnforcement (default [{"type":"none"}])')
    parser.add_argument("--prior-dispatch-tx", default=None,
                        help="Record a previously mined source dispatch tx in summary")
    parser.add_argument("--index-from", type=int, default=None,
                        help="Agent index.from for source (skip ancient non-archive ranges)")
    parser.add_argument("--reset-db", action="store_true",
                        help="Wipe hyperlane_db_relayer_gate3_testnet before start")
    parser.add_argument("--whitelist-sender", default=None,
                        help="Only relay messages from this sender (MatchingList JSON built)")
    parser.add_argument("--unpaid-dispatch", action="store_true",
                        help="Self-dispatch via merkleTreeHook only (skip IGP)")
    parser.add_argument("--dispatch-delay", type=int, default=0,
                        help="Seconds after relayer start before self-dispatch (0=before)")
    args = parser.parse_args()
    if args.source == args.dest:
        raise SystemExit("source and dest must differ")

    key = load_key(args.signer_key)
    addr = address_of(key)
    src = CHAINS[args.source]
    dst = CHAINS[args.dest]
    whitelist = None
    if args.whitelist_sender:
        sender = args.whitelist_sender
        whitelist = json.dumps([{"senderAddress": sender}])
    elif args.unpaid_dispatch or args.self_dispatch:
        # Default: focus DIY delivery on our own dispatches.
        whitelist = json.dumps([{"senderAddress": addr}])

    if args.reset_db:
        import shutil
        db = DATA / "hyperlane_db_relayer_gate3_testnet"
        if db.exists():
            shutil.rmtree(db)
        db.mkdir(parents=True, exist_ok=True)

    bal_src = eth_balance(src["rpc"], addr)
    bal_dst = eth_balance(dst["rpc"], addr)
    pre = {
        "address": addr,
        "source": args.source,
        "dest": args.dest,
        "balance_source_wei": bal_src,
        "balance_dest_wei": bal_dst,
        "balance_source_eth": bal_src / 1e18,
        "balance_dest_eth": bal_dst / 1e18,
        "test_recipient": args.recipient,
        "whitelist": whitelist,
    }
    print(json.dumps({"preflight": pre}, indent=2), flush=True)
    if bal_dst < args.min_dest_wei:
        raise SystemExit(
            f"Destination {args.dest} balance {bal_dst/1e18:.6f} ETH < "
            f"min {args.min_dest_wei/1e18:.6f}; fund it first"
        )

    dispatch_meta = {"attempted": False}
    if args.prior_dispatch_tx:
        dispatch_meta = {
            "attempted": True,
            "ok": True,
            "prior": True,
            "recipient": args.recipient,
            "tx": args.prior_dispatch_tx,
            "explorer": (
                f"https://sepolia-optimism.etherscan.io/tx/{args.prior_dispatch_tx}"
                if args.source == "optimismsepolia"
                else f"https://sepolia.etherscan.io/tx/{args.prior_dispatch_tx}"
            ),
        }

    do_dispatch = args.self_dispatch or args.dispatch_only or args.unpaid_dispatch
    if do_dispatch and args.dispatch_delay <= 0:
        print("attempting self-dispatch...", flush=True)
        dispatch_meta = try_self_dispatch(
            args.source, args.dest, key, addr, args.recipient, unpaid=args.unpaid_dispatch
        )
        print(json.dumps({"dispatch": dispatch_meta}, indent=2), flush=True)
        if args.dispatch_only:
            SUMMARY.write_text(json.dumps({
                "provenance": "live_natural_observation",
                "network": "testnet",
                "preflight": pre,
                "dispatch": dispatch_meta,
                "observed_at": datetime.now(timezone.utc).isoformat(),
            }, indent=2, sort_keys=True) + "\n")
            return

    if not args.skip_pull:
        subprocess.run(["docker", "pull", "--platform", "linux/amd64", IMAGE], check=False)

    if TRACE.exists():
        TRACE.unlink()
    config = write_proxy_config(args.source)
    proxy = start_proxy(config, args.port)
    time.sleep(1.0)

    # Mid-run unpaid dispatch so the tip-focused relayer sees a fresh message.
    delayed = None
    if do_dispatch and args.dispatch_delay > 0:
        import threading

        def _late() -> None:
            nonlocal dispatch_meta
            time.sleep(args.dispatch_delay)
            print(f"delayed self-dispatch after {args.dispatch_delay}s...", flush=True)
            dispatch_meta = try_self_dispatch(
                args.source, args.dest, key, addr, args.recipient, unpaid=args.unpaid_dispatch
            )
            print(json.dumps({"dispatch": dispatch_meta}, indent=2), flush=True)

        delayed = threading.Thread(target=_late, daemon=True)
        delayed.start()

    try:
        meta = run_relayer(
            args.source, args.dest, args.port, key, args.seconds, args.gas_limit,
            args.gas_payment_enforcement, args.index_from, whitelist,
        )
        if delayed is not None:
            delayed.join(timeout=30)
        log_stats = classify_log(REPO / meta["log_path"])
        trace_rows = []
        if TRACE.exists():
            trace_rows = [json.loads(l) for l in TRACE.read_text().splitlines() if l.strip()]
        accepts = sum(1 for r in trace_rows if r.get("outcome") == "accept")
        post_dst = eth_balance(dst["rpc"], addr)
        post_src = eth_balance(src["rpc"], addr)
        delivery = mailbox_delivered(args.dest, (dispatch_meta or {}).get("message_id") or "")
        process_tx = find_process_tx(args.dest, (dispatch_meta or {}).get("message_id") or "")
        if isinstance(delivery, dict) and process_tx:
            delivery = {**delivery, "process_tx": process_tx, "process_from": process_tx.get("from")}
        our_process = bool(
            process_tx
            and process_tx.get("from")
            and process_tx["from"].lower() == addr.lower()
        )
        summary = {
            "provenance": "live_natural_observation",
            "network": "testnet",
            "interface": "official Hyperlane agent Docker image ./relayer",
            "image": IMAGE,
            "source_chain": args.source,
            "dest_chain": args.dest,
            "address": addr,
            "test_recipient": args.recipient,
            "whitelist": whitelist,
            "preflight": pre,
            "post_balances": {
                "source_eth": post_src / 1e18,
                "dest_eth": post_dst / 1e18,
                "dest_spent_eth": (bal_dst - post_dst) / 1e18,
                "source_spent_eth": (bal_src - post_src) / 1e18,
            },
            "delivery": delivery,
            "delivery_check": delivery,
            "process_tx": process_tx,
            "our_process": our_process,
            "diy_delivery_likely": bool(
                delivery and delivery.get("delivered") and our_process
            ),
            "proxy_accepts": accepts,
            "proxy_trace_rows": len(trace_rows),
            "proxy_outcomes": {
                k: sum(1 for r in trace_rows if r.get("outcome") == k)
                for k in sorted({r.get("outcome") for r in trace_rows})
            },
            "relayer": meta,
            "log_stats": log_stats,
            "dispatch": dispatch_meta,
            "spend_guards": {
                "seconds": args.seconds,
                "transaction_gas_limit": args.gas_limit,
                "min_dest_wei": args.min_dest_wei,
                "gas_payment_enforcement": args.gas_payment_enforcement,
                "index_from": args.index_from,
            },
            "note": (
                "Testnet funded path (Sepolia <-> OP Sepolia). Prefer unpaid merkle-only "
                "dispatch + whitelist so public IGP hunters skip; require ProcessId tx "
                "from our signer under a non-Always ISM (official TestRecipient)."
            ),
            "observed_at": datetime.now(timezone.utc).isoformat(),
        }
    finally:
        proxy.terminate()
        try:
            proxy.wait(timeout=10)
        except subprocess.TimeoutExpired:
            proxy.kill()

    SUMMARY.write_text(json.dumps(summary, indent=2, sort_keys=True) + "\n")
    print(json.dumps(summary, indent=2, sort_keys=True))


if __name__ == "__main__":
    main()
