#!/usr/bin/env python3
"""Gate 3: unmodified JSON-RPC relayer client through BoundaryGuard proxy.

An unmodified Hyperlane relayer speaks ordinary JSON-RPC. This harness runs the
same query interface against four configurations and records source-event,
proxy-release, relay-submit, and destination-delivery timestamps for historical
delivered messages. Destination delivery times come from the frozen Hyperlane
trace when available; the client itself never uses proprietary APIs.
"""

from __future__ import annotations

# --- github publish layout (auto-generated by sync_github_publish.py) ---
import sys
from pathlib import Path as _Path
_GITHUB_ROOT = _Path(__file__).resolve().parents[1]
_BG = _GITHUB_ROOT / "BoundaryGuard"
_EXP = _GITHUB_ROOT / "exp"
for _p in (_BG, _EXP):
    _s = str(_p)
    if _s not in sys.path:
        sys.path.insert(0, _s)
DATA = _GITHUB_ROOT.joinpath("data")
EXP = _EXP
ROOT = _GITHUB_ROOT
# --- end header ---

import argparse
import json
import threading
import time
import urllib.request
from dataclasses import dataclass
from datetime import datetime
from http.server import ThreadingHTTPServer
from pathlib import Path

from boundaryguard_proxy import BoundaryGuardProxy, ProxyConfig, make_handler
from hyperlane_identity import DISPATCH_TOPIC, normalize
from rpc_probe import rpc


ROOT = _GITHUB_ROOT
MESSAGES = DATA / "hyperlane_messages.jsonl"
OUT = DATA / "relayer_proxy_live.jsonl"
SUMMARY = DATA / "relayer_proxy_live_summary.json"

CHAIN_CFG = {
    "optimism": {
        "primary": "https://mainnet.optimism.io",
        "boundary": "https://optimism.drpc.org",
        "repair": "https://op-pokt.nodies.app",
        "fallback": "https://optimism.drpc.org",
    },
}


def parse_ts(value: object) -> float | None:
    if value is None:
        return None
    if isinstance(value, (int, float)):
        return float(value)
    text = str(value)
    try:
        return datetime.fromisoformat(text.replace("Z", "+00:00")).timestamp()
    except Exception:
        return None


@dataclass
class FakeDual:
    """Always-dual baseline: query two providers and prefer the larger log set."""

    primary: str
    secondary: str
    timeout_s: float = 15.0

    def eth_get_logs(self, query: dict) -> tuple[list, dict]:
        a = rpc(self.primary, "eth_getLogs", [query], self.timeout_s)
        b = rpc(self.secondary, "eth_getLogs", [query], self.timeout_s)
        ra, rb = a.get("result"), b.get("result")
        la = ra if isinstance(ra, list) else []
        lb = rb if isinstance(rb, list) else []
        chosen = la if len(la) >= len(lb) else lb
        meta = {
            "primary_outcome": a["outcome"],
            "secondary_outcome": b["outcome"],
            "requests": 2,
            "bytes": len(json.dumps(ra, default=str)) + len(json.dumps(rb, default=str)),
        }
        return chosen, meta


def start_proxy(cfg: ProxyConfig, port: int) -> tuple[ThreadingHTTPServer, BoundaryGuardProxy]:
    proxy = BoundaryGuardProxy(cfg)
    server = ThreadingHTTPServer(("127.0.0.1", port), make_handler(proxy))
    thread = threading.Thread(target=server.serve_forever, daemon=True)
    thread.start()
    time.sleep(0.2)
    return server, proxy


def jsonrpc(url: str, method: str, params: list, timeout_s: float = 20.0) -> dict:
    payload = {"jsonrpc": "2.0", "id": 1, "method": method, "params": params}
    req = urllib.request.Request(
        url,
        data=json.dumps(payload).encode(),
        headers={"content-type": "application/json", "user-agent": "HyperlaneRelayerCompat/1.0"},
    )
    started = time.perf_counter()
    try:
        with urllib.request.urlopen(req, timeout=timeout_s) as response:
            body = response.read()
            parsed = json.loads(body)
            return {
                "outcome": "error" if "error" in parsed else "ok",
                "result": parsed.get("result"),
                "error": parsed.get("error"),
                "latency_ms": (time.perf_counter() - started) * 1000,
                "bytes": len(body),
                "http_status": response.status,
            }
    except Exception as exc:
        return {
            "outcome": "transport_error",
            "result": None,
            "error": f"{type(exc).__name__}:{exc}",
            "latency_ms": (time.perf_counter() - started) * 1000,
            "bytes": 0,
            "http_status": None,
        }


def load_messages(chain: str, limit: int, recent: bool = False) -> list[dict]:
    rows = []
    with MESSAGES.open() as handle:
        for line in handle:
            row = json.loads(line)
            if row["chain"] != chain:
                continue
            if not row.get("is_delivered"):
                continue
            rows.append(row)
    rows.sort(key=lambda r: r["origin_block_height"])
    if len(rows) <= limit:
        return rows
    if recent:
        # Prefer tip-near history so public tip RPCs can serve eth_getLogs.
        return rows[-limit:]
    return [rows[round(i * (len(rows) - 1) / (limit - 1))] for i in range(limit)]


def expected_count(url: str, mailbox: str, start: int, end: int) -> int | None:
    selector = "0xaffed0e0"
    before = rpc(url, "eth_call", [{"to": mailbox, "data": selector}, hex(start - 1)], 12)
    after = rpc(url, "eth_call", [{"to": mailbox, "data": selector}, hex(end)], 12)
    if before["outcome"] != "ok" or after["outcome"] != "ok":
        return None
    try:
        return int(after["result"], 16) - int(before["result"], 16)
    except Exception:
        return None


def run_mode(mode: str, messages: list[dict], cfg: dict, proxy_url: str | None) -> list[dict]:
    dual = FakeDual(cfg["primary"], cfg["fallback"])
    records = []
    for message in messages:
        mailbox = normalize(message["origin_mailbox"])
        block = int(message["origin_block_height"])
        start = end = block
        query = {
            "fromBlock": hex(start),
            "toBlock": hex(end),
            "address": mailbox,
            "topics": [DISPATCH_TOPIC],
        }
        source_event_ts = parse_ts(message.get("send_occurred_at"))
        dest_delivery_ts = parse_ts(message.get("delivery_occurred_at"))
        t0 = time.time()
        meta = {"requests": 1, "bytes": 0}
        logs: list = []
        release_ts = None
        submit_ts = None
        completed = False
        if mode == "unchecked":
            resp = rpc(cfg["primary"], "eth_getLogs", [query], 15)
            logs = resp.get("result") if isinstance(resp.get("result"), list) else []
            meta = {"requests": 1, "bytes": len(json.dumps(resp.get("result"), default=str)),
                    "outcome": resp["outcome"], "latency_ms": resp["latency_ms"]}
            release_ts = time.time()
            completed = len(logs) > 0
        elif mode == "error_fallback":
            resp = rpc(cfg["primary"], "eth_getLogs", [query], 15)
            if resp["outcome"] != "ok":
                resp = rpc(cfg["fallback"], "eth_getLogs", [query], 15)
                meta["requests"] = 2
            logs = resp.get("result") if isinstance(resp.get("result"), list) else []
            meta.update({"outcome": resp["outcome"], "latency_ms": resp["latency_ms"],
                         "bytes": len(json.dumps(resp.get("result"), default=str))})
            release_ts = time.time()
            # Silent empty is not an explicit error, so fallback does not help.
            completed = len(logs) > 0
        elif mode == "always_dual":
            logs, dual_meta = dual.eth_get_logs(query)
            meta.update(dual_meta)
            release_ts = time.time()
            completed = len(logs) > 0
        elif mode == "boundaryguard":
            assert proxy_url is not None
            resp = jsonrpc(proxy_url, "eth_getLogs", [query], 25)
            logs = resp.get("result") if isinstance(resp.get("result"), list) else []
            meta.update({
                "outcome": resp["outcome"],
                "latency_ms": resp["latency_ms"],
                "bytes": resp["bytes"],
                "http_status": resp["http_status"],
                "error": resp.get("error"),
            })
            release_ts = time.time()
            completed = resp["outcome"] == "ok" and len(logs) > 0
        submit_ts = time.time() if completed else None
        # Completeness vs protocol state for single-block query.
        expected = expected_count(cfg["boundary"], mailbox, start, end)
        complete = completed and expected is not None and len(logs) == expected
        records.append({
            "provenance": "live_natural_observation",
            "mode": mode,
            "chain": message["chain"],
            "nonce": message["nonce"],
            "block": block,
            "msg_id": message["msg_id"],
            "source_event_ts": source_event_ts,
            "proxy_release_ts": release_ts,
            "relay_submit_ts": submit_ts,
            "destination_delivery_ts": dest_delivery_ts,
            "proxy_overhead_ms": None if source_event_ts is None or release_ts is None
            else (release_ts - t0) * 1000,
            "source_to_proxy_ms": None if source_event_ts is None or release_ts is None
            else (release_ts - source_event_ts) * 1000,
            "proxy_to_dest_ms": None if release_ts is None or dest_delivery_ts is None
            else (dest_delivery_ts - release_ts) * 1000,
            "returned": len(logs),
            "expected": expected,
            "completed": completed,
            "prefix_complete": complete,
            "is_delivered_in_trace": bool(message.get("is_delivered")),
            **meta,
            "observed_at": time.time(),
        })
        print(mode, message["nonce"], "completed", completed, "prefix", complete, flush=True)
        time.sleep(0.05)
    return records


def summarize(records: list[dict]) -> dict:
    modes = {}
    for mode in ("unchecked", "error_fallback", "always_dual", "boundaryguard"):
        rows = [row for row in records if row["mode"] == mode]
        if not rows:
            continue
        overhead = [row["proxy_overhead_ms"] for row in rows if row["proxy_overhead_ms"] is not None]
        overhead.sort()

        def pct(vals: list[float], p: float) -> float | None:
            if not vals:
                return None
            return vals[min(len(vals) - 1, int(round((p / 100) * (len(vals) - 1))))]

        completed = [row for row in rows if row["completed"]]
        auditable = [row for row in completed if row.get("expected") is not None]
        prefix_aud = sum(1 for row in auditable if row["prefix_complete"])
        modes[mode] = {
            "n": len(rows),
            "completed": len(completed),
            "fail_closed": len(rows) - len(completed),
            "completion_rate": len(completed) / len(rows),
            "auditable": len(auditable),
            "prefix_complete_of_auditable": (prefix_aud / len(auditable)) if auditable else None,
            # Auditable-only rate; do not mix evaluation-oracle misses into this field.
            "prefix_complete_rate": (prefix_aud / len(auditable)) if auditable else None,
            "legacy_prefix_complete_of_issued": sum(bool(row["prefix_complete"]) for row in rows) / len(rows),
            "count_mismatch_of_auditable": sum(
                1 for row in auditable if int(row.get("returned") or 0) != int(row["expected"])
            ),
            "requests": sum(row.get("requests", 1) for row in rows),
            "bytes": sum(row.get("bytes", 0) for row in rows),
            "overhead_ms": {
                "p50": pct(overhead, 50),
                "p95": pct(overhead, 95),
                "p99": pct(overhead, 99),
            },
        }
    bg = modes.get("boundaryguard", {})
    dual = modes.get("always_dual", {})
    return {
        "provenance": "live_natural_observation",
        "interface": "unmodified JSON-RPC eth_getLogs (Hyperlane-relayer-compatible)",
        "note": (
            "Destination delivery timestamps are from the frozen Hyperlane delivery "
            "trace; proxy path is live. prefix_complete_rate is among auditable "
            "completed responses (known evaluation nonce delta), not among issued."
        ),
        "modes": modes,
        "boundaryguard_completion": bg.get("completion_rate"),
        "boundaryguard_fail_closed": bg.get("fail_closed"),
        "boundaryguard_prefix_complete_of_auditable": bg.get("prefix_complete_of_auditable"),
        "cu_or_request_saving_vs_dual_pct": None if not dual or not bg else
        100.0 * (dual["requests"] - bg["requests"]) / dual["requests"],
        "byte_saving_vs_dual_pct": None if not dual or not bg or not dual.get("bytes") else
        100.0 * (dual["bytes"] - bg["bytes"]) / dual["bytes"],
        "messages": len({(row["chain"], row["nonce"]) for row in records}),
    }


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--chain", default="optimism")
    parser.add_argument("--limit", type=int, default=80)
    parser.add_argument("--port", type=int, default=18545)
    parser.add_argument(
        "--recent",
        action="store_true",
        help="Sample the most recent delivered messages instead of evenly spaced history",
    )
    parser.add_argument(
        "--tag",
        default="",
        help="Optional output tag, e.g. recent500 -> relayer_proxy_live_recent500.jsonl",
    )
    args = parser.parse_args()
    cfg = CHAIN_CFG[args.chain]
    messages = load_messages(args.chain, args.limit, recent=args.recent)
    out = DATA / (f"relayer_proxy_live_{args.tag}.jsonl" if args.tag else "relayer_proxy_live.jsonl")
    summary_path = DATA / (
        f"relayer_proxy_live_{args.tag}_summary.json" if args.tag else "relayer_proxy_live_summary.json"
    )
    trace_path = DATA / (
        f"relayer_proxy_trace_{args.tag}.jsonl" if args.tag else "relayer_proxy_trace.jsonl"
    )
    mailbox = normalize(messages[0]["origin_mailbox"])
    proxy_cfg = ProxyConfig(
        chain_id=args.chain,
        mailbox=mailbox,
        primary_url=cfg["primary"],
        boundary_url=cfg["boundary"],
        repair_url=cfg["repair"],
        timeout_s=20.0,
        retry_count=1,
        chunk_count=4,
        confirmation_depth=0,
        finalized_tip=None,
        trace_path=str(trace_path),
    )
    server, proxy = start_proxy(proxy_cfg, args.port)
    proxy_url = f"http://127.0.0.1:{args.port}"
    all_records: list[dict] = []
    try:
        for mode in ("unchecked", "error_fallback", "always_dual", "boundaryguard"):
            all_records.extend(run_mode(mode, messages, cfg, proxy_url))
    finally:
        server.shutdown()
    with out.open("w") as handle:
        for row in all_records:
            handle.write(json.dumps(row, sort_keys=True) + "\n")
    summary = summarize(all_records)
    summary["proxy_stats"] = proxy.stats
    summary["sample"] = {"recent": args.recent, "limit": args.limit, "tag": args.tag or None}
    summary_path.write_text(json.dumps(summary, indent=2, sort_keys=True) + "\n")
    print(json.dumps(summary, indent=2, sort_keys=True))


if __name__ == "__main__":
    main()
