#!/usr/bin/env python3
"""Gate 3': run official Hyperlane relayer agent against BoundaryGuard proxy.

This harness:
  1. Writes a local proxy config for Optimism (or configurable chain).
  2. Starts BoundaryGuard as a JSON-RPC endpoint.
  3. Launches the unmodified Hyperlane agent Docker image `./relayer` with
     customRpcUrls pointed at the proxy (host.docker.internal).
  4. Records proxy traces and whether the official binary issued eth_getLogs.

Destination delivery still requires a funded signer key. Pass --signer-key or
HYP_DEFAULTSIGNER_KEY. Without funds the agent may index/query via the proxy
but cannot submit Mailbox.process transactions; that limitation is recorded
honestly in the summary.
"""

from __future__ import annotations

# --- github publish layout (auto-generated by sync_github_publish.py) ---
import sys
from pathlib import Path as _Path
_GITHUB_ROOT = _Path(__file__).resolve().parents[1]
_BG = _GITHUB_ROOT / "BoundaryGuard"
_EXP = _GITHUB_ROOT / "exp"
for _p in (_BG, _EXP):
    _s = str(_p)
    if _s not in sys.path:
        sys.path.insert(0, _s)
DATA = _GITHUB_ROOT.joinpath("data")
EXP = _EXP
ROOT = _GITHUB_ROOT
# --- end header ---

import argparse
import json
import os
import signal
import subprocess
import time
from datetime import datetime, timezone
from pathlib import Path


ROOT = _GITHUB_ROOT
REPO = ROOT.parent
DATA = DATA
LOGS = ROOT / "logs"
CFG = ROOT / "configs" / "gate3_proxy_optimism.json"
SUMMARY = DATA / "relayer_official_gate3_summary.json"
TRACE = DATA / "relayer_official_proxy_trace.jsonl"

CHAIN_DEFAULTS = {
    "optimism": {
        "chain_name": "optimism",
        "mailbox": "0xd4c1905bb1d26bc93dac913e13cacc278cdcc80d",
        "primary_url": "https://mainnet.optimism.io",
        "boundary_url": "https://optimism.drpc.org",
        "repair_url": "https://op-pokt.nodies.app",
        "relay_chains": "optimism,ethereum",
    }
}

IMAGE = "ghcr.io/hyperlane-xyz/hyperlane-agent:agents-v2.2.0"


def write_proxy_config(chain: str, port: int) -> Path:
    cfg = CHAIN_DEFAULTS[chain]
    payload = {
        "chain_id": chain,
        "mailbox": cfg["mailbox"],
        "primary_url": cfg["primary_url"],
        "boundary_url": cfg["boundary_url"],
        "repair_url": cfg["repair_url"],
        "timeout_s": 20.0,
        "retry_count": 1,
        "retry_base_s": 0.25,
        "chunk_count": 4,
        "confirmation_depth": 64,
        "finalized_tip": None,
        "byzantine_inclusion": False,
        "trace_path": str(TRACE),
    }
    CFG.parent.mkdir(parents=True, exist_ok=True)
    CFG.write_text(json.dumps(payload, indent=2) + "\n")
    return CFG


def start_proxy(config: Path, port: int) -> subprocess.Popen:
    LOGS.mkdir(parents=True, exist_ok=True)
    log = (LOGS / "gate3_proxy.log").open("w")
    proc = subprocess.Popen(
        [
            "python3",
            str(ROOT / "boundaryguard_proxy.py"),
            "--config",
            str(config),
            "--listen",
            "0.0.0.0",
            "--port",
            str(port),
        ],
        cwd=str(REPO),
        stdout=log,
        stderr=subprocess.STDOUT,
    )
    time.sleep(1.0)
    return proc


def docker_available() -> bool:
    try:
        subprocess.run(["docker", "info"], check=True, capture_output=True)
        return True
    except Exception:
        return False


def pull_image() -> None:
    subprocess.run(
        ["docker", "pull", "--platform", "linux/amd64", IMAGE],
        check=True,
    )


def run_relayer(chain: str, port: int, signer_key: str | None, seconds: int) -> dict:
    cfg = CHAIN_DEFAULTS[chain]
    db_dir = DATA / "hyperlane_db_relayer_gate3"
    db_dir.mkdir(parents=True, exist_ok=True)
    proxy_url = f"http://host.docker.internal:{port}"
    eth_rpc = "https://ethereum-rpc.publicnode.com"
    cmd = [
        "docker",
        "run",
        "--rm",
        "--name",
        "boundaryguard-hyperlane-relayer",
        "-u",
        "0:0",
        "--add-host=host.docker.internal:host-gateway",
        "-e",
        f"HYP_CHAINS_{cfg['chain_name'].upper()}_CUSTOMRPCURLS={proxy_url}",
        "-e",
        f"HYP_CHAINS_{cfg['chain_name'].upper()}_RPCCONSENSUSTYPE=fallback",
        "-e",
        f"HYP_CHAINS_ETHEREUM_CUSTOMRPCURLS={eth_rpc}",
        "-e",
        "HYP_CHAINS_ETHEREUM_RPCCONSENSUSTYPE=fallback",
        "--mount",
        f"type=bind,source={db_dir},target=/hyperlane_db",
        IMAGE,
        "./relayer",
        "--db",
        "/hyperlane_db",
        "--relayChains",
        cfg["relay_chains"],
        "--allowLocalCheckpointSyncers",
        "true",
    ]
    if signer_key:
        key = signer_key.strip()
        if key.startswith("0x"):
            key = key[2:]
        cmd.extend(["--defaultSigner.key", "0x" + key])
    LOGS.mkdir(parents=True, exist_ok=True)
    log_path = LOGS / "gate3_official_relayer.log"
    with log_path.open("w") as log:
        proc = subprocess.Popen(cmd, stdout=log, stderr=subprocess.STDOUT)
        try:
            proc.wait(timeout=seconds)
            rc = proc.returncode
            timed_out = False
        except subprocess.TimeoutExpired:
            proc.send_signal(signal.SIGTERM)
            try:
                proc.wait(timeout=20)
            except subprocess.TimeoutExpired:
                proc.kill()
            rc = proc.returncode
            timed_out = True
    return {
        "command": [c if not (isinstance(c, str) and c.startswith("0x") and len(c) > 20) else "0x***redacted***" for c in cmd],
        "log_path": str(log_path.relative_to(REPO)),
        "returncode": rc,
        "timed_out": timed_out,
        "ran_seconds": seconds,
        "proxy_url": proxy_url,
        "ethereum_rpc": eth_rpc,
    }


def summarize(proxy_proc: subprocess.Popen, relayer_meta: dict) -> dict:
    from collections import Counter

    trace_rows = []
    if TRACE.exists():
        trace_rows = [json.loads(line) for line in TRACE.read_text().splitlines() if line.strip()]
    outcomes = Counter(row.get("outcome") for row in trace_rows)
    methods = Counter(
        row.get("method") or row.get("rpc_method") for row in trace_rows
        if row.get("method") or row.get("rpc_method")
    )
    getlogs = sum(
        1
        for row in trace_rows
        if "getLogs" in str(row.get("method") or row.get("rpc_method") or "")
    )
    # Proxy audit traces may omit method; count accepts as evidence of audited ranges.
    accepts = sum(1 for row in trace_rows if row.get("outcome") == "accept")
    return {
        "provenance": "live_natural_observation",
        "interface": "official Hyperlane agent Docker image ./relayer",
        "image": IMAGE,
        "proxy_alive_after": proxy_proc.poll() is None,
        "proxy_trace_rows": len(trace_rows),
        "proxy_outcomes": dict(outcomes),
        "proxy_accepts": accepts,
        "proxy_methods": dict(methods),
        "eth_getLogs_seen": getlogs,
        "audited_ranges_seen": accepts if getlogs == 0 else getlogs,
        "relayer": relayer_meta,
        "note": (
            "Unmodified Hyperlane relayer binary talks to BoundaryGuard over JSON-RPC. "
            "Destination Mailbox.process submission requires a funded signer; without "
            "funds this run validates the retrieval path through the proxy, not live "
            "destination inclusion. audited_ranges_seen counts proxy accept outcomes "
            "when method labels are absent from the trace schema."
        ),
        "observed_at": datetime.now(timezone.utc).isoformat(),
    }


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--chain", default="optimism", choices=sorted(CHAIN_DEFAULTS))
    parser.add_argument("--port", type=int, default=18545)
    parser.add_argument("--seconds", type=int, default=120, help="How long to let the official relayer run")
    parser.add_argument("--signer-key", default=os.environ.get("HYP_DEFAULTSIGNER_KEY"))
    parser.add_argument("--skip-pull", action="store_true")
    args = parser.parse_args()

    if not docker_available():
        raise SystemExit(
            "Docker daemon is not running. Start Docker Desktop, then re-run:\n"
            "  python3 work/relayer_official_gate3.py"
        )

    if not args.skip_pull:
        pull_image()

    if TRACE.exists():
        TRACE.unlink()
    config = write_proxy_config(args.chain, args.port)
    proxy = start_proxy(config, args.port)
    try:
        meta = run_relayer(args.chain, args.port, args.signer_key, args.seconds)
        summary = summarize(proxy, meta)
    finally:
        proxy.terminate()
        try:
            proxy.wait(timeout=10)
        except subprocess.TimeoutExpired:
            proxy.kill()
    SUMMARY.write_text(json.dumps(summary, indent=2, sort_keys=True) + "\n")
    print(json.dumps(summary, indent=2, sort_keys=True))


if __name__ == "__main__":
    main()
