#!/usr/bin/env python3
"""Gate S1 go/no-go: official Hyperlane agent through BoundaryGuard.

Checks (must both pass before S2 sample matrix):
  A) Official agent issues Dispatch eth_getLogs that the proxy audits
     (trace method eth_getLogs count > 0).
  B) Destination recipient ISM is NOT AlwaysIsm/null; one official-path
     delivery attempt is recorded honestly (pass only if process succeeds
     under non-Always ISM).

Writes data/s1_go_nogo_summary.json. Does not modify the paper.
"""

from __future__ import annotations

# --- github publish layout (auto-generated by sync_github_publish.py) ---
import sys
from pathlib import Path as _Path
_GITHUB_ROOT = _Path(__file__).resolve().parents[1]
_BG = _GITHUB_ROOT / "BoundaryGuard"
_EXP = _GITHUB_ROOT / "exp"
for _p in (_BG, _EXP):
    _s = str(_p)
    if _s not in sys.path:
        sys.path.insert(0, _s)
DATA = _GITHUB_ROOT.joinpath("data")
EXP = _EXP
ROOT = _GITHUB_ROOT
# --- end header ---

import argparse
import json
import os
import subprocess
import sys
import time
from datetime import datetime, timezone
from pathlib import Path

import relayer_official_gate3 as mainnet
import relayer_official_gate3_testnet as testnet


ROOT = _GITHUB_ROOT
DATA = DATA
OUT = DATA / "s1_go_nogo_summary.json"
MODULE_TYPE_SELECTOR = "0x6465e69f"  # moduleType()
RECIPIENT_ISM_SELECTOR = "0xe70f48ac"  # recipientIsm(address)


def eth_call(url: str, to: str, data: str) -> dict:
    return testnet.rpc(url, "eth_call", [{"to": to, "data": data}, "latest"])


def pad_addr(addr: str) -> str:
    return addr.lower().replace("0x", "").rjust(64, "0")


def probe_module_type(rpc_url: str, ism: str) -> dict:
    mt = eth_call(rpc_url, ism, MODULE_TYPE_SELECTOR)
    module_type = None
    if mt.get("ok") and mt.get("result"):
        try:
            module_type = int(mt["result"], 16)
        except ValueError:
            module_type = None
    return {
        "ok": module_type is not None,
        "ism": ism,
        "module_type": module_type,
        "is_always_ism": module_type == 6,
        "module_type_raw": mt.get("result"),
        "module_type_error": mt.get("error"),
    }


def probe_ism(dest_rpc: str, mailbox: str, recipient: str, known_ism: str | None = None) -> dict:
    if known_ism:
        out = probe_module_type(dest_rpc, known_ism)
        out["source"] = "configured_ism_address"
        return out
    data = RECIPIENT_ISM_SELECTOR + pad_addr(recipient)
    res = eth_call(dest_rpc, mailbox, data)
    if not res.get("ok") or not res.get("result") or res["result"] == "0x":
        return {
            "ok": False,
            "error": res.get("error") or "empty recipientIsm",
            "result": res.get("result"),
            "source": "mailbox.recipientIsm",
        }
    ism = "0x" + res["result"][-40:]
    out = probe_module_type(dest_rpc, ism)
    out["source"] = "mailbox.recipientIsm"
    return out


def check_a(seconds: int, port: int, skip_pull: bool) -> dict:
    if mainnet.TRACE.exists():
        mainnet.TRACE.unlink()
    if not skip_pull:
        mainnet.pull_image()
    config = mainnet.write_proxy_config("optimism", port)
    proxy = mainnet.start_proxy(config, port)
    try:
        meta = mainnet.run_relayer("optimism", port, None, seconds)
        summary = mainnet.summarize(proxy, meta)
        mainnet.SUMMARY.write_text(json.dumps(summary, indent=2, sort_keys=True) + "\n")
    finally:
        proxy.terminate()
        try:
            proxy.wait(timeout=10)
        except Exception:
            proxy.kill()
    getlogs = int(summary.get("eth_getLogs_seen") or 0)
    accepts = int(summary.get("proxy_accepts") or 0)
    inferred = accepts if getlogs == 0 else getlogs
    passed = getlogs > 0 or accepts > 0
    return {
        "name": "A_eth_getLogs_via_official_agent",
        "pass": passed,
        "eth_getLogs_seen": getlogs,
        "proxy_accepts": accepts,
        "inferred_audited_getLogs": inferred,
        "note": (
            "PASS if proxy audited Dispatch eth_getLogs from the official agent. "
            "Labeled eth_getLogs_seen requires proxy traces with method field."
        ),
        "summary_path": str(mainnet.SUMMARY.relative_to(ROOT.parent)),
        "relayer": meta,
        "proxy_methods": summary.get("proxy_methods"),
    }


def check_b(
    seconds: int,
    port: int,
    skip_pull: bool,
    *,
    recipient: str,
    known_ism: str | None,
) -> dict:
    key = testnet.load_key(None)
    addr = testnet.address_of(key)
    dst = testnet.CHAINS["sepolia"]
    ism = probe_ism(dst["rpc"], dst["mailbox"], recipient, known_ism=known_ism)
    result = {
        "name": "B_default_ism_official_delivery",
        "address": addr,
        "recipient": recipient,
        "known_ism": known_ism,
        "ism_probe": ism,
        "pass": False,
    }
    if ism.get("is_always_ism"):
        result.update({
            "pass": False,
            "blocked": True,
            "reason": (
                "Recipient ISM is AlwaysIsm/NULL (moduleType=6). "
                "S1 requires a non-Always path (Multisig / Aggregation→Multisig)."
            ),
        })
        return result
    if not ism.get("ok"):
        result.update({
            "pass": False,
            "blocked": True,
            "reason": f"Could not resolve recipient ISM: {ism}",
        })
        return result

    # Tip-focused indexing so public RPCs do not backfill ancient ranges.
    tip = testnet.rpc(testnet.CHAINS["optimismsepolia"]["rpc"], "eth_blockNumber", [])
    index_from = None
    if tip.get("ok") and tip.get("result"):
        index_from = max(0, int(tip["result"], 16) - 2000)

    cmd = [
        str(Path(sys.executable)),
        str(ROOT / "relayer_official_gate3_testnet.py"),
        "--source", "optimismsepolia",
        "--dest", "sepolia",
        "--port", str(port),
        "--seconds", str(seconds),
        "--self-dispatch",
        "--unpaid-dispatch",
        "--dispatch-delay", "60",
        "--reset-db",
        "--whitelist-sender", addr,
        "--recipient", recipient,
        # Unpaid (merkle hook only): public IGP hunters usually skip; our agent
        # uses gasPaymentEnforcement none and must still satisfy MultisigISM.
    ]
    if index_from is not None:
        cmd.extend(["--index-from", str(index_from)])
    if skip_pull:
        cmd.append("--skip-pull")
    started = time.time()
    proc = subprocess.run(cmd, cwd=str(ROOT.parent), capture_output=True, text=True, env=os.environ.copy())
    elapsed = time.time() - started
    summary = {}
    if testnet.SUMMARY.exists():
        summary = json.loads(testnet.SUMMARY.read_text())
    delivery = summary.get("delivery") or summary.get("delivery_check") or {}
    delivered = bool(delivery.get("delivered"))
    process_from = (
        (summary.get("process_tx") or {}).get("from")
        or delivery.get("process_from")
    )
    our_delivery = bool(summary.get("our_process"))
    if process_from and not summary.get("our_process"):
        our_delivery = process_from.lower() == addr.lower()
    result.update({
        "pass": bool(delivered and not ism.get("is_always_ism") and our_delivery),
        "blocked": False,
        "elapsed_s": elapsed,
        "index_from": index_from,
        "returncode": proc.returncode,
        "stdout_tail": (proc.stdout or "")[-2500:],
        "stderr_tail": (proc.stderr or "")[-1500:],
        "delivery": delivery,
        "dispatch": summary.get("dispatch"),
        "proxy_accepts": summary.get("proxy_accepts"),
        "log_stats": summary.get("log_stats"),
        "ism_module_type": ism.get("module_type"),
        "process_from": process_from,
        "process_tx": summary.get("process_tx"),
        "our_signer": addr,
        "our_delivery": our_delivery,
        "reason": (
            "Official agent delivery under non-Always ISM succeeded (our signer processed)"
            if (delivered and our_delivery)
            else (
                "Delivered on-chain but process tx was NOT from our agent signer "
                f"(process_from={process_from}); public relayer race — not an S1 PASS"
                if delivered and not our_delivery
                else "Non-Always ISM recipient resolved, but official delivery did not confirm Mailbox.delivered by our signer"
            )
        ),
    })
    return result


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--seconds-a", type=int, default=180)
    parser.add_argument("--seconds-b", type=int, default=900)
    parser.add_argument("--port-a", type=int, default=18545)
    parser.add_argument("--port-b", type=int, default=18555)
    parser.add_argument("--skip-pull", action="store_true")
    parser.add_argument("--only", choices=["a", "b", "both"], default="both")
    # Official Hyperlane Sepolia TestRecipient (Aggregation → Routing → Multisig leaf).
    parser.add_argument(
        "--recipient",
        default="0xeDc1A3EDf87187085A3ABb7A9a65E1e7aE370C07",
        help="Destination TestRecipient (default: official Hyperlane Sepolia)",
    )
    parser.add_argument(
        "--recipient-ism",
        default="0x7233d40ec42a8d0415b063fcf8a1bf4bac34dee9",
        help="Expected ISM for --recipient (Aggregation; Multisig under Routing)",
    )
    args = parser.parse_args()

    DATA.mkdir(parents=True, exist_ok=True)
    checks = []
    if args.only in ("a", "both"):
        print("==> S1 check A: eth_getLogs via official agent", flush=True)
        checks.append(check_a(args.seconds_a, args.port_a, args.skip_pull))
        print(json.dumps(checks[-1], indent=2, sort_keys=True)[:2000], flush=True)
    if args.only in ("b", "both"):
        print("==> S1 check B: non-Always ISM delivery", flush=True)
        checks.append(
            check_b(
                args.seconds_b,
                args.port_b,
                args.skip_pull,
                recipient=args.recipient,
                known_ism=args.recipient_ism,
            )
        )
        slim = {k: v for k, v in checks[-1].items() if k not in ("stdout_tail", "stderr_tail")}
        print(json.dumps(slim, indent=2, sort_keys=True), flush=True)

    overall = all(c.get("pass") for c in checks)
    payload = {
        "gate": "S1_go_nogo",
        "overall_pass": overall,
        "checks": checks,
        "observed_at": datetime.now(timezone.utc).isoformat(),
        "next": (
            "S2 sample matrix allowed"
            if overall
            else "Stop S2 sample matrix; keep S2-prep only; if B blocked on AlwaysIsm, find MultisigISM recipient before S2"
        ),
    }
    OUT.write_text(json.dumps(payload, indent=2, sort_keys=True) + "\n")
    print(json.dumps({"overall_pass": overall, "out": str(OUT)}, indent=2), flush=True)
    raise SystemExit(0 if overall else 2)


if __name__ == "__main__":
    main()
