#!/usr/bin/env python3
"""S2 strong E2E: official agent + BoundaryGuard + MultisigISM recipient.

After S1 pass, collect:
  - healthy deliveries (default target 20)
  - controlled fault classes via proxy fault_injection (omit_nth / successful_empty / truncate_last)

Does not modify the paper. Artifacts under data/strong_e2e/.
"""

from __future__ import annotations

# --- github publish layout (auto-generated by sync_github_publish.py) ---
import sys
from pathlib import Path as _Path
_GITHUB_ROOT = _Path(__file__).resolve().parents[1]
_BG = _GITHUB_ROOT / "BoundaryGuard"
_EXP = _GITHUB_ROOT / "exp"
for _p in (_BG, _EXP):
    _s = str(_p)
    if _s not in sys.path:
        sys.path.insert(0, _s)
DATA = _GITHUB_ROOT.joinpath("data")
EXP = _EXP
ROOT = _GITHUB_ROOT
# --- end header ---

import argparse
import json
import time
from datetime import datetime, timezone
from pathlib import Path

import relayer_official_gate3_testnet as t


ROOT = _GITHUB_ROOT
DATA = DATA / "strong_e2e"
RECIPIENT_FILE = DATA / "s1_multisig_recipient.txt"
ISM_FILE = DATA / "s1_multisig_ism.txt"


def load_recipient() -> tuple[str, str]:
    recipient = RECIPIENT_FILE.read_text().strip()
    ism = ISM_FILE.read_text().strip()
    return recipient, ism


def wait_our_delivery(mid: str, addr: str, timeout_s: int) -> dict:
    deadline = time.time() + timeout_s
    last: dict = {}
    while time.time() < deadline:
        try:
            d = t.mailbox_delivered("sepolia", mid) or {}
            p = t.find_process_tx("sepolia", mid) or {}
        except Exception as exc:  # noqa: BLE001 - keep polling across RPC flakes
            print(time.strftime("%H:%M:%S"), "poll_error", type(exc).__name__, exc, flush=True)
            time.sleep(10)
            continue
        delivered = bool(d.get("delivered"))
        our = bool(p.get("found") and p.get("from") and p["from"].lower() == addr.lower())
        last = {
            "message_id": mid,
            "delivered": delivered,
            "our_delivery": our,
            "delivery": d,
            "process_tx": p,
            "checked_at": datetime.now(timezone.utc).isoformat(),
        }
        if delivered and our:
            last["pass"] = True
            return last
        if delivered and not our:
            last["pass"] = False
            last["reason"] = "delivered but ProcessId sender is not our signer"
            return last
        time.sleep(15)
    last["pass"] = False
    last["reason"] = "timeout waiting for our delivery"
    return last


def append_jsonl(path: Path, row: dict) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    with path.open("a") as handle:
        handle.write(json.dumps(row, sort_keys=True) + "\n")


def summarize(path: Path, out: Path) -> dict:
    rows = [json.loads(line) for line in path.read_text().splitlines() if line.strip()] if path.exists() else []
    by_mode: dict[str, list] = {}
    for row in rows:
        by_mode.setdefault(row.get("mode", "unknown"), []).append(row)
    summary = {
        "gate": "S2_strong_e2e",
        "observed_at": datetime.now(timezone.utc).isoformat(),
        "total": len(rows),
        "passed": sum(1 for r in rows if r.get("pass")),
        "by_mode": {
            mode: {
                "n": len(items),
                "passed": sum(1 for r in items if r.get("pass")),
            }
            for mode, items in sorted(by_mode.items())
        },
        "targets": {
            "healthy": 20,
            "per_fault_class_min": 5,
            "per_fault_class_target": 10,
        },
        "artifact": str(path.relative_to(ROOT) if path.is_relative_to(ROOT) else path),
    }
    healthy_ok = summary["by_mode"].get("healthy", {}).get("passed", 0) >= 20
    fault_ok = all(
        summary["by_mode"].get(m, {}).get("passed", 0) >= 5
        for m in ("omit_nth", "successful_empty", "truncate_last")
    )
    fault_target = all(
        summary["by_mode"].get(m, {}).get("passed", 0) >= 10
        for m in ("omit_nth", "successful_empty", "truncate_last")
    )
    summary["overall_pass"] = bool(healthy_ok and fault_ok)
    summary["strong_target_pass"] = bool(healthy_ok and fault_target)
    summary["next"] = (
        "S2 PASS; open S3 full fault matrix"
        if summary["overall_pass"]
        else "Continue collecting healthy/fault samples until targets met"
    )
    out.write_text(json.dumps(summary, indent=2, sort_keys=True) + "\n")
    return summary


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--count", type=int, default=1)
    parser.add_argument("--mode", default="healthy",
                        choices=["healthy", "omit_nth", "successful_empty", "truncate_last"])
    parser.add_argument("--timeout", type=int, default=600,
                        help="Per-message wait for our ProcessId (seconds)")
    parser.add_argument("--delay", type=int, default=20,
                        help="Seconds between dispatches")
    args = parser.parse_args()

    recipient, ism = load_recipient()
    key = t.load_key(None)
    addr = t.address_of(key)
    samples = DATA / "samples.jsonl"
    DATA.mkdir(parents=True, exist_ok=True)

    print(f"S2 mode={args.mode} count={args.count} recipient={recipient} addr={addr}", flush=True)
    for i in range(args.count):
        started = time.time()
        dispatch = t.try_self_dispatch(
            "optimismsepolia", "sepolia", key, addr, recipient, unpaid=True
        )
        row = {
            "idx": i,
            "mode": args.mode,
            "provenance": (
                "live_natural_observation"
                if args.mode == "healthy"
                else "controlled_fault_injection"
            ),
            "recipient": recipient,
            "ism": ism,
            "ism_module_type": 5,
            "address": addr,
            "dispatch": dispatch,
            "started_at": datetime.now(timezone.utc).isoformat(),
        }
        if not dispatch.get("ok") or not dispatch.get("message_id"):
            row["pass"] = False
            row["reason"] = "dispatch failed"
            append_jsonl(samples, row)
            print(json.dumps(row, sort_keys=True), flush=True)
            continue
        mid = dispatch["message_id"]
        print(f"[{i+1}/{args.count}] dispatched {mid}", flush=True)
        delivery = wait_our_delivery(mid, addr, args.timeout)
        row.update(delivery)
        row["elapsed_s"] = round(time.time() - started, 2)
        append_jsonl(samples, row)
        print(json.dumps({k: row[k] for k in ("idx", "mode", "pass", "message_id", "process_tx", "elapsed_s") if k in row}, indent=2), flush=True)
        if i + 1 < args.count:
            time.sleep(args.delay)

    summary = summarize(samples, DATA / "summary.json")
    print(json.dumps(summary, indent=2, sort_keys=True), flush=True)
    raise SystemExit(0 if summary.get("passed", 0) > 0 else 2)


if __name__ == "__main__":
    main()
