#!/usr/bin/env python3
"""Summarize live natural RPC observations without relabeling failures."""

from __future__ import annotations

# --- github publish layout (auto-generated by sync_github_publish.py) ---
import sys
from pathlib import Path as _Path
_GITHUB_ROOT = _Path(__file__).resolve().parents[1]
_BG = _GITHUB_ROOT / "BoundaryGuard"
_EXP = _GITHUB_ROOT / "exp"
for _p in (_BG, _EXP):
    _s = str(_p)
    if _s not in sys.path:
        sys.path.insert(0, _s)
DATA = _GITHUB_ROOT.joinpath("data")
EXP = _EXP
ROOT = _GITHUB_ROOT
# --- end header ---

import json
from collections import defaultdict
from pathlib import Path


def main() -> None:
    rows = []
    for path in (Path("data/natural_fault_expansion.jsonl"),
                 Path("data/provider_frontier_probe.jsonl")):
        if not path.exists():
            continue
        for line in path.read_text().splitlines():
            row = json.loads(line)
            row["dataset"] = path.name
            row["method"] = {"blockHash": "eth_getLogs:blockHash",
                             "singleBlock": "eth_getLogs:singleBlock"}.get(row["method"], row["method"])
            rows.append(row)
    groups = defaultdict(lambda: {"queries": 0, "valid": 0, "silent_semantic_failure": 0,
                                  "explicit_or_transport_failure": 0})
    for row in rows:
        key = (row["chain"], row["provider"], row["method"])
        cell = groups[key]; cell["queries"] += 1
        if row["outcome"] == "ok" and row["semantic_match"]:
            cell["valid"] += 1
        elif row["outcome"] == "ok":
            cell["silent_semantic_failure"] += 1
        else:
            cell["explicit_or_transport_failure"] += 1
    silent = [r for r in rows if r["outcome"] == "ok" and not r["semantic_match"]]
    result = {
        "provenance": "live_natural_observation", "records": len(rows),
        "messages": len({(r["chain"], r["nonce"]) for r in rows}),
        "chains": sorted({r["chain"] for r in rows}),
        "providers": sorted({(r["chain"], r["provider"]) for r in rows}),
        "silent_semantic_failures": len(silent),
        "silent_failure_providers": sorted({r["provider"] for r in silent}),
        "unique_query_contexts": len({(r["chain"], r["nonce"], r["provider"], r["method"])
                                      for r in rows}),
        "silent_failure_sources": [
            {k: r.get(k) for k in ("chain", "nonce", "provider", "method", "outcome",
                                      "result_count", "matching_logs", "identity_valid")}
            for r in silent
        ],
        "groups": [{"chain": k[0], "provider": k[1], "method": k[2], **v}
                   for k, v in sorted(groups.items())],
    }
    Path("data/natural_fault_summary.json").write_text(json.dumps(result, indent=2, sort_keys=True) + "\n")
    lines = ["# Natural RPC Fault Expansion", "", "All observations below are unmodified live RPC responses.", "",
             f"- Records: {result['records']}", f"- Real messages: {result['messages']}",
             f"- Chains: {len(result['chains'])}", f"- Chain/provider pairs: {len(result['providers'])}",
             f"- Unique message/provider/method contexts: {result['unique_query_contexts']}",
             f"- Successful responses failing semantic identity: {len(silent)}",
             f"- Providers with silent semantic failures: {', '.join(result['silent_failure_providers'])}", "",
             "| Chain | Provider | Method | Valid | Silent semantic | Explicit/transport |", "|---|---|---|---:|---:|---:|"]
    for row in result["groups"]:
        lines.append(f"| {row['chain']} | {row['provider']} | {row['method']} | {row['valid']} | "
                     f"{row['silent_semantic_failure']} | {row['explicit_or_transport_failure']} |")
    lines += ["", "A successful JSON-RPC response is counted as valid only after message identity verification; "
              "empty or non-matching successful results are silent semantic failures."]
    Path("outputs/natural_fault_expansion_report.md").write_text("\n".join(lines) + "\n")
    print(json.dumps({k: result[k] for k in ("records", "messages", "chains", "providers", "silent_semantic_failures")}, indent=2))


if __name__ == "__main__":
    main()
