#!/usr/bin/env python3
"""Round-3 third-org hunt: new independent public endpoints on known silent contexts.

Only counts successful_empty. Appends to natural_fault_targeted_round3.jsonl.
Does not rewrite paper numbers unless a new silent-empty org appears.
"""

from __future__ import annotations

# --- github publish layout (auto-generated by sync_github_publish.py) ---
import sys
from pathlib import Path as _Path
_GITHUB_ROOT = _Path(__file__).resolve().parents[1]
_BG = _GITHUB_ROOT / "BoundaryGuard"
_EXP = _GITHUB_ROOT / "exp"
for _p in (_BG, _EXP):
    _s = str(_p)
    if _s not in sys.path:
        sys.path.insert(0, _s)
DATA = _GITHUB_ROOT.joinpath("data")
EXP = _EXP
ROOT = _GITHUB_ROOT
# --- end header ---

import json
import time
from collections import Counter
from pathlib import Path

from natural_fault_gate2_complete import (
    EXPANSION,
    MULTIDAY,
    TARGETED,
    load_jsonl,
    message_index,
    query_one,
)


ROOT = _GITHUB_ROOT
OUT = DATA / "natural_fault_targeted_round3.jsonl"
SUMMARY = DATA / "natural_fault_third_hunt_round3_summary.json"

# Prefer brands not already saturated in prior targeted/third hunts.
NEW_EXTRA = {
    "ethereum": {
        "mevblocker": "https://rpc.mevblocker.io",
        "mevblocker_fast": "https://rpc.mevblocker.io/fast",
        "blxr_virginia": "https://virginia.rpc.blxrbdn.com",
        "blxr_uk": "https://uk.rpc.blxrbdn.com",
        "thirdweb": "https://ethereum.rpc.thirdweb.com",
        "gashawk": "https://core.gashawk.io/rpc",
        "omniatech": "https://endpoints.omniatech.io/v1/eth/mainnet/public",
        "publicnode_https": "https://ethereum.publicnode.com",
        "llama_alt": "https://eth.llamarpc.com",
        "rpc_graffiti": "https://rpc.graffiti.farm",
    },
    "optimism": {
        "meow_op": "https://optimism.meowrpc.com",
        "omniatech_op": "https://endpoints.omniatech.io/v1/op/mainnet/public",
        "thirdweb_op": "https://optimism.rpc.thirdweb.com",
        "gatewayfm_op": "https://rpc.optimism.gateway.fm",
        "blockpi_op": "https://optimism.blockpi.network/v1/rpc/public",
        "ankr_op": "https://rpc.ankr.com/optimism",
        "publicnode_https_op": "https://optimism.publicnode.com",
        "blastapi_op": "https://optimism-mainnet.public.blastapi.io",
        "onfinality_op": "https://optimism.api.onfinality.io/public",
        "1rpc_alt": "https://1rpc.io/op",
    },
}


def silent_contexts() -> list[dict]:
    keyed = {}
    for path in (EXPANSION, MULTIDAY):
        for row in load_jsonl(path):
            empty = row.get("failure_class") == "successful_empty"
            if not empty:
                if not (
                    row.get("outcome") == "ok"
                    and row.get("semantic_match") is False
                    and (row.get("result_count") or 0) == 0
                ):
                    continue
            key = (row["chain"], int(row["nonce"]), row["method"])
            keyed[key] = {
                "chain": row["chain"],
                "nonce": int(row["nonce"]),
                "method": row["method"],
                "block": row.get("block") or row.get("origin_block_height"),
                "source_provider": row.get("provider"),
            }
    return list(keyed.values())


def already_tested() -> set[tuple]:
    keys = set()
    for path in (TARGETED, OUT, DATA / "natural_fault_third_hunt_round2.jsonl",
                 DATA / "natural_fault_third_hunt.jsonl",
                 DATA / "natural_fault_op_third_hunt.jsonl",
                 DATA / "natural_fault_provider_hunt.jsonl"):
        for row in load_jsonl(path):
            keys.add((row["chain"], int(row["nonce"]), row["provider"], row["method"]))
    return keys


def main() -> None:
    messages = message_index()
    contexts = silent_contexts()
    existing = already_tested()
    print(f"silent_contexts={len(contexts)} already_keys={len(existing)}", flush=True)

    written = 0
    empty_hits = []
    class_counts = Counter()
    OUT.parent.mkdir(parents=True, exist_ok=True)
    with OUT.open("a") as handle:
        for ctx in contexts:
            chain = ctx["chain"]
            if (chain, ctx["nonce"]) not in messages and (chain, int(ctx["nonce"])) not in {
                (k[0], k[1]) for k in messages
            }:
                # message_index keys are (chain, nonce)
                pass
            message = messages.get((chain, ctx["nonce"])) or messages.get((chain, int(ctx["nonce"])))
            if message is None:
                print("skip missing message", chain, ctx["nonce"], flush=True)
                continue
            for provider, url in NEW_EXTRA.get(chain, {}).items():
                key = (chain, ctx["nonce"], provider, ctx["method"])
                if key in existing:
                    continue
                got = query_one(url, message, ctx["method"], timeout=12.0)
                record = {
                    "provenance": "live_natural_observation",
                    "observed_at": time.time(),
                    "kind": "targeted_silent_reprobe_round3",
                    "source_provider": ctx["source_provider"],
                    "chain": chain,
                    "nonce": ctx["nonce"],
                    "block": ctx["block"],
                    "provider": provider,
                    "method": ctx["method"],
                    **got,
                }
                handle.write(json.dumps(record, sort_keys=True) + "\n")
                handle.flush()
                written += 1
                existing.add(key)
                class_counts[got["failure_class"]] += 1
                print(
                    "r3", chain, provider, ctx["method"], got["failure_class"],
                    flush=True,
                )
                if got["failure_class"] == "successful_empty":
                    empty_hits.append(record)
                time.sleep(0.08)

    # Org labels: strip _alt/_op suffixes for coarse org identity where obvious
    def org_of(provider: str) -> str:
        p = provider
        for suf in ("_alt", "_op", "_https", "_fast", "_virginia", "_uk"):
            if p.endswith(suf):
                p = p[: -len(suf)]
        # map known aliases
        aliases = {
            "1rpc": "1rpc",
            "llama": "llamarpc",
            "blastapi": "blast",
            "publicnode": "publicnode",
            "mevblocker": "mevblocker",
            "blxr": "bloxroute",
            "thirdweb": "thirdweb",
            "gashawk": "gashawk",
            "omniatech": "omnia",
            "meow": "meow",
            "gatewayfm": "gatewayfm",
            "blockpi": "blockpi",
            "ankr": "ankr",
            "onfinality": "onfinality",
            "rpc_graffiti": "graffiti",
        }
        for k, v in aliases.items():
            if p == k or p.startswith(k):
                return v
        return p

    empty_orgs = sorted({org_of(r["provider"]) for r in empty_hits})
    prior_orgs = {"1rpc", "flashbots"}
    new_orgs = sorted(set(empty_orgs) - prior_orgs)

    summary = {
        "written": written,
        "failure_class_counts": dict(class_counts),
        "successful_empty_hits": len(empty_hits),
        "successful_empty_providers": sorted({r["provider"] for r in empty_hits}),
        "successful_empty_orgs": empty_orgs,
        "new_orgs_beyond_1rpc_flashbots": new_orgs,
        "adopt_for_paper": bool(new_orgs),
        "note": (
            "Adopt into paper only if new_orgs_beyond_1rpc_flashbots is non-empty; "
            "otherwise keep third-org hunt as negative result."
        ),
    }
    SUMMARY.write_text(json.dumps(summary, indent=2, sort_keys=True) + "\n")
    print(json.dumps(summary, indent=2, sort_keys=True), flush=True)


if __name__ == "__main__":
    main()
