#!/usr/bin/env python3
"""Bounded third silent-empty org hunt (non-blocking).

Reprobes known silent contexts on new public endpoints. Caps contexts and
providers so the run finishes quickly. Does not rewrite paper Gate-2 numbers
unless a new org is found.
"""

from __future__ import annotations

# --- github publish layout (auto-generated by sync_github_publish.py) ---
import sys
from pathlib import Path as _Path
_GITHUB_ROOT = _Path(__file__).resolve().parents[1]
_BG = _GITHUB_ROOT / "BoundaryGuard"
_EXP = _GITHUB_ROOT / "exp"
for _p in (_BG, _EXP):
    _s = str(_p)
    if _s not in sys.path:
        sys.path.insert(0, _s)
DATA = _GITHUB_ROOT.joinpath("data")
EXP = _EXP
ROOT = _GITHUB_ROOT
# --- end header ---

import argparse
import json
import time
from collections import Counter
from datetime import datetime, timezone
from pathlib import Path

from natural_fault_gate2_complete import load_jsonl, message_index, query_one
from third_org_hunt_round3 import already_tested, silent_contexts


ROOT = _GITHUB_ROOT
OUT = DATA / "natural_fault_third_hunt_bounded.jsonl"
SUMMARY = DATA / "natural_fault_third_hunt_bounded_summary.json"
KNOWN = {"1rpc", "flashbots"}

# Fresh endpoints not covered by prior round3 provider keys (new names → untested keys).
FRESH_EXTRA = {
    "ethereum": {
        "cloudflare_eth": "https://cloudflare-eth.com",
        "securerpc": "https://api.securerpc.com/v1",
        "payload": "https://rpc.payload.de",
        "builder0x69": "https://rpc.builder0x69.io",
        "lokibuilder": "https://rpc.lokibuilder.xyz/rpc",
        "manually": "https://rpc.manually.eth.link",
        "ethpandaops": "https://rpc.ethpandaops.io",
        "nodies_eth": "https://eth-pokt.nodies.app",
    },
    "optimism": {
        "rockx_op": "https://optimism.public-rpc.com",
        "nodies_op": "https://op-pokt.nodies.app",
        "drpc_op": "https://optimism.drpc.org",
        "tenderly_op": "https://optimism.gateway.tenderly.co",
        "llama_op": "https://optimism.llamarpc.com",
        "omnia_fresh_op": "https://endpoints.omniatech.io/v1/op/mainnet/public",
        "publicnode_fresh_op": "https://optimism-rpc.publicnode.com",
        "blast_fresh_op": "https://optimism-mainnet.public.blastapi.io",
    },
}


def org_of(provider: str) -> str:
    p = provider
    for suf in ("_alt", "_op", "_https", "_fast", "_virginia", "_uk"):
        if p.endswith(suf):
            p = p[: -len(suf)]
    aliases = {
        "1rpc": "1rpc",
        "llama": "llamarpc",
        "blastapi": "blast",
        "publicnode": "publicnode",
        "mevblocker": "mevblocker",
        "blxr": "bloxroute",
        "thirdweb": "thirdweb",
        "gashawk": "gashawk",
        "omniatech": "omnia",
        "meow": "meow",
        "gatewayfm": "gatewayfm",
        "blockpi": "blockpi",
        "ankr": "ankr",
        "onfinality": "onfinality",
        "rpc_graffiti": "graffiti",
    }
    for k, v in aliases.items():
        if p == k or p.startswith(k):
            return v
    return p


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--max-contexts", type=int, default=12)
    parser.add_argument("--max-providers-per-chain", type=int, default=4)
    parser.add_argument("--timeout", type=float, default=12.0)
    args = parser.parse_args()

    messages = message_index()
    contexts = silent_contexts()[: args.max_contexts]
    existing = already_tested()
    # Also skip keys already in our bounded out file.
    for row in load_jsonl(OUT):
        existing.add((row["chain"], int(row["nonce"]), row["provider"], row["method"]))

    print(
        f"contexts={len(contexts)} existing_keys={len(existing)} "
        f"max_providers/chain={args.max_providers_per_chain}",
        flush=True,
    )
    written = 0
    empty_hits = []
    class_counts = Counter()
    OUT.parent.mkdir(parents=True, exist_ok=True)
    if OUT.exists():
        OUT.unlink()
    with OUT.open("w") as handle:
        for ctx in contexts:
            chain = ctx["chain"]
            message = messages.get((chain, ctx["nonce"])) or messages.get((chain, int(ctx["nonce"])))
            if message is None:
                continue
            providers = list(FRESH_EXTRA.get(chain, {}).items())[: args.max_providers_per_chain]
            for provider, url in providers:
                key = (chain, ctx["nonce"], provider, ctx["method"])
                if key in existing:
                    continue
                got = query_one(url, message, ctx["method"], timeout=args.timeout)
                record = {
                    "provenance": "live_natural_observation",
                    "observed_at": datetime.now(timezone.utc).isoformat(),
                    "kind": "bounded_third_org_hunt",
                    "source_provider": ctx["source_provider"],
                    "chain": chain,
                    "nonce": ctx["nonce"],
                    "block": ctx["block"],
                    "provider": provider,
                    "org": org_of(provider),
                    "method": ctx["method"],
                    **got,
                }
                handle.write(json.dumps(record, sort_keys=True) + "\n")
                handle.flush()
                written += 1
                existing.add(key)
                class_counts[got.get("failure_class") or "unknown"] += 1
                print(
                    "hunt", chain, provider, ctx["method"], got.get("failure_class"),
                    flush=True,
                )
                if got.get("failure_class") == "successful_empty":
                    empty_hits.append(record)
                time.sleep(0.05)

    new_orgs = sorted({r["org"] for r in empty_hits if r["org"] not in KNOWN})
    summary = {
        "gate": "third_org_silent_hunt_bounded",
        "provenance": "live_natural_observation",
        "observed_at": datetime.now(timezone.utc).isoformat(),
        "written": written,
        "max_contexts": args.max_contexts,
        "max_providers_per_chain": args.max_providers_per_chain,
        "failure_class_counts": dict(class_counts),
        "successful_empty_hits": len(empty_hits),
        "known_silent_orgs": sorted(KNOWN),
        "new_orgs_beyond_1rpc_flashbots": new_orgs,
        "meets_three_silent_providers": len(KNOWN | set(new_orgs)) >= 3,
        "adopt_for_paper": bool(new_orgs),
        "pass": True,  # non-blocking: hunt completed; third org is optional
        "note": "Non-blocking. If new_orgs empty, keep Gate-2 two-org limitation.",
        "artifact": str(OUT.relative_to(ROOT)),
    }
    SUMMARY.write_text(json.dumps(summary, indent=2, sort_keys=True) + "\n")
    print(json.dumps(summary, indent=2, sort_keys=True))
    raise SystemExit(0)


if __name__ == "__main__":
    main()
