#!/usr/bin/env python3
"""Decompose healthy-path throughput and tail latency from saved concurrency runs.

Default: analyze data/strong_e2e/concurrent_throughput.json (no live RPCs).
Optional --live delegates to concurrent_throughput.py with a wider sweep after
the Gate-2 recurrence job is idle.
"""

from __future__ import annotations

# --- github publish layout (auto-generated by sync_github_publish.py) ---
import sys
from pathlib import Path as _Path
_GITHUB_ROOT = _Path(__file__).resolve().parents[1]
_BG = _GITHUB_ROOT / "BoundaryGuard"
_EXP = _GITHUB_ROOT / "exp"
for _p in (_BG, _EXP):
    _s = str(_p)
    if _s not in sys.path:
        sys.path.insert(0, _s)
DATA = _GITHUB_ROOT.joinpath("data")
EXP = _EXP
ROOT = _GITHUB_ROOT
# --- end header ---

import argparse
import json
import subprocess
import sys
from datetime import datetime, timezone
from pathlib import Path


ROOT = _GITHUB_ROOT
DATA = DATA / "strong_e2e"
INP = DATA / "concurrent_throughput.json"
OUT = DATA / "throughput_root_cause.json"


def pct(numer: float, denom: float) -> float | None:
    if denom == 0:
        return None
    return 100.0 * (numer - denom) / denom


def analyze(payload: dict) -> dict:
    by = {(row["mode"], row["concurrency"]): row for row in payload.get("rows") or []}
    concs = sorted({c for _, c in by})
    rows = []
    for c in concs:
        un = by.get(("unchecked", c))
        dual = by.get(("always_dual", c))
        bg = by.get(("boundaryguard", c))
        if not un or not dual or not bg:
            continue
        bg_p50 = bg["p50_ms"]
        bg_p95 = bg["p95_ms"]
        dual_p50 = dual["p50_ms"]
        dual_p95 = dual["p95_ms"]
        un_p50 = un["p50_ms"]
        # Sequential extra work vs a single log: BG median minus unchecked median.
        extra_p50 = bg_p50 - un_p50
        extra_p95 = bg_p95 - un["p95_ms"]
        tail_ratio = None if bg_p50 <= 0 else bg_p95 / bg_p50
        dual_tail = None if dual_p50 <= 0 else dual_p95 / dual_p50
        rows.append(
            {
                "concurrency": c,
                "unchecked_qps": un["throughput_qps"],
                "dual_qps": dual["throughput_qps"],
                "bg_qps": bg["throughput_qps"],
                "bg_over_dual_qps": None
                if dual["throughput_qps"] <= 0
                else bg["throughput_qps"] / dual["throughput_qps"],
                "unchecked_p50_ms": un_p50,
                "unchecked_p95_ms": un["p95_ms"],
                "dual_p50_ms": dual_p50,
                "dual_p95_ms": dual_p95,
                "bg_p50_ms": bg_p50,
                "bg_p95_ms": bg_p95,
                "bg_p95_over_p50": tail_ratio,
                "dual_p95_over_p50": dual_tail,
                "bg_extra_p50_vs_unchecked_ms": extra_p50,
                "bg_extra_p95_vs_unchecked_ms": extra_p95,
                "bg_cu": bg.get("cu_est"),
                "dual_cu": dual.get("cu_est"),
                "cu_saving_pct": None
                if not dual.get("cu_est")
                else 100.0 * (1.0 - bg["cu_est"] / dual["cu_est"]),
                "hypothesis": (
                    "BoundaryGuard P95/P50 >> always-dual indicates sequential "
                    "boundary eth_call on the healthy path, not log-query cost. "
                    "Always-dual P50 is close to two sequential logs; BG P50 is "
                    "closer to one log plus cheaper calls, but the tail is dominated "
                    "by slow boundary providers."
                ),
            }
        )
    return {
        "gate": "throughput_root_cause",
        "provenance": payload.get("provenance") or "saved_concurrency_trace",
        "analyzed_at": datetime.now(timezone.utc).isoformat(),
        "source_observed_at": payload.get("observed_at"),
        "n": payload.get("n"),
        "width": payload.get("width"),
        "rows": rows,
        "headline": rows,
    }


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--live", action="store_true",
                        help="Run concurrent_throughput.py --concurrencies 1,2,4,8,16")
    parser.add_argument("--concurrencies", default="1,2,4,8,16")
    args = parser.parse_args()
    if args.live:
        cmd = [
            sys.executable,
            str(EXP / "concurrent_throughput.py"),
            "--concurrencies",
            args.concurrencies,
        ]
        print("running", " ".join(cmd), flush=True)
        completed = subprocess.run(cmd, cwd=str(ROOT), check=False)
        if completed.returncode not in (0, 2):
            raise SystemExit(completed.returncode)
    if not INP.exists():
        raise SystemExit(f"missing {INP}")
    payload = json.loads(INP.read_text())
    summary = analyze(payload)
    summary["live_rerun"] = bool(args.live)
    OUT.write_text(json.dumps(summary, indent=2, sort_keys=True) + "\n")
    print(json.dumps(summary, indent=2, sort_keys=True))


if __name__ == "__main__":
    main()
