#!/usr/bin/env python3
"""Feasibility-only replay on an unmodified Wormhole message trace.

This is not a paper experiment. It asks a narrower gate question: when real
message arrivals are bursty and chains share an audit budget, can an online
hint-aware scheduler outperform strong static-sqrt and max-age baselines
without injecting failures into the workload?
"""

from __future__ import annotations

# --- github publish layout (auto-generated by sync_github_publish.py) ---
import sys
from pathlib import Path as _Path
_GITHUB_ROOT = _Path(__file__).resolve().parents[1]
_BG = _GITHUB_ROOT / "BoundaryGuard"
_EXP = _GITHUB_ROOT / "exp"
for _p in (_BG, _EXP):
    _s = str(_p)
    if _s not in sys.path:
        sys.path.insert(0, _s)
DATA = _GITHUB_ROOT.joinpath("data")
EXP = _EXP
ROOT = _GITHUB_ROOT
# --- end header ---

import argparse
import gzip
import json
import math
from collections import defaultdict, deque
from dataclasses import dataclass
from datetime import datetime
from pathlib import Path
from statistics import mean


def timestamp(value: str) -> float:
    return datetime.fromisoformat(value.replace("Z", "+00:00")).timestamp()


def percentile(values: list[float], q: float) -> float:
    if not values:
        return float("nan")
    ordered = sorted(values)
    pos = (len(ordered) - 1) * q
    lo = math.floor(pos)
    hi = math.ceil(pos)
    if lo == hi:
        return ordered[lo]
    return ordered[lo] * (hi - pos) + ordered[hi] * (pos - lo)


@dataclass
class Result:
    policy: str
    delays: list[float]
    by_chain: dict[str, list[float]]
    audits: int
    empty_audits: int
    audit_counts: dict[str, int]

    def summary(self) -> dict[str, object]:
        chain_p95 = {
            chain: round(percentile(delays, 0.95), 3)
            for chain, delays in sorted(self.by_chain.items())
            if delays
        }
        return {
            "policy": self.policy,
            "events": len(self.delays),
            "mean_s": round(mean(self.delays), 3),
            "p50_s": round(percentile(self.delays, 0.50), 3),
            "p95_s": round(percentile(self.delays, 0.95), 3),
            "p99_s": round(percentile(self.delays, 0.99), 3),
            "worst_chain_p95_s": round(max(chain_p95.values()), 3),
            "empty_audit_fraction": round(self.empty_audits / self.audits, 4),
            "audit_counts": dict(sorted(self.audit_counts.items())),
            "chain_p95_s": chain_p95,
        }


def load_events(path: Path, chains: list[str]) -> dict[str, list[float]]:
    selected = set(chains)
    events: dict[str, list[float]] = {chain: [] for chain in chains}
    seen: set[str] = set()
    with gzip.open(path, "rt", encoding="utf-8") as source:
        for line in source:
            row = json.loads(line)
            chain = row.get("src_chain")
            tx_id = row.get("tx_id")
            if chain not in selected or not tx_id or tx_id in seen:
                continue
            seen.add(tx_id)
            events[chain].append(timestamp(row["tx_timestamp"]))
    for values in events.values():
        values.sort()
    return events


def run_policy(
    policy: str,
    events: dict[str, list[float]],
    train_start: float,
    eval_start: float,
    eval_end: float,
    slot_seconds: float,
    max_audit_gap: float,
    event_sla: float,
) -> Result:
    chains = list(events)
    train_duration = eval_start - train_start
    rates = {
        chain: sum(train_start <= t < eval_start for t in values) / train_duration
        for chain, values in events.items()
    }
    weights = {chain: math.sqrt(max(rates[chain], 1e-12)) for chain in chains}
    total_weight = sum(weights.values())
    target_share = {chain: weights[chain] / total_weight for chain in chains}

    eval_events = {
        chain: [t for t in values if eval_start <= t <= eval_end]
        for chain, values in events.items()
    }
    pointers = {chain: 0 for chain in chains}
    pending = {chain: deque() for chain in chains}
    last_audit = {chain: eval_start for chain in chains}
    audit_counts = {chain: 0 for chain in chains}
    delays: list[float] = []
    by_chain: dict[str, list[float]] = defaultdict(list)
    empty_audits = 0
    audits = 0

    def add_arrivals(now: float) -> None:
        for chain in chains:
            values = eval_events[chain]
            idx = pointers[chain]
            while idx < len(values) and values[idx] <= now:
                pending[chain].append(values[idx])
                idx += 1
            pointers[chain] = idx

    def choose(now: float) -> str:
        overdue = [chain for chain in chains if now - last_audit[chain] >= max_audit_gap]
        if overdue:
            return max(overdue, key=lambda chain: (now - last_audit[chain], chain))

        if policy == "max_age":
            return max(chains, key=lambda chain: (now - last_audit[chain], chain))

        if policy == "active_max_age":
            active = [chain for chain in chains if pending[chain]]
            if active:
                return max(
                    active,
                    key=lambda chain: (now - pending[chain][0], len(pending[chain])),
                )
            return max(chains, key=lambda chain: (now - last_audit[chain], chain))

        if policy in {"static_sqrt", "active_static_sqrt"}:
            next_audit_number = audits + 1
            candidates = chains
            if policy == "active_static_sqrt":
                active = [chain for chain in chains if pending[chain]]
                if active:
                    candidates = active
            return max(
                candidates,
                key=lambda chain: (
                    target_share[chain] * next_audit_number - audit_counts[chain],
                    now - last_audit[chain],
                ),
            )

        if policy in {"backlog_age", "deadline_backlog"}:
            active = [chain for chain in chains if pending[chain]]
            if not active:
                return max(chains, key=lambda chain: (now - last_audit[chain], chain))
            if policy == "deadline_backlog":
                urgent = [chain for chain in active if now - pending[chain][0] >= event_sla]
                if urgent:
                    return max(
                        urgent,
                        key=lambda chain: (now - pending[chain][0], len(pending[chain])),
                    )
            return max(
                active,
                key=lambda chain: (
                    sum(now - arrival for arrival in pending[chain]),
                    len(pending[chain]),
                    now - last_audit[chain],
                ),
            )

        raise ValueError(policy)

    now = eval_start + slot_seconds
    flush_end = eval_end + max_audit_gap
    while now <= flush_end:
        add_arrivals(min(now, eval_end))
        chain = choose(now)
        audits += 1
        audit_counts[chain] += 1
        last_audit[chain] = now
        if not pending[chain]:
            empty_audits += 1
        else:
            while pending[chain]:
                arrival = pending[chain].popleft()
                delay = now - arrival
                delays.append(delay)
                by_chain[chain].append(delay)
        if now >= eval_end and all(not queue for queue in pending.values()):
            if all(pointers[c] >= len(eval_events[c]) for c in chains):
                break
        now += slot_seconds

    return Result(policy, delays, dict(by_chain), audits, empty_audits, audit_counts)


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("trace", type=Path)
    parser.add_argument(
        "--chains",
        default="Ethereum,Arbitrum,Optimism,Polygon",
        help="Comma-separated source chains",
    )
    parser.add_argument("--slots", default="10,30,60", help="Audit slot intervals in seconds")
    parser.add_argument("--max-gap", type=float, default=300.0)
    parser.add_argument("--event-sla", type=float, default=120.0)
    args = parser.parse_args()

    chains = args.chains.split(",")
    events = load_events(args.trace, chains)
    all_times = [t for values in events.values() for t in values]
    start = min(all_times)
    end = max(all_times)
    split = start + 0.20 * (end - start)

    print(json.dumps({
        "chains": chains,
        "counts": {chain: len(events[chain]) for chain in chains},
        "trace_days": round((end - start) / 86400, 3),
        "train_days": round((split - start) / 86400, 3),
        "eval_days": round((end - split) / 86400, 3),
        "note": "Unmodified arrivals; push hints are assumed visible; audits verify prefixes.",
    }, sort_keys=True))

    for slot in (float(value) for value in args.slots.split(",")):
        for policy in (
            "static_sqrt",
            "active_static_sqrt",
            "max_age",
            "active_max_age",
            "backlog_age",
            "deadline_backlog",
        ):
            result = run_policy(
                policy,
                events,
                start,
                split,
                end,
                slot,
                args.max_gap,
                args.event_sla,
            )
            row = result.summary()
            row["slot_seconds"] = slot
            row["max_audit_gap_s"] = args.max_gap
            row["event_sla_s"] = args.event_sla
            print(json.dumps(row, sort_keys=True))


if __name__ == "__main__":
    main()
