#!/usr/bin/env python3
"""Offline feasibility gates for Hyperlane verified historical backfill."""

from __future__ import annotations

# --- github publish layout (auto-generated by sync_github_publish.py) ---
import sys
from pathlib import Path as _Path
_GITHUB_ROOT = _Path(__file__).resolve().parents[1]
_BG = _GITHUB_ROOT / "BoundaryGuard"
_EXP = _GITHUB_ROOT / "exp"
for _p in (_BG, _EXP):
    _s = str(_p)
    if _s not in sys.path:
        sys.path.insert(0, _s)
DATA = _GITHUB_ROOT.joinpath("data")
EXP = _EXP
ROOT = _GITHUB_ROOT
# --- end header ---

import json
import math
import statistics
import time
import urllib.request
from collections import defaultdict
from pathlib import Path

from rpc_probe import CHAINS


ROOT = _GITHUB_ROOT
MESSAGES = DATA / "hyperlane_messages.jsonl"
PROBES = DATA / "rpc_probe.jsonl"
OUTPUT = DATA / "backfill_feasibility.json"
NONCE_SELECTOR = "0xaffed0e0"


def rpc(url: str, method: str, params: list, timeout: float = 20.0) -> dict:
    payload = json.dumps(
        {"jsonrpc": "2.0", "id": 1, "method": method, "params": params}
    ).encode()
    request = urllib.request.Request(
        url,
        data=payload,
        headers={"Content-Type": "application/json", "User-Agent": "BoundaryGuard-backfill/0.1"},
        method="POST",
    )
    started = time.perf_counter()
    try:
        with urllib.request.urlopen(request, timeout=timeout) as response:
            body = json.loads(response.read())
        return {
            "ok": "result" in body and body.get("result") is not None,
            "result": body.get("result"),
            "error": body.get("error"),
            "latency_ms": round((time.perf_counter() - started) * 1000, 3),
        }
    except Exception as exc:
        return {
            "ok": False,
            "result": None,
            "error": repr(exc),
            "latency_ms": round((time.perf_counter() - started) * 1000, 3),
        }


def address(value: str) -> str:
    return "0x" + value.removeprefix("\\x").removeprefix("0x")


def load_messages() -> dict[str, list[dict]]:
    grouped: dict[str, list[dict]] = defaultdict(list)
    with MESSAGES.open() as handle:
        for line in handle:
            row = json.loads(line)
            grouped[row["chain"]].append(row)
    for rows in grouped.values():
        rows.sort(key=lambda row: row["nonce"])
    return grouped


def boundary_gate(messages: dict[str, list[dict]]) -> dict:
    results = {}
    for chain, rows in sorted(messages.items()):
        mailbox = address(rows[0]["origin_mailbox"])
        points = {
            "before_first": max(0, rows[0]["origin_block_height"] - 1),
            "at_first": rows[0]["origin_block_height"],
            "at_last": rows[-1]["origin_block_height"],
        }
        observations = {}
        for provider, url in CHAINS[chain]["urls"].items():
            observations[provider] = {}
            for label, block in points.items():
                response = rpc(
                    url,
                    "eth_call",
                    [{"to": mailbox, "data": NONCE_SELECTOR}, hex(block)],
                )
                value = None
                if response["ok"] and isinstance(response["result"], str):
                    value = int(response["result"], 16)
                observations[provider][label] = {
                    "block": block, "nonce_state": value, **response
                }
        expected_delta = rows[-1]["nonce"] - rows[0]["nonce"] + 1
        usable = []
        for provider, obs in observations.items():
            start = obs["before_first"]["nonce_state"]
            end = obs["at_last"]["nonce_state"]
            if start is not None and end is not None:
                usable.append((provider, start, end))
        provider, start, end = usable[0] if usable else (None, None, None)
        observed_delta = None if start is None or end is None else end - start
        results[chain] = {
            "mailbox": mailbox,
            "usable_provider": provider,
            "first_message_nonce": rows[0]["nonce"],
            "last_message_nonce": rows[-1]["nonce"],
            "expected_message_count": expected_delta,
            "state_delta": observed_delta,
            # A delta larger than the downloaded nonce window is expected when
            # its first block also contains older messages excluded by the
            # Explorer nonce cutoff.  The state is still a usable exact boundary
            # for a block-aligned backfill.
            "passes": observed_delta is not None and observed_delta >= expected_delta,
            "observations": observations,
        }
    return results


def action_profiles() -> dict[str, list[dict]]:
    samples: dict[tuple[str, str, int], list[float]] = defaultdict(list)
    with PROBES.open() as handle:
        for line in handle:
            row = json.loads(line)
            if row.get("probe") != "range_cost" or row.get("outcome") != "ok":
                continue
            span = row.get("range_blocks")
            if isinstance(span, int):
                samples[(row["chain"], row["provider"], span)].append(row["latency_ms"] / 1000)
    profiles: dict[str, list[dict]] = defaultdict(list)
    for (chain, provider, span), latencies in samples.items():
        # The original probe repeated each action three times. Require all three
        # successes so the oracle does not exploit a flaky action.
        if len(latencies) < 3:
            continue
        profiles[chain].append(
            {
                "provider": provider,
                "span": span,
                "latency_s": statistics.median(latencies),
                "throughput_blocks_s": span / statistics.median(latencies),
            }
        )
    return profiles


def oracle_gate(messages: dict[str, list[dict]], profiles: dict[str, list[dict]]) -> dict:
    """Upper-bound test using perfect knowledge of message positions.

    The strong static baseline chooses one empirically reliable provider/span
    for the whole chain.  The interval oracle may choose the fastest reliable
    action independently for each gap between adjacent real messages.  Because
    the current action model has no density-dependent failures, this is an
    intentionally optimistic upper bound: if it cannot win, an online planner
    cannot win from these measurements.
    """
    results = {}
    for chain, rows in sorted(messages.items()):
        actions = profiles.get(chain, [])
        if not actions:
            results[chain] = {"passes": False, "error": "no fully reliable actions"}
            continue
        lo = rows[0]["origin_block_height"]
        hi = rows[-1]["origin_block_height"]
        total_blocks = hi - lo + 1
        static_costs = []
        for action in actions:
            requests = math.ceil(total_blocks / action["span"])
            static_costs.append((requests * action["latency_s"], requests, action))
        static_time, static_requests, static_action = min(static_costs, key=lambda item: item[0])

        # With the current probes, action cost does not depend on event density
        # or position.  Therefore the continuous relaxation is a valid oracle
        # upper bound: use the best measured blocks/second action everywhere,
        # with a proportional final request.  Any online policy can only add
        # learning/verification overhead under this measured model.
        best_rate_action = max(actions, key=lambda action: action["throughput_blocks_s"])
        oracle_time = total_blocks / best_rate_action["throughput_blocks_s"]
        oracle_requests = total_blocks / best_rate_action["span"]
        choices = {(best_rate_action["provider"], best_rate_action["span"]): 1}
        improvement = (static_time - oracle_time) / static_time if static_time else 0.0
        results[chain] = {
            "block_range": [lo, hi],
            "total_blocks": total_blocks,
            "static": {"time_s": static_time, "requests": static_requests, **static_action},
            "oracle": {
                "time_s": oracle_time,
                "requests": oracle_requests,
                "interval_choices": [
                    {"provider": key[0], "span": key[1], "intervals": count}
                    for key, count in sorted(choices.items())
                ],
            },
            "improvement_pct": improvement * 100,
            "passes_15pct": improvement >= 0.15,
        }
    aggregate_static = sum(row.get("static", {}).get("time_s", 0) for row in results.values())
    aggregate_oracle = sum(row.get("oracle", {}).get("time_s", 0) for row in results.values())
    aggregate_improvement = (
        (aggregate_static - aggregate_oracle) / aggregate_static if aggregate_static else 0.0
    )
    return {
        "per_chain": results,
        "aggregate": {
            "static_time_s": aggregate_static,
            "oracle_time_s": aggregate_oracle,
            "improvement_pct": aggregate_improvement * 100,
            "passes_15pct": aggregate_improvement >= 0.15,
        },
        "limitation": "Probe data has no density-dependent latency or semantic outcomes; this is only an upper-bound screen over measured reliable actions.",
    }


def main() -> None:
    messages = load_messages()
    result = {
        "generated_at": time.time(),
        "boundary_gate": boundary_gate(messages),
        "oracle_gate": oracle_gate(messages, action_profiles()),
    }
    OUTPUT.write_text(json.dumps(result, indent=2, sort_keys=True) + "\n")
    print(json.dumps(result, indent=2, sort_keys=True))


if __name__ == "__main__":
    main()
