#!/usr/bin/env python3
"""Verify data/experiment_manifest.json SHA-256 inventory."""

from __future__ import annotations

# --- github publish layout (auto-generated by sync_github_publish.py) ---
import sys
from pathlib import Path as _Path
_GITHUB_ROOT = _Path(__file__).resolve().parents[1]
_BG = _GITHUB_ROOT / "BoundaryGuard"
_EXP = _GITHUB_ROOT / "exp"
for _p in (_BG, _EXP):
    _s = str(_p)
    if _s not in sys.path:
        sys.path.insert(0, _s)
DATA = _GITHUB_ROOT.joinpath("data")
EXP = _EXP
ROOT = _GITHUB_ROOT
# --- end header ---

import hashlib
import json
import sys
from pathlib import Path

ROOT = _GITHUB_ROOT
MANIFEST = ROOT / "data" / "experiment_manifest.json"


def sha256(path: Path) -> str:
    digest = hashlib.sha256()
    with path.open("rb") as handle:
        for chunk in iter(lambda: handle.read(1024 * 1024), b""):
            digest.update(chunk)
    return digest.hexdigest()


def main() -> int:
    if not MANIFEST.exists():
        print(f"missing {MANIFEST}", file=sys.stderr)
        return 2
    data = json.loads(MANIFEST.read_text())
    files = data.get("files") or []
    bad: list[str] = []
    for ent in files:
        rel = ent["path"]
        path = ROOT / rel
        if not path.exists():
            bad.append(f"missing\t{rel}")
            continue
        digest = sha256(path)
        size = path.stat().st_size
        if digest != ent.get("sha256"):
            bad.append(f"sha256\t{rel}")
        if size != ent.get("bytes"):
            bad.append(f"bytes\t{rel}")
    print(f"frozen_at={data.get('frozen_at')}")
    print(f"files={len(files)}")
    if bad:
        print("FAIL")
        for line in bad:
            print(line)
        return 1
    print("OK")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
