#!/usr/bin/env python3
"""Report cost-model MAE denominators from boundaryguard_cost_sweep.json.

The JSON field mean_abs_model_error_pp is the mean over model_vs_measured
(22 populated matrix cells). points is the analytic sensitivity grid, not
the MAE sample. The paper's single-fault n>=8 figure is the four-cell subset.
"""

from __future__ import annotations

# --- github publish layout (auto-generated by sync_github_publish.py) ---
import sys
from pathlib import Path as _Path
_GITHUB_ROOT = _Path(__file__).resolve().parents[1]
_BG = _GITHUB_ROOT / "BoundaryGuard"
_EXP = _GITHUB_ROOT / "exp"
for _p in (_BG, _EXP):
    _s = str(_p)
    if _s not in sys.path:
        sys.path.insert(0, _s)
DATA = _GITHUB_ROOT.joinpath("data")
EXP = _EXP
ROOT = _GITHUB_ROOT
# --- end header ---

import json
import statistics
from pathlib import Path

ROOT = _GITHUB_ROOT
DATA = DATA
SWEEP = DATA / "boundaryguard_cost_sweep.json"


def main() -> int:
    payload = json.loads(SWEEP.read_text())
    rows = payload["model_vs_measured"]
    subset = [row for row in rows if row["f_requested"] == 1 and row["n"] >= 8]
    overall = statistics.fmean(row["abs_error_pp"] for row in rows)
    subset_mae = statistics.fmean(row["abs_error_pp"] for row in subset)
    print(f"analytic_grid_points={payload['points']}")
    print(f"measured_cells={len(rows)}")
    print(f"mean_abs_model_error_pp={overall:.6f}")
    print(f"single_fault_n_ge_8_cells={len(subset)}")
    print(f"single_fault_n_ge_8_mae_pp={subset_mae:.6f}")
    stored = payload["mean_abs_model_error_pp"]
    if abs(stored - overall) > 1e-9:
        print(f"FAIL stored mean {stored} != recomputed {overall}")
        return 1
    print("OK")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
