#!/usr/bin/env python3
"""Minimal second-protocol portability check for BoundaryGuard (Wormhole).

Self-contained: no imports from the rest of the repo. Run locally, since the
sandbox proxy blocks public RPC endpoints.

What it does, per window of `--width` finalized Ethereum blocks:
  1. boundary  : eth_call Wormhole Core `nextSequence(emitter)` at (start-1) and (end)
                 -> expected number of messages in the window
  2. logs      : eth_getLogs for `LogMessagePublished` from that emitter
  3. audit     : boundary delta == log count ?   (the Eq.(1) test, count form)
  4. injection : drop one returned log and re-run the audit; it must now fail

Step 4 is what makes this a *detection* result rather than only a consistency
check: it shows the Wormhole boundary would catch a silent omission.

Usage:
    python3 wormhole_min_check.py                 # 12 windows, default RPCs
    python3 wormhole_min_check.py --windows 24
    python3 wormhole_min_check.py --rpc https://your-endpoint

Output: data/wormhole_min_check.json
"""

from __future__ import annotations

# --- github publish layout (auto-generated by sync_github_publish.py) ---
import sys
from pathlib import Path as _Path
_GITHUB_ROOT = _Path(__file__).resolve().parents[1]
_BG = _GITHUB_ROOT / "BoundaryGuard"
_EXP = _GITHUB_ROOT / "exp"
for _p in (_BG, _EXP):
    _s = str(_p)
    if _s not in sys.path:
        sys.path.insert(0, _s)
DATA = _GITHUB_ROOT.joinpath("data")
EXP = _EXP
ROOT = _GITHUB_ROOT
# --- end header ---

import argparse
import json
import time
import urllib.error
import urllib.request
from pathlib import Path

# Wormhole Core bridge on Ethereum mainnet.
WH_CORE = "0x98f3c9e6E3fAce36bAAd05FE09d375Ef1464288B"
# keccak("LogMessagePublished(address,uint64,uint32,bytes,uint8)")
WH_TOPIC = "0x6eb224fb001ed210e379b335e35efe88672a8ce935d981a6896b27ffdf52a3b2"
# selector for nextSequence(address)
WH_NEXT_SEQ = "0x4cf842b5"
# Portal Token Bridge: the highest-volume Wormhole emitter on Ethereum.
DEFAULT_EMITTER = "0x3ee18B2214AFF97000D974cf647E7C347E8fa585"

DEFAULT_RPCS = [
    "https://mainnet.gateway.tenderly.co",
    "https://0xrpc.io/eth",
    "https://eth.drpc.org",
    "https://gateway.tenderly.co/public/mainnet",
]

DATA = DATA


def rpc(url: str, method: str, params: list, timeout: float = 20.0) -> dict:
    body = json.dumps({"jsonrpc": "2.0", "id": 1, "method": method, "params": params})
    req = urllib.request.Request(
        url, data=body.encode(), headers={"content-type": "application/json"}
    )
    try:
        with urllib.request.urlopen(req, timeout=timeout) as resp:
            payload = json.loads(resp.read())
    except urllib.error.HTTPError as exc:
        return {"outcome": "http_error", "error": f"{exc.code}"}
    except Exception as exc:  # noqa: BLE001 - transport bucket
        return {"outcome": "transport_error", "error": type(exc).__name__}
    if "error" in payload:
        return {"outcome": "rpc_error", "error": str(payload["error"])[:160]}
    return {"outcome": "ok", "result": payload.get("result")}


def first_live_rpc(urls: list[str]) -> tuple[str, int] | tuple[None, None]:
    for url in urls:
        resp = rpc(url, "eth_blockNumber", [], timeout=12.0)
        if resp["outcome"] == "ok":
            return url, int(resp["result"], 16)
        print(f"  [skip] {url}: {resp['outcome']}")
    return None, None


def next_sequence(url: str, emitter: str, block: int) -> int | None:
    data = WH_NEXT_SEQ + emitter.lower().removeprefix("0x").zfill(64)
    resp = rpc(url, "eth_call", [{"to": WH_CORE, "data": data}, hex(block)])
    if resp["outcome"] != "ok" or not isinstance(resp.get("result"), str):
        return None
    raw = resp["result"]
    return int(raw, 16) if len(raw) > 2 else None


def audit(expected: int, observed_count: int) -> bool:
    """Count form of the Eq.(1) prefix test used by selective localization."""
    return expected == observed_count


def main() -> None:
    ap = argparse.ArgumentParser()
    ap.add_argument("--windows", type=int, default=12)
    ap.add_argument("--width", type=int, default=200, help="blocks per window")
    ap.add_argument("--confirmations", type=int, default=64)
    ap.add_argument("--emitter", default=DEFAULT_EMITTER)
    ap.add_argument("--rpc", action="append", default=None)
    args = ap.parse_args()

    urls = args.rpc or DEFAULT_RPCS
    url, tip = first_live_rpc(urls)
    if url is None:
        raise SystemExit("no reachable RPC endpoint; pass --rpc <url>")
    print(f"rpc={url}  tip={tip}  emitter={args.emitter}\n")

    topic1 = "0x" + args.emitter.lower().removeprefix("0x").zfill(64)
    cases: list[dict] = []
    readable = matched = injected_caught = 0

    for i in range(args.windows):
        end = tip - args.confirmations - i * (args.width + 50)
        start = end - args.width + 1
        if start <= 0:
            break

        t0 = time.perf_counter()
        before = next_sequence(url, args.emitter, start - 1)
        after = next_sequence(url, args.emitter, end)
        boundary_ms = (time.perf_counter() - t0) * 1000

        if before is None or after is None:
            cases.append({"start": start, "end": end, "boundary_ok": False})
            print(f"  [{i+1}/{args.windows}] {start}-{end}  boundary UNREADABLE")
            continue
        readable += 1
        expected = after - before

        t1 = time.perf_counter()
        logs_resp = rpc(url, "eth_getLogs", [{
            "fromBlock": hex(start), "toBlock": hex(end),
            "address": WH_CORE, "topics": [WH_TOPIC, topic1],
        }])
        logs_ms = (time.perf_counter() - t1) * 1000
        logs = logs_resp.get("result") if logs_resp["outcome"] == "ok" else None
        count = len(logs) if isinstance(logs, list) else None

        ok = count is not None and audit(expected, count)
        matched += bool(ok)

        # Injection: drop one event and confirm the boundary now rejects.
        caught = None
        if ok and count and count > 0:
            caught = not audit(expected, count - 1)
            injected_caught += bool(caught)

        cases.append({
            "start": start, "end": end, "boundary_ok": True,
            "expected_delta": expected, "log_count": count,
            "prefix_match": ok, "omission_detected_after_injection": caught,
            "boundary_ms": round(boundary_ms, 1), "logs_ms": round(logs_ms, 1),
            "logs_outcome": logs_resp["outcome"],
        })
        flag = "OK " if ok else "MISMATCH"
        inj = "" if caught is None else f"  inject-1 -> {'DETECTED' if caught else 'MISSED'}"
        print(f"  [{i+1}/{args.windows}] {start}-{end}  expected={expected:<3} logs={count:<3} {flag}{inj}")
        time.sleep(0.05)

    injectable = sum(1 for c in cases if c.get("omission_detected_after_injection") is not None)
    out = {
        "provenance": "live_natural_observation + controlled single-event injection",
        "protocol": "wormhole_core_nextSequence",
        "chain": "ethereum",
        "rpc": url,
        "core": WH_CORE,
        "emitter": args.emitter,
        "window_blocks": args.width,
        "windows": len(cases),
        "boundary_readable": readable,
        "prefix_matches": matched,
        "prefix_match_rate_of_readable": (matched / readable) if readable else None,
        "injection_windows": injectable,
        "injection_detected": injected_caught,
        "claim": (
            "Wormhole's nextSequence(emitter) counter is readable at historical "
            "heights and its delta matches LogMessagePublished counts on complete "
            "replies; dropping one event makes the same audit fail, so a silent "
            "omission is detectable on a second protocol."
        ),
        "cases": cases,
    }
    DATA.mkdir(parents=True, exist_ok=True)
    path = DATA / "wormhole_min_check.json"
    path.write_text(json.dumps(out, indent=2) + "\n")

    print(f"\nboundary readable : {readable}/{len(cases)}")
    print(f"prefix match      : {matched}/{readable}")
    print(f"injection detected: {injected_caught}/{injectable}")
    print(f"wrote {path}")


if __name__ == "__main__":
    main()
